### ISSUE TITLE
PlaintextHelpFormatter prints message incorrectly

### ISSUE THREAD

**Issue by RanolP** [ajalt/clikt#10]
I used this library to make my cli program, but the help message printed incorrectly like this:
```
  -L, --lorem-ipsum                
                                   It is lorem ipsum text, just ignore it. I
                                   think it
                                   doesn't
                                   works
                                   correctly.
```

I expected help message like this:
```
  -L, --lorem-ipsum                
                                   It is lorem ipsum text, just ignore it. I
                                   think it doesn't works correctly.
```

So I traced that why the help message formats incorrectly. And I found the reason. If the length of local variable `subsequentIndent` of Extension method `StringBuilder.appendDefinitionList (in PlaintextHelpFormatter.kt)` is so long, The help message format broken. And I traced why. It's the problem of `StringBuilder.wrapParagraph (in text.kt)`. It must resets the length of local variable `currentWidth` to 0, but it resets to `subsequentIndent.length`. So I changed the code. And it works.

Could you fix the code I pointed out? It would make this project more useful.

(Sorry for my bad english. Thank you for reading this article, which may be disrespectful or annoying.)

**Comment by ajalt** [comment]
Thanks for the report and the clear reproduction! Resetting `currentWidth` to 0 causes problems in some other cases, but you can check out #11 for an explanation of the root cause if you're curious.
