### ISSUE TITLE
Outdated documentation in "advanced" section

### ISSUE THREAD

**Issue by PegasisForever** [ajalt/clikt#108]
All the codes related to ↓ seems not working.
```kotlin
class Command : CliktCommand() {
    init {
        context {
            ...
        }
    }
}
```

The IDE tells me `Expression 'context' of type 'Context' cannot be invoked as a function. The function 'invoke()' is not found`.
Example: <https://ajalt.github.io/clikt/advanced/#token-normalization>

**Comment by PegasisForever** [comment]
Sorry it seems like is my IDE issue, now i can use the code without errors.

**Comment by jorunfa** [comment]
@PegasisForever: What did you do to make it work?

**Comment by jorunfa** [comment]
I figured it out.
I had this import:
`import com.github.ajalt.clikt.core.Context`

when I needed to have this one (small `c` in `context):

`import com.github.ajalt.clikt.core.context`
