### ISSUE TITLE
Create an alias for findObject, like getOrPut

### ISSUE THREAD

**Issue by sschuberth** [ajalt/clikt#110]
Personally, I have to say that I find the name `findObject` for the variant that is "setting `context.obj` if one is not found" *very* counter-intuitive. How about renaming / creating an alias function for it named `getOrPut`, resembling [Kotlin's function for maps](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/get-or-put.html)?

**Comment by ajalt** [comment]
I can see your point about making the naming more intuitive. There are five related functions, and I don't think it makes sense to rename just one. I'm open to renaming all of them (and deprecating the current names) if we can come up with consistent names for all five.

The five functions are:

1. [`Context.findObject()`](https://ajalt.github.io/clikt/api/clikt/com.github.ajalt.clikt.core/-context/find-object/) which returns a nullable value.
2. [`Context.findObject(default)`](https://ajalt.github.io/clikt/api/clikt/com.github.ajalt.clikt.core/-context/find-object/) which sets the default value if not found.
3. [`CliktCommand.findObject()`](https://ajalt.github.io/clikt/api/clikt/com.github.ajalt.clikt.core/find-object/) extension that returns a ReadOnlyProperty that calls the nullable version of `Context.findObject`.
4. [`CliktCommand.findObject(default)`](https://ajalt.github.io/clikt/api/clikt/com.github.ajalt.clikt.core/find-object/) extension that returns a ReadOnlyProperty that calls the default value version of `Context.findObject`.
5. [`CliktCommand.requireObject()`](https://ajalt.github.io/clikt/api/clikt/com.github.ajalt.clikt.core/find-object/) extension that returns a ReadOnlyProperty that calls the nullable version of `Context.findObject` but throws an NPE if thee value isn't found.

Here's one set of possibilities:

1. `Context.getObjectOrNull()`
2. `Context.getOrPutObject()`
3. `CliktCommand.contextObjectOrNull()`
4. `CliktCommand.contextGetOrPutObject()`
5. `CliktCommand.contextObject()`

Those names are closer to what the stdlib uses for similar concepts, but I'm not a fan of how verbose they are. They also don't suggest the fact that these function search up the ancestors the way "find" does. I'm open to better suggestions.

**Comment by sschuberth** [comment]
Thanks for being open to renaming these! How about:

1. `Context.findObject()` (keep as-is)
2. `Context.findOrSetObject()`
3. `CliktCommand.findObject()` (keep as-is)
4. `CliktCommand.findOrSetObject()`
5. `CliktCommand.requireObject()` (keep as-is)

**Comment by ajalt** [comment]
Yeah, I like those names.

**Comment by sschuberth** [comment]
Thank you for the quick implementation!
