### ISSUE TITLE
Support different types for mutuallyExclusiveOptions?

### ISSUE THREAD

**Issue by sschuberth** [ajalt/clikt#113]
Sometimes it's useful if mutually exclusive options could be of different types. In my concrete case, an option is either a path to a `File`, or a `String` name of a resource. Currently, that's not supported as all mutually exclusive options need to be of the same type.

I tried to work around that by also treating the `File` as a `String`, but I did not find an elegant way then to determine which of the two options was given and whether I should convert the `String` to a `File` or not.

I acknowledge it's not possible to support different types for *all* mutually exclusive options, but maybe as a work-around we could at least support two different types for the first two mandatory `option1` and `options2` parameters of `mutuallyExclusiveOptions`?

In any case I'm also open to other suggestion how to elegantly tackle this issue.

**Comment by ajalt** [comment]
What would the type of the property be in that case? You'll need to create a sealed class with a type for each option. Something like this:

```kotlin
sealed class MyOption {
    data class StringType(val s: String) : MyOption()
    data class IntType(val i: Int): MyOption()
}

val opt by mutuallyExclusiveOptions(
    option().convert<MyOption> { MyOption.IntType(it.toInt()) },
    option().convert<MyOption> { MyOption.StringType(it) }
)
```

By design, you can't `convert` an option twice, so if you want to wrap a `file()` option in a sealed class, it takes a little more ceremony:

```kotlin
fun NullableOption<File, File>.inMyOption(): NullableOption<MyOption, MyOption> {
    return copy<MyOption?, MyOption, MyOption>(
            { MyOption.FileType(transformValue(it)) },
            { it.single() },
            { it.lastOrNull() },
            {})
}

val opt by option().file().inMyOption()
```

I can see the use case of wanting to reuse an existing conversion, so I might add an extension to make it easier.

**Comment by sschuberth** [comment]
> What would the type of the property be in that case?

Couldn't it simply be `Any`?

**Comment by ajalt** [comment]
If you just want `Any`, then you can cast each option:

```kotiln
val opt by mutuallyExclusiveOptions(
        option("-x").file() as OptionDelegate<Any?>,
        option("-y") as OptionDelegate<Any?>
)
```

I'm not sure why the type inference can't figure out the types without a manual cast.

**Comment by sschuberth** [comment]
Ah, cool, I'll give that a try and report back.

**Comment by sschuberth** [comment]
Hmm, that doesn't seem to be working. I'm passing mutually exclusive options on the command line, but *clikt* does not complain.

**Comment by sschuberth** [comment]
My fault, I forgot to call `.single()` 🙄 Looking all good now, thanks!
