### ISSUE TITLE
Make enum conversion case-insensitive by default

### ISSUE THREAD

**Issue by sschuberth** [ajalt/clikt#115]
I'd like to propose to make `enum` value conversion case-insensitive by default, because it's probably more convenient for the command line user to not care about casing, and the risk to accidentally refer to another `enum` value that just differs in case is rather low.

**Comment by sschuberth** [comment]
I was trying to work around this via `option(...).convert { it.toUpperCase() }.enum<...>()` to be able to use lower-case name for upper-case `enum` constants, but for some reason that does not work.

**Comment by sschuberth** [comment]
My work-around is to replace

    .enum<OutputFormat>()

with

    .choice(enumValues<OutputFormat>().associateBy { it.name }.toSortedMap(java.lang.String.CASE_INSENSITIVE_ORDER))

**Comment by sschuberth** [comment]
Or as a new extension function:

```
inline fun <reified T : Enum<T>> RawOption.enumCaseInsensitive(key: (T) -> String = { it.name }): NullableOption<T, T> {
    return choice(enumValues<T>().associateBy { key(it) }.toSortedMap(java.lang.String.CASE_INSENSITIVE_ORDER))
}
```

**Comment by ajalt** [comment]
That's a good idea. I decided to add an `ignoreCase` parameter to `enum` and `choice`, with value value defaulting to `false` for `choice`, and `true` for `enum`.

**Comment by sschuberth** [comment]
Even better, thanks a lot!
