### ISSUE TITLE
Clikt + jline

### ISSUE THREAD

**Issue by mel4tonin4** [ajalt/clikt#122]
Hello.

I'm trying to use Clikt with [jline](https://github.com/jline/jline3). I was already using Clikt in a REPL to minimize startup time.

I'm encoutering a few issues.

In order to build the a `org.jline.reader.Completer` from the `ClickCommand`, I need access to the registered sub-commands, options, and arguments, so, at the moment, I'm using reflection.

Something like this:

```
package com.aeyeonmovement.cliktshell

import kotlin.reflect.KClass

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.arguments.Argument
import com.github.ajalt.clikt.parameters.groups.ParameterGroup
import com.github.ajalt.clikt.parameters.options.Option
import com.github.ajalt.clikt.completion.CompletionCandidates

import org.jline.builtins.Completers
import org.jline.reader.Completer
import org.jline.reader.impl.completer.NullCompleter
import org.jline.reader.impl.completer.ArgumentCompleter
import org.jline.reader.impl.completer.StringsCompleter

class PrivateField<T : Any, V>(kClass : KClass<T>, name : String) {
    private val field by lazy {
        kClass.java.getDeclaredField(name).apply { isAccessible = true }
    }

    fun get(obj : T) : V = field.get(obj) as V
}

class PrivateMethod<T : Any, TArg0 : Any, TResult>(kClass : KClass<T>, name : String, arg0KClass : KClass<TArg0>) {
    private val method by lazy {
        kClass.java.getDeclaredMethod(name, arg0KClass.java).apply { isAccessible = true }
    }

    fun invoke(obj : T, arg0 : TArg0?) : TResult = method.invoke(obj, arg0) as TResult
}

private object Clikt {
    val CliktCommand_subcommands = PrivateField<CliktCommand, List<CliktCommand>>(CliktCommand::class, "_subcommands")
    val CliktCommand_options = PrivateField<CliktCommand, List<Option>>(CliktCommand::class, "_options")
    val CliktCommand_arguments = PrivateField<CliktCommand, List<Argument>>(CliktCommand::class, "_arguments")
    val CliktCommand_groups = PrivateField<CliktCommand, List<ParameterGroup>>(CliktCommand::class, "_groups")

    val CliktCommand_createContext =
        PrivateMethod<CliktCommand, Context, Unit>(CliktCommand::class,"createContext", Context::class)
}

internal val CliktCommand.registeredSubcommands get() =
    Clikt.CliktCommand_subcommands.get(this)
internal val CliktCommand.registeredOptions get() =
    Clikt.CliktCommand_options.get(this)
internal val CliktCommand.registeredArguments get() =
    Clikt.CliktCommand_arguments.get(this)
internal val CliktCommand.registeredGroups get() =
    Clikt.CliktCommand_groups.get(this)

internal fun CliktCommand.createContext(parent : Context? = null) =
    Clikt.CliktCommand_createContext.invoke(this, parent)

fun CompletionCandidates.toNameSet() = when(this) {
    is CompletionCandidates.Fixed -> candidates
    else -> emptySet()
}

internal fun CliktCommand.makeJLineTreeCompleter() : Completers.TreeCompleter =
    Completers.TreeCompleter(registeredSubcommands.map { it.makeJLineCompleterNode() })

internal fun CliktCommand.makeJLineCompleterNode() : Completers.TreeCompleter.Node =
    registeredSubcommands.let { subcommands ->
        if (subcommands.isEmpty()) {
            val options = registeredOptions.flatMap {
                (it.completionCandidates.toNameSet() + it.names).toList()
            }
            val optionValues = mapOf<String, List<String>>()
            Completers.TreeCompleter.node(
                ArgumentCompleter(
                    StringsCompleter(commandName),
                    Completers.OptionCompleter(
                        NullCompleter.INSTANCE, optionValues, options, 1
                    )
                )
            )

        } else {
            Completers.TreeCompleter.node(commandName, *subcommands.map { it.makeJLineCompleterNode() }.toTypedArray())
        }
    }

```

[Completion of command options is not working in the code above. I still don't understand the jline API in many parts.]

~~Since the parsing is being performed by jline, and I'm not calling `CliktCommand.main()` or `CliktCommand.parse()`, I have to invoke `createContext()` by myself, which I'm doing by the same means.~~ That's is not the reason. Here's why I need to call createContext() explicitly: my context objects are often closeable() and so is my root CliktCommand. If I start the shell and close it without calling any CliktCommand, there is an attempt to close a context which was never created, which causes an exception.

The help messages display the name of the root CliktCommand in front of the chain of subcommands. I'm setting the root command's name to the empty string, so that I only get an extra space at the beginning of the command description, to minimize this inconsistency.

~~After displaying help messages, Clikt quits. I have no workaround for this, at the moment.~~ _[I was using main() instead of parse()]_

Do you have any suggestions?
Would you consider pull requests for changes that improve the interoperability between Clikt and and jline?

Thanks for reading.

**Comment by ajalt** [comment]
I've had discussions about JLine in the past, and heard that Clikt is easy enough to integrate into JLine as it is, so I've never added more code to accommodate.  

[Here's an example of an app that integrates Clikt with JLine without any reflection](https://github.com/square/leakcanary/blob/master/shark-cli/src/main/java/shark/InteractiveCommand.kt)

I am of course willing to discuss improvements to Clikt if you have specific ideas.

**Comment by mel4tonin4** [comment]
Thanks for your reply, ajalt.

Two considerations.

**"Integrating" is a vague word, so I should have been more precise.**

With "integrating Clikt and JLine", I mean:

1. running `CliktCommand`s from a JLine shell
2. extracting the information about `CliktCommand`s features and pass it to JLine without any additional (application-specific) code

The example that you linked does not qualify as "integration" in this sense: it just run a JLine shell from a `CliktCommand`. The commands executed by this shell are implemented using a custom representation which has nothing to do with Clikt. There are two different representations of the concept of "command". I suppose that satisfied the needs of that project.

The `main()` function of my application used to be that of a typical Clikt application. Something like:

```
fun main(args: Array<String>) {
    Root().main(args)
}
```

where `Root` is the `CliktCommand` representing the root of the hierarchy of nested commands that my application can execute.

Now it becomes

```
fun main(args: Array<String>) {
    ReadEvaluatePrintLoop.run(
        Root(),
        prompt = ">> "
    )
}
```

where `ReadEvaluatePrintLoop` is part of the clikt-jline bridge and takes care of generating the completers for the `CliktCommand`s, and `Root` is the same `CliktCommand` as before.

The command line of the application is not used, at the moment, but obviously it can be used, through an additional `CliktCommand`, to alter the behaviour of the REPL and configure the `Root` command and its context.

The `run()` method of `ReadEvaluatePrintLoop` is something like this:

```
    fun run() {
        whileTrue {
            catchingAllExceptions {
                rootCmd.createContext()

                // Interaction with the console is handler by jline
                // Completion happens here, among other things
                val line = reader.readLine(prompt, rightPrompt, null as MaskingCallback?, null)
                if (line.matches(COMMENT_REGEX)) {
                    return@catchingAllExceptions
                }

                // jline does also parsing
                val pl = reader.parser.parse(line, 0)
                val argv = pl.words().toTypedArray()
                val command = Parser.getCommand(pl.word())

                if (builtins.hasCommand(command)) {
                    // We execute jline built-in commands
                    builtins.execute(
                        command, argv.copyOfRange(1, argv.size), System.`in`, System.out, System.err
                    )
                } else {
                    // Otherwise we attempt to execute a Clikt command
                    catchingCliktExceptions {
                        rootCmd.parse(argv)
                    }
                }
            }
        }
    }
```

**I used reflection as a temporary workaround**

There should be no need to use reflection to build the completers from the `ClickCommand`s. I just used it to acquire access to few private members. A handful of read-only accessors would fix this problem.

So far, my experience with this setup is limited, and here are

**the improvements I'm suggesting**

1. public access to read-only lists of subcommands, options, arguments and groups: 

```
    val registeredSubcommands : List<CliktCommand> get() = _subcommands
    val registeredOptions : List<Option> get() = _options
    val registeredArguments : List<Argument> get() = _arguments
    val registeredGroups : List<ParameterGroup> get() = _groups 
```

2. public access to `createContext()`
3. possibility to remove the name of the root command from the help messages

Anything equivalent would also be equally welcome.

It's also possible that I will encounter other problems as I use this setup daily.

Thanks for reading this long message.

**Comment by mel4tonin4** [comment]
Ok, the next issue is that `CliktCommand`s can't be re-used.

Running the shell as described above, each `CliktCommand` arguments are parsed only the first time that a command is invoked. So if you call the same command multiple times with different sets of parameters, the command is executed always as if it was called with the first set of parameters.

This means that the current implementation of Clikt is incompatible with an usage inside a REPL.

I'll think about it and see if I can came with a valid suggestion for improvements in this area, because the first (simpler) ideas that came to my mind don't really work.

**Comment by mel4tonin4** [comment]
Is it difficult revert a `ClickCommand`'s parameters to their "pre-initialization" state, for example  with a `reset()` method in `NullableLateinit` (and possibly similar classes)?

**Comment by ajalt** [comment]
Thank you for the clarifications. Is there a reason that you need to reuse a command, rather than creating a new instance each time you want to parse argv?

**Comment by mel4tonin4** [comment]
The command tree is used once to extract the information about the commands available and their arguments and generate the _jline3_ completers and the help information. Then they are used to actually perform the commands when they are invoked.

Besides performance reasons (resetting a `CliktCommand` before re-parsing its parameters is way cheaper than recreating the whole tree, and my application has lots of commands), in order to recreate the command for each execution I have to publish a somehow broken API.

I did just what you proposed, and, now, instead of writing:

```
fun main(args: Array<String>) {
    ReadEvaluatePrintLoop.run(Root())
}
```

I'm writing

```
fun main(args: Array<String>) {
    ReadEvaluatePrintLoop.run({ Root() })
}
```

That is, instead of providing a pre-built `CliktCommand` tree to `ReadEvaluatePrintLoop`, I'm passing a factory in the form of a lambda.

That factory will be invoked once when the `ReadEvaluatePrintLoop` object is created and the `completer` is generated and used to instantiate the jline3 `reader` and once each time we execute one of the commands of our application.

So there is an implicit requirement that the factory returns a `CliktCommand` tree which has the same structure and features, each time it's called, otherwise the completion will be broken.

If I pass a reference to the root command, instead of a factory, I don't have this weak point in the API, as this requirements is guaranteed by the compiler.

You may consider this just a matter of style.

Of course, I can presently live with an API of this kind. I just won't release this reausable "clikt shell powered by jline3" companion library to the public. That's all. Nobody is going to cry for that, and I can continue my work.

**Comment by mel4tonin4** [comment]
I managed to make completion of options of nested arguments to work in _JLine 3_.
The code which generates the completers, now looks like this:

```
internal fun CliktCommand.makeJLineTreeCompleter() : Completer =
    AggregateCompleter(registeredSubcommands.map { it.makeJLineTreeCompleter(emptyList()) })

internal fun CliktCommand.makeJLineTreeCompleter(parentCommandPath : List<CliktCommand>) : Completer =
    registeredSubcommands.let { subcommands ->
        val commandPath = parentCommandPath + listOf(this)
        if (subcommands.isEmpty()) {
            ArgumentCompleter(
                commandPath.map { StringsCompleter(it.commandName) } + listOf(
                    Completers.OptionCompleter(
                        registeredArguments.map { it.makeJLineTreeCompleter() },
                        Function { _ -> registeredOptions.flatMap { it.makeJLineDescription() } },
                        commandPath.size
                    )
                )
            )
        } else {
            AggregateCompleter(subcommands.map { it.makeJLineTreeCompleter(commandPath) })
        }
    }

```

which uses the following methods 

```

internal fun CompletionCandidates.makeJLineCompleter() = when(this) {
    is CompletionCandidates.Fixed -> StringsCompleter(candidates)
    is CompletionCandidates.Path -> Completers.FileNameCompleter()
    is CompletionCandidates.Username -> UsernameCompleter()
    is CompletionCandidates.Hostname -> HostnameCompleter()
    else -> NullCompleter.INSTANCE
}

internal fun Option.makeJLineDescription() : List<Completers.OptDesc> {
    val valueCompleter = completionCandidates.makeJLineCompleter()

    return names.map { Completers.OptDesc(it, it, help, valueCompleter) } +
        secondaryNames.map { Completers.OptDesc(it, it) }
}

internal fun Argument.makeJLineTreeCompleter() : Completer {
    return NullCompleter.INSTANCE
}
```

Since _Clikt_ allows multiple (short and long) names for an option, as opposed to a pair of long name and short name, I choose to create different option descriptions for each of the names.

_Clikt_ has a deals with the problem of "completion" with the `completionCandidates` property. As far as I can understand (I never used this feature) this is used to provide completion hints to external shells. We can specify an explicit set of string, or indicate completion with usernames, paths or hostnames. I already supported this in the code above, for options, by implementing an `UsernameCompleter` and a `HostnameCompleter` (if I don't need them, at the moment).

In my application, I also would like to dynamically complete arguments using data coming from tables in the database and other application-specific sources.

One method to do this would be providing completion sources for different kind of data types.

The issue here is that I don't see a way to check the type of an argument at runtime, due to type erasure: a type like `ProcessedArgument<AllT, ValueT>` will have lost information about type `ValueT` by the time I need it to create the completer.

Otherwise one could thing to extend the types of `CompletionCandidates` to carry this information.

Do you have any suggestion?

Thanks for your patience.

**Comment by ajalt** [comment]
The latest release of Clikt adds the experimental [`CompletionCandidates.Custom`](https://ajalt.github.io/clikt/api/clikt/com.github.ajalt.clikt.completion/-completion-candidates/-custom/) that you could use to implement whatever completion you want.

If you need to carry extra runtime information, you could create a  `class MyCompletion: (ShellType) -> String?`, and store that in the `Custom` class. It's a bit of a kludge, but it should work.

**Comment by ajalt** [comment]
#138 added public functions to get registered subcommands/parameters/groups, so you should be able to use them instead of reflection.
