### ISSUE TITLE
Converters should be eagerly computed

### ISSUE THREAD

**Issue by sgarfinkel** [ajalt/clikt#123]
Sometimes it's nice to set default values based on other options and arguments in the same command. However, converters do not get eagerly computed as far as I can tell, which causes spurious NPEs when trying to use those values in defaultLazy.

Here's a simple example:
```kotlin
object Example: NoRunCliktCommand() {
    val foo by option().defaultLazy { "$bar" }
    val bar by argument().long()
}

fun main(args: Array<String>) = Example.main(args)
```

**Comment by ajalt** [comment]
Conversions are computed eagerly as soon as the parameter is parsed on the command line. It wouldn't be possible to refer to other parameters in conversions regardless of when the conversions are run. For example:

```
class Example: NoRunCliktCommand() {
    val foo by option().defaultLazy { "$bar" }
    val bar by option().defaultLazy { "$foo" }
}
```

There's only two ways to implement that: throw an exception, or go into an infinite loop. I choose to do the former.

Note that `validate` functions run after all the parameters have been set, and so can refer to parameters freely.

**Comment by sgarfinkel** [comment]
Ah, I follow you. Do you know how the builtin `lazy { }` handles this situation?

**Comment by ajalt** [comment]
`lazy` would throw a `StackOverflowError` if you did that.

**Comment by sgarfinkel** [comment]
Then I suppose this can be closed as "wont-fix". I can see how this could cause some unexpected behavior if implemented.
