### ISSUE TITLE
Correctly Display Large ASCII Art in Help Message

### ISSUE THREAD

**Issue by JSextonn** [ajalt/clikt#124]
I have some large ASCII art I would like to display in my help message. The formatter was automatically line wrapping the text and obviously messing up the art. I've got it working with the below snippet.

```kt
init {
        context { helpFormatter = CliktHelpFormatter(width = 1000) }
}
```

I was wondering if there is a better or recommended solution to accomplish this? Does Clikt have a `RawFormatter` similar to pythons [RawDescriptionHelpFormatter](https://docs.python.org/2/library/argparse.html#formatter-class)?

**Comment by ajalt** [comment]
No need for a raw formatter. You can [pre-format individual paragraphs](https://ajalt.github.io/clikt/documenting/#preformatting-paragraphs).

**Comment by JSextonn** [comment]
@ajalt Using the triple back ticks did not solve the problem, unless I overlooked something. Not all white space is being preserved as I would have expected.

```
class MyCommand: CliktCommand(
    help = """
        ```
        test
             another test
                              yet another test
        ```
    """
)
```

The above help output:

```
 test
 another test
 yet another test

```

But I would expected:
```
test
     another test
                      yet another test
```

Am I missing something?

**Comment by ajalt** [comment]
No, that looks like a bug to me.

**Comment by ajalt** [comment]
This should be fixed in the latest snapshots. Thanks for the report!
