### ISSUE TITLE
Add the possibility to retrieve all subcommands (not only their commandName)

### ISSUE THREAD

**Issue by michgauz** [ajalt/clikt#126]
Hello,
The title is pretty exhaustive.
It would be cool to retrieve the subcommands of a command.

My usage would be the merge of two commands having the same commandName

Thanks !

**Comment by ajalt** [comment]
Can you elaborate more on what you're trying to do?

**Comment by michgauz** [comment]
Sure. Thanks for the quick answer :)

I have a ServiceLoader, loading different list of `CliktCommand`, each one with subCommands
I would like to merge commands with the same command name, so achieve something like that :

**List A**
command1
-->subCommand11
-->subCommand12

command2
-->subCommand21
-->subCommand22

**List B**
command1
-->subCommand13
-->subCommand14

command3
-->subCommand31
-->subCommand32

**List I would like to build**
command1
-->subCommand11
-->subCommand12
-->subCommand13
-->subCommand14

command2
-->subCommand21
-->subCommand22

command3
-->subCommand31
-->subCommand32

**Comment by ajalt** [comment]
Hmm, I don't think manually adding the same command instance to two parents is the right way to solve your problem.

This seems like something better solved in your service loader. Maybe something equivalent to [koin's named bindings](https://doc.insert-koin.io/#/koin-core/definitions?id=definition-naming-amp-default-bindings) combined with `Koin.getAll`, with a name for each top-level command?

Or maybe you have a base class/interface for each top-level command that children of that command should implement, and you could load all the children using that base class?

**Comment by michgauz** [comment]
Yep but I don't know in advance which top-level command I will have.
Seems that merging subcommands is far simpler

And actually subCommands are a command property. So add a getter seems to not be very exotic ;)

**Comment by michgauz** [comment]
We have considered an other solution to fit our needs. 
Thanks for your answer 👍
