### ISSUE TITLE
Rename NoRunCliktCommand

### ISSUE THREAD

**Issue by ajalt** [ajalt/clikt#130]
The name [`NoRunCliktCommand`](https://ajalt.github.io/clikt/api/clikt/com.github.ajalt.clikt.core/-no-run-clikt-command/) is not great. 

If you can think of something better, please leave your suggestions in the comments of this issue.

**Comment by sebokopter** [comment]
IMHO a typical usecase for `NoRunCliktCommand` is for having it as a skeleton for subcommands.

I'd suggest `SkeletonCliktCommand` therefore.
If you would like to explain what it is technically, than `NoopCliktCommand` would be my choice.

Other names which did come to my mind:
- Root(Clikt)Command
- Super(Clikt)Command
- Parent(Clikt)Command
- Plumbing(Clikt)Command
- Scaffolding(Clikt)Command
- Staging(Clikt)Command
- Abstract(Clikt)Command
- Empty(Clikt)Command
- HelpOnly(Clikt)Command

**Comment by sschuberth** [comment]
I'd also vote for `Empty(Clikt)Command` or `NoOp(Clikt)Command`.

**Comment by ajalt** [comment]
Thank you for the suggestions! I decided to go with `NoOpCliktCommand`. 

I agree that it's not commonly used, but some people prefer treating their commands like data classes, and writing the business logic externally. That doesn't scale to subcommands, but it's easy enough to support that I don't mind leaving the class around.
