### ISSUE TITLE
Help sub-command

### ISSUE THREAD

**Issue by qw3ry** [ajalt/clikt#136]
I'd like to create a program where the help works similar to `git`:
```bash
$ git help
$ git help add
```
etc.

Is there some help-subcommand I can add to `CliktCommand.subcommands(...)`? Do I have to create this myself?

**Comment by ajalt** [comment]
That particular pattern isn't built in to Clikt. However, `git help` produces the same output as `git --help`, and `git help add` is the same as `git add --help`. The `--help` option works out of the box with Clikt, so I recommend sticking with that pattern.

If you still want to implement the subcommand pattern, you can do so by throwing [PrintHelp](https://ajalt.github.io/clikt/api/clikt/com.github.ajalt.clikt.core/-print-help-message/) with the command you want help printed for.

**Comment by qw3ry** [comment]
Thank you for the quick response.
I created a PR adding this functionality, if you are interested.

**Comment by ajalt** [comment]
See comments in #137
