### ISSUE TITLE
Add option/argument converters for java.nio.Path

### ISSUE THREAD

**Issue by benjamin-bader** [ajalt/clikt#14]
`java.nio.Path` supplants `java.io.File` in JDK 8+; it would be quite useful to be able to have options of this type, e.g. with a `path` extension to `RawArgument`/`RawOption`.  This would be presumably identical to the `.file(...)` API:

```kt
/**
 * Convert the option to a [Path].
 *
 * @param exists If true, fail if the given path does not exist
 * @param fileOkay If false, fail if the given path is a file
 * @param folderOkay If false, fail if the given path is not a directory
 * @param writable If true, fail if the given path is not writable
 * @param readable If true, fail if the given path is not readable
 * @param fileSystem If specified, the [FileSystem] with which to resolve paths.
 */
fun RawOption.path(
    exists: Boolean = false,
    fileOkay: Boolean = true,
    folderOkay: Boolean = true,
    writable: Boolean = false,
    readable: Boolean = false,
    filesystem: FileSystems.getDefault()): NullableOption<Path, Path>
``` 

The only real difference here is the addition of a `FileSystem` param, which can be safely defaulted 99% of the time.

I'm using something like this internally at present; happy to open a PR if there are no objections to the API.

**Comment by ajalt** [comment]
Currently, clikt targets Java 6. We could potentially create a `clikt-jvm8` module, but it's probably fine to just raise the target to Java 8 instead. Feel free to submit a PR.
