### ISSUE TITLE
Think about custom exit codes again

### ISSUE THREAD

**Issue by sschuberth** [ajalt/clikt#151]
This is a follow-up of the discussion at https://github.com/ajalt/clikt/issues/44. Customizing exit codes is currently possible in two ways:

> call [parse](https://ajalt.github.io/clikt/api/clikt/com.github.ajalt.clikt.core/-clikt-command/parse/) instead of [main](https://ajalt.github.io/clikt/api/clikt/com.github.ajalt.clikt.core/-clikt-command/main/), [catch CliktExceptions](https://github.com/ajalt/clikt/blob/425b28234eb4bf03887a5f9b07455d50439d0b84/clikt/src/main/kotlin/com/github/ajalt/clikt/core/CliktCommand.kt#L229-L248), and exit with whatever values you want

(quote from [here](https://github.com/ajalt/clikt/issues/44#issuecomment-541758494))

and

> a `statusCode` property to `UsageError`

(quote from [here](https://github.com/ajalt/clikt/issues/44#issuecomment-548175150))

Both these ways require an exception to be thrown, which fits well if the idea is that a non-zero exit code denotes an abnormal program termination or a usage error.

However, if writing e.g. a command line tool that performs some kind of check e.g. on source code, and this tool is used e.g. in CI, you usually want to indicate via a non-zero exit code that the check failed. That is, the check itself was performed successfully, but the source code (in this example) did not pass it. In that sense, it would be semantically wrong to throw an exception or `UsageError` as there was nothing wrong with the usage. For such cases it would be great to be able to modify the exit code without throwing an exception and interrupting the normal program flow.

That's why I'd like to suggest [again](https://github.com/ajalt/clikt/issues/44#issuecomment-541807802) that `run` should simply return an `Int` which is used as the exit code. Alternatively, to not require existing code to be changed to `return 0` in normal cases, `CliktCommand` could get a `var statusCode = 0` which is used in `main` where currently `0` is hard-coded in the calls to `exitProcessMpp` (and a final call to `exitProcessMpp` would been to be added at the end of `main` to customize the exit code). Then commands could simply modify `statusCode` before they return, if required.

**Comment by ajalt** [comment]
Thanks for the feedback. I do agree that it should be easier to choose the exit code.

> it would be great to be able to modify the exit code without throwing an exception and interrupting the normal program flow

I'm not sure I follow here: exiting with a status code inherently ends program flow.

> run should simply return an Int

I'm -1 on this, since it would require all users to add `return 0` to their run bodies

> CliktCommand could get a var statusCode = 0

I'm also -1 on this, since I'd prefer minimizing state and side effects.

---

The solution I'm leaning towards is adding a `statusCode` property to `Abort`, or maybe adding a new exception with that property. That way, the majority of commands that don't want to customize the status code can continue to work the same as they currently do, but commands that need a custom status code could throw the exception.

**Comment by sschuberth** [comment]
> I'm not sure I follow here: exiting with a status code inherently ends program flow.

In the JVM world, [you're correct](https://stackoverflow.com/a/28738376/1127485). That is, if you want to set a non-zero exit code, you have to call `System.exit()` in one way or the other.

My thinking probably comes from the C/C++ world where setting the exit code is done by returning an `int` from `main()` without *explicitly* calling `exit()`. With that in mind, I do not regard a `System.exit()` call as the last statement in `main()` as a program flow interruption, simply because the program would have ended then anyway, and there is no other way to set an exit code.

Exceptions on the other hand *really* break the program flow, and [should not be used for flow control](https://softwareengineering.stackexchange.com/q/189222/241369).

> The solution I'm leaning towards is adding a `statusCode` property to `Abort`, or maybe adding a new exception with that property.

If these are the options, I'd vote against `Abort` as that also has the notion of something that went wrong. So maybe a new `ProgramResultException` or `StatusCodeException`? In any case, for such a new exception [the logic that shows the help](https://github.com/ajalt/clikt/blob/b1d3bf86c29d9985479acda196a18be3ceb1c7a6/clikt/src/commonMain/kotlin/com/github/ajalt/clikt/core/exceptions.kt#L78) should no kick in, as the user did not do anything wrong in calling the program and does not require any help.

**Comment by sschuberth** [comment]
> a status code doesn't make sense for subcommands.

[Turns out](https://github.com/ajalt/clikt/issues/342) it *does*, for chained subcommands.
