### ISSUE TITLE
Usage example for accepting a Date/Time option and converting toa Date

### ISSUE THREAD

**Issue by talmdal** [ajalt/clikt#153]
I'm trying to create an option that takes a date string and convert that to a java.util.Date.

`
val startDate: Date by option("--startDate", help="start date).????  { dateFormatter.parse(it) }
`
I've tried convert and transformValue, neither works
convert generates the following error:
 Property delegate must have a 'getValue(Application, KProperty*>)' method. None of the following functions is suitable.
getValue(ParameterHolder, KProperty<*>) defined in kotlin.properties.ReadOnlyProperty

transformValue gives:
Type 'String' has no method 'getValue(Application, KProperty<*>)' and thus it cannot serve as a delegate
No value passed for parameter 'p1'

I couldn't find any usage examples on the web.

Could you please provide an example of how to do this.
Thanks

**Comment by ajalt** [comment]
`convert` is correct, but options are nullable by default, so you would just need to declare your property as `val startDate: Date?` or use something like `.convert{...}.default(Date())` (or `multiple`, `required` etc.)

**Comment by talmdal** [comment]
thanks for the quick response. That did the trick
