### ISSUE TITLE
Migrate build scripts to Kotlin?

### ISSUE THREAD

**Issue by sschuberth** [ajalt/clikt#155]
Just wondering, since this is a pure Kotlin project, is there any interest in migrating the Gradle build files from Groovy to Kotlin?

**Comment by ajalt** [comment]
The main one already is: e.g. https://github.com/ajalt/clikt/blob/master/clikt/build.gradle.kts

The others are just a couple of lines each.

**Comment by sschuberth** [comment]
Ok, it's probably a bit weird to have this mix, but I guess you want to keep the samples to be using Groovy DSL to address a wider audience?

**Comment by ajalt** [comment]
Not really, I just never updated them. I'd accept a PR, or I can do it when I get a chance.

**Comment by sschuberth** [comment]
> I'd accept a PR

Here you go: https://github.com/ajalt/clikt/pull/160
