### ISSUE TITLE
Wrong line separator when used in git bash

### ISSUE THREAD

**Issue by Legion2** [ajalt/clikt#161]
I'm using my cli on a windows machine with git bash. The git bash is a linux like environment and the default line separator for all the linux programs of git bash is `\n`. But the cli output uses `\r\n` which causes `^M` to appear in the output. In most cases this is not a problem, because this character is not visible, but if the output is consumed by another application, it causes problems.

For example I tried to add autocomplete to my cli application and for this I used the output of one command for completion of another command.

Workaround: Set the line separator explicitly to `\n`

**Comment by ajalt** [comment]
How can we detect that shell? Does git bash set an environment variable or something that we can check?

**Comment by oing9179** [comment]
> Does git bash set an environment variable or something that we can check?

Yes.

```bash
$ echo $OS
Windows_NT
$ echo $MINGW_CHOST
x86_64-w64-mingw32
$ echo $MSYSTEM
mingw64
```

**Comment by ajalt** [comment]
So looking into this more, I think the current behavior is correct. You said that the MinGW console actually handles the CR fine. It's just when you try to `echo` to a bash completion file that the CR matters. In that case, it doesn't matter what terminal you're running from, you always want LF line endings.

If you're using `echo`, you can pass `lineSeparator = "\n"`. You can also force line endings for all output in a command like this:

```kotlin
class NewlineConsole : CliktConsole by defaultCliktConsole() {
    override val lineSeparator: String get() = "\n"
}

class Cli : CliktCommand() {
   init {
       context {
           console = NewlineConsole()
       }
   }
}
```

Note that the built in completion mechanism always uses CR for bash and ZSH completion.
