### ISSUE TITLE
Following symbolic links for @args files

### ISSUE THREAD

**Issue by rockwotj** [ajalt/clikt#172]
Hello! Thanks for the great library. We use https://bazel.build as our build system and it makes heavy use of symbolic links. I believe @args files don't support symlinks (at least on the JVM) would you accept a patch to add support for following symbolic links? I only really care about the JVM, but would add support to all platforms if that is a requirement.

**Comment by ajalt** [comment]
I'm surprised that `File` doesn't already follow symlinks. I would definitely accept a PR that added this functionality.

All you'd need to do is update the implementations of [`readFileIfExists`](https://github.com/ajalt/clikt/blob/a0c33ab8f4ca341aa9f35deae10e25e2bb683742/clikt/src/commonMain/kotlin/com/github/ajalt/clikt/mpp/MppH.kt#L15). 

The [JVM version](https://github.com/ajalt/clikt/blob/a0c33ab8f4ca341aa9f35deae10e25e2bb683742/clikt/src/jvmMain/kotlin/com/github/ajalt/clikt/mpp/MppImpl.kt#L24-L28) is currently based on `File.bufferedReader`.
