### ISSUE TITLE
Is it possible to make user input password hidden with asterisks? (promptForLine, hideInput = true)

### ISSUE THREAD

**Issue by kgruhler** [ajalt/clikt#182]
Hi together,
 
is there a possibility to make the user input hidden with asterisks instead of hiding the complete input?
I'm using **promptForLine** together with **hideInput = true**. 
Background is that some users complain that they didn't have a feedback while they input their password and are getting confused, although this is a common behavior for password prompts I guess.

Thanks in advance, 
Br

**Comment by ajalt** [comment]
I don't think that's possible to provide on JVM without extra dependencies. Clikt uses Java's `Console.readPassword`, which doesn't allow specifying a mask character.

I know JLine provides a `LineReader` which can do what you want. You should be able to [setyour `CliktConsole`](https://ajalt.github.io/clikt/advanced/#replacing-stdin-and-stdout) to something like this (untested):

```kotlin
import org.jline.reader.LineReaderBuilder

class MaskingConsole(private val console: CliktConsole): CliktConsole by console {
    override fun promptForLine(prompt: String, hideInput: Boolean): String? {
        return if (hideInput) {
            val reader = LineReaderBuilder.builder().build()
            reader.readLine(prompt, "", "*", "")
        } else {
            console.promptForLine(prompt, hideInput)
        }
    }
}
```
