### ISSUE TITLE
Breaking changes for Clikt 3.0

### ISSUE THREAD

**Issue by ajalt** [ajalt/clikt#185]
It seems like it's worth thinking about making a 3.0 release with some breaking changes. Here's what I have in mind so far. I love to get feedback and ideas on what other changes could be made.

1. Remove the concept of envvarSplit (#177)
1. Remove `@Deprecated` functions
1. Remove experimental annotations and stabilize those APIs. 
1. Change maven coordinates from `com.github.ajalt:clikt` to `com.github.ajalt.clikt:clikt`. The code's package would remain the same, but we have multiple modules now with MPP, and I think it makes more sense to group them in a `clikt` coordinate.
1. Make the `OptionWithValues` and `ProcessedArgument` constructors private (or make them interfaces with private implementations). Is anyone constructing these classes directly instead of using the `option()` and `argument()` functions? Is anyone using their `copy` functions? Having them public makes it hard to add functionality without breaking the API.

**Comment by sghpjuikit** [comment]
As nobody has replied yet, I may as well chip in. The changes do not seem to be breaking in a very serious way, so I say go for it (sooner the better). A migration documentation would be welcome though, probably on the release page.

Disclaimer: I would not be affected by the listed changes.

**Comment by JakeWharton** [comment]
Here's a crazy one: make `run` a `suspend fun`. This would require either making the public API also `suspend` or depending on the kotlinx.coroutines library and using `runBlocking` internally.

Personally, almost all my commands look like
```kotlin
override fun run() = runBlocking {
  // ...
}
```

**Comment by ajalt** [comment]
Making `run` a suspend function would allow you to write `override suspend fun run() {` instead of `override fun run() = runBlocking {`, which saves 7 characters and looks cleaner.

That would definitely be nice, but the drawback is that people who don't call suspend functions now have to add the `suspend` modifier to their functions, which adds 8 characters.

In terms of implementation, since `runBlocking` doesn't exist on Kotlin/JS, I think I'd have to make `main` and `parse` suspend functions as well, requiring people to using a suspending main in their scripts.

It seems like the drawbacks of a suspending `run` outweigh the advantages.

**Comment by ajalt** [comment]
Version 3.0.0-rc has now been released. Thanks for the feedback!
