### ISSUE TITLE
Incorrect PrintHelpMessage return code

### ISSUE THREAD

**Issue by pgreze** [ajalt/clikt#187]
Facing a similar issue than #41 I tried to display the help message + return an error code, as it's specified in PrintHelpMessage javadoc:

https://github.com/ajalt/clikt/blob/8078c4866bbabe1321f3f0ac17fe22060befc8f6/clikt/src/commonMain/kotlin/com/github/ajalt/clikt/core/exceptions.kt#L25

Sadly the current behavior is returning the return code 0:

https://github.com/ajalt/clikt/blob/b9c1891de35ff8381b0eb3955e6ae13214dbf048/clikt/src/commonMain/kotlin/com/github/ajalt/clikt/core/CliktCommand.kt#L278

Considering help message is the expected output when using -h or --help which is already implemented by clikt, user usage of PrintHelpMessage would probably always means that help message is the consequence of an error.
If you agree with previous sentence, I would encourage enforcing javadoc behavior by fixing the code but still provide a way to show help message without failing (like Abort logic?).

In any case, thanks for your this nice project, always useful when trying to create Kotlin CLI 👍

**Comment by ajalt** [comment]
```
$ for i in git man ls cat bash grep awk cloc rg; do $i --help >/dev/null; echo $i : $?; done
git : 0
man : 0
ls : 0
cat : 0
bash : 0
grep : 0
awk : 0
cloc : 0
rg : 0
```

Every command line tool I looked at exits with status code 0 when they print their help message, so I think the current behavior is correct, and this is a bug in the documentation.

**Comment by pgreze** [comment]
@ajalt I agree, but you always tried with "--help", which of course should return 0.

But if you're trying:
```
$ git
usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
...
$ echo $?
1
```
Even if output is similar to --help, this is still an error, that's what I was talking about.

**Comment by ajalt** [comment]
I see. That's different than the `--help` case mentioned in the initial issue. I agree it makes sense to use an error code when the `printHelpOnEmptyArgs` or `invokeWithoutSubcommand` cases are triggered. 

I'll add an `error : Boolean` parameter to `PrintHelpMessage` and `PrintMessage` and use it for those cases. The `--help` case will continue to exit with 0.
