### ISSUE TITLE
Support Fish Autocompletion

### ISSUE THREAD

**Issue by sgarfinkel** [ajalt/clikt#189]
Autocomplete supports Bash and Zsh, but not Fish which is also extremely popular. It would be nice to have auto-generation of Fish completions.

Possible inspiration: https://github.com/spf13/cobra/blob/master/fish_completions.go

**Comment by faogustavo** [comment]
can I take this one?

**Comment by ajalt** [comment]
@faogustavo Absolutely. Feel free to ask here or on the #clikt channel in the kotlinlang slack if you have any questions.

**Comment by faogustavo** [comment]
@ajalt I've just opened a PR that does almost everything. It still has some work to do with `CompletionCandidates.Custom`. 
If you can take a look at the PR to see it and give your opinion I'll appreciate

**Comment by faogustavo** [comment]
Also, there are more useful links that helped me understand how to build a completion script for fish:
* https://github.com/fish-shell/fish-shell/blob/master/share/completions
* https://devmanual.gentoo.org/tasks-reference/completion/index.html
* https://fishshell.com/docs/current/cmds/complete.html
