### ISSUE TITLE
Passing strings with spaces to Options

### ISSUE THREAD

**Issue by aayushsanghavi** [ajalt/clikt#192]
Passing a string with spaces to an Option raises `Error: Got unexpected extra argument`

**Example:**
```
class Hello: CliktCommand() {
    val name by option(help="your name")
    val age by option(help="your age")
    override fun run() {
        echo("Hello, $name!")
    }
}
```

**Usage:**
`/hello --name=Foo Bar --age=20`

**Output:**
`Error: Got unexpected extra argument (Bar)`

**Expected behaviour:**
String values with spaces should work for an option

**Comment by ajalt** [comment]
This is an inherent behavior of shells. All programs function this way. If you want spaces in a value, you need to quote the value by surrounding it with `"` or `'`: `--name='Foo Bar'`

**Comment by aayushsanghavi** [comment]
Aah my bad. I forgot to mention that I had tried it by surrounding it with quotes as well but even that didn't work.

**Comment by ajalt** [comment]
I ran your code in bash and it works as expected when using quotes. 

```
$ ./hello --name='Foo Bar' --age=20
Hello, Foo Bar!
```

Are you using Windows cmd.exe? That shell only supports `"`, not `'`, for quoting, so try using double quotes if you aren't on a unix shell.

**Comment by benjaminRomano** [comment]
FWIW, I'm also running into this issue with `2.7.1` with both bash/zsh. If I find some time I'll try digging into this
