### ISSUE TITLE
Change main to accept Array<out String>

### ISSUE THREAD

**Issue by JakeWharton** [ajalt/clikt#196]
Since it never mutates the array and simply creates a list, `main(args: Array<String>)` should ideally be `main(args: Array<out String>)`. This will improve the compatibility with the three ways you can define the parameter for a normal `main` method.

Here's an illustrative example:
```kotlin
fun testMain(vararg varargString: String) {
  val arrayString: Array<String> = emptyArray()
  val arrayOutString: Array<out String> = emptyArray()
  
  exampleNoOut(varargString)
  exampleNoOut(arrayString)
  exampleNoOut(arrayOutString)
  
  exampleOut(varargString)
  exampleOut(arrayString)
  exampleOut(arrayOutString)
}

fun exampleNoOut(args: Array<String>) = Unit
fun exampleOut(args: Array<out String>) = Unit
```

And what it looks like in the IDE:
<img width="417" alt="Screen Shot 2020-06-19 at 4 11 59 PM" src="https://user-images.githubusercontent.com/66577/85176340-9cb8cb80-b247-11ea-83c1-5ace54c98e7e.png">

This is a binary-compatible change since variance is a concept solely implemented in the compiler (like generics in general). It also should be a source-compatible change as you can see above, but also because `Array<out String>` is more permissive than `Array<String>` in what it accepts.

**Comment by ajalt** [comment]
TIL that you can declare `main` as `vararg`. The bytecode's the same, so it makes sense, but I've never seen it mentioned in any docs.

**Comment by JakeWharton** [comment]
Same is true of Java!
```java
public static void main(String... args) {
}
```
