### ISSUE TITLE
Browser target

### ISSUE THREAD

**Issue by toth-istvan-zoltan** [ajalt/clikt#198]
Hi,

any chance of supporting the browser target, even with reduced functionality?

Would be very handy for me because I like to have a small shell in my SPA-s so I can issue commands manually, no need to build a whole interface. It is very similar to a terminal.

I've checked kotlinx.cli and it is very "noisy".

Thanks in advance,
tiz

**Comment by ajalt** [comment]
I'm not opposed to the idea, but I'm not sure what a CLI in a browser would look like. Can you give me examples of what you're looking for? Are there any existing websites that have this functionality?

**Comment by toth-istvan-zoltan** [comment]
Sure, here is a work-in-progress minimal shell I use right now. It is mostly an admin / developer tool.

Having a shell means I can provide commands and interfaces to use without the need of a UI.

This one particularly makes it possible to navigate in a tree of entities with parent - child relations (much like a file system), add entities, etc.

As I have a shell, I have no need to build UI for every small function I want to make reachable from the web. 

I'm actually a big fan of shells, old-timer here. :)

<img width="710" alt="Screenshot 2020-06-20 at 17 41 39 (2)" src="https://user-images.githubusercontent.com/16266294/85205838-14592a00-b31e-11ea-93a9-b3ef4810e4de.png">

**Comment by ajalt** [comment]
Interesting. So since there's no `println` in the browser, how should we print out help and error messages? If there's no general solution, we could potentially require browser users to always [define their own `CliktConsole`](https://ajalt.github.io/clikt/advanced/#replacing-stdin-and-stdout).

**Comment by toth-istvan-zoltan** [comment]
Yes, that was my idea (CliktConsole) to go with. However, when I added the Hello command to my source I've got this message on my browser console.

```
/Users/tiz/../build/js/packages_imported/clikt-clikt/2.7.1/clikt-clikt.js
Module not found: Error: Can't resolve 'child_process' in '/Users/tiz/../build/js/packages_imported/clikt-clikt/2.7.1'
```

At this point I decided to ask.

As for the browser console it is very simple. The only painful point is the separation of command arguments because that has to take care about the quotes / escaping.

The console you see above have an input at the bottom so I can type in the commands, and an "out" method. "Out" adds a "<pre>...</pre>" to the output area which is on the top.

I also added some handy features:

- command history (in session only, permanent raises security problems, probably should store on server side)
- the possibility to drop files on it, so you can actually manipulate / change /upload file data from the console in a secure manner (the browser controls file access to the client file system) 

If that helps, I can make this into a proper implementation so you can add it as an example.

I have an actual use-case for this functionality. We have a RFID reader software which can be started from shell or as a daemon. Our electrical engineers always complain about using SSH and the unix shell, so I could give them a browser based approach with the very same code I use for the shell itself. Everyone wins, code is the same everywhere, my server side is still clean as I provide the same API for shell / browser, no need for UI.

Sorry for the long post. I always wanted this and I see Clikt the right way to make it work.

**Comment by toth-istvan-zoltan** [comment]
Narrowed down the child_process problem. After gradle clean and new build the node_modules/child_process contains a README.md with:

```
This package name is not currently in use, but was formerly occupied
by another package.
```

**Comment by ajalt** [comment]
@toth-istvan-zoltan I added browser support in #199. Give that branch a try and let me know what you think. Does it work for you? Is there anything we could do to make it easier to use?

**Comment by toth-istvan-zoltan** [comment]
Thank you, this works well.

Webpack still complained about the internal Node dependencies but I've been able to solve that by adding a config extension to my MPP project. Attached the file, it has to be placed in the webpack.config.d directory as explained here: [Configuring webpack bundling](https://kotlinlang.org/docs/reference/js-project-setup.html#configuring-webpack-bundling)

Apart that all I had to do was to add the CliktConsole interface to my class.

I've also attached a small (quite imperfect) but working example.

I don't see anything else missing at this point, thanks for the support.

The project I needed this for will be on Github in a few months, I'll let you know so you may have a look how it works in a production environment.

[webpackAndSample.zip](https://github.com/ajalt/clikt/files/4828343/webpackAndSample.zip)

**Comment by ajalt** [comment]
@toth-istvan-zoltan I landed the PR with a hack that should fix the webpack warnings without needing to add anything to your configuration. Let me know if you have any issues with it. You can use the [latest snapshot](https://github.com/ajalt/clikt#snapshots) to try it out.

**Comment by toth-istvan-zoltan** [comment]
@ajalt Works great, no webpack warnings, thank you!
