### ISSUE TITLE
Boolean option

### ISSUE THREAD

**Issue by lgrammel** [ajalt/clikt#200]
Hey - I was wondering if having a `.bool()` option along the lines of 

```
import com.github.ajalt.clikt.parameters.options.RawOption
import com.github.ajalt.clikt.parameters.options.convert

internal fun valueToBool(it: String): Boolean {
    return it.toBoolean()
}

fun RawOption.bool() = convert { valueToBool(it) }
```

would make sense? I'm sure you thought about it and I realize that flags exist for that purposes. The reason I'm bringing it up is that I load all the values in my CliKt application through env variables (since it's 12 factor service), and flags don't work well in that case.

**Comment by ajalt** [comment]
> flags don't work well in that case.

How so? Flags support envvars. [Here's all the values](https://github.com/ajalt/clikt/blob/db11e17bb35972d4efd783565a1bb909ccf18cff/clikt/src/commonMain/kotlin/com/github/ajalt/clikt/parameters/options/FlagOption.kt#L108-L109) that you can use in an envvar for a flag option.

**Comment by lgrammel** [comment]
@ajalt ah, perfect - this is what I was looking for! Thanks!
