### ISSUE TITLE
Error should not reveal hidden option

### ISSUE THREAD

**Issue by wazhar** [ajalt/clikt#202]
Supplying non existing or misspelled option reveals hidden option in the form of suggestion. 

Error: no such option: "--dbug". Did you mean "--debug"?

Is there any configuration to suppress suggestions for hidden options?

**Comment by ajalt** [comment]
Is there a use case for making that configurable? I'm leaning toward the simplicity of never suggesting hidden options.

**Comment by wazhar** [comment]
Can't think of any use case. Just checked if there was a way to override the behaviour. 

Never suggesting hidden options is good.  

Thanks.
