### ISSUE TITLE
Add `help()` as a separate function for `option`/`argument`

### ISSUE THREAD

**Issue by serpro69** [ajalt/clikt#207]
Would be nice to have the possibility to provide help text through a separate function for options/arguments, as opposed to only having a `help` argument for `option()`/`argument()` functions.
This is particularly useful if you have a multi-line help-text:

Right now it's only possible to do one of the following:
```
private val test by option("-t", "--test", help = "This is a first help line\nAnd a second line\nAnd another one")
    .choice("unit", "integration", ignoreCase = true)
    .default("unit")
```
This gets a bit too long to read in an IDE. 
Or it could be done like this using kotlin's multi-line strings:
```
    private val test by option(
        "-t", "--test",
        help = """
            This is a first help line
            And a second line
            And another one
        """)
        .choice("unit", "integration", ignoreCase = true)
        .default("unit")
```
but it is also not that good if we have any extra functions afterwards such as `choice()` etc.

With the `help()` function we could put it at the end like so:
```
    private val test by option("-t", "--test")
        .choice("unit", "integration", ignoreCase = true)
        .default("unit")
        .help("""
            This is a first help line
            And a second line
            And another one
        """)
```
This, in my opinion, looks much better than any of the above.

I could try to make a PR for this if you think it would be a good thing to add.

**Comment by ajalt** [comment]
You can do almost exactly what you want today with the [`copy`](https://ajalt.github.io/clikt/api/clikt/com.github.ajalt.clikt.parameters.options/-option-with-values/copy/) function:

```kotlin
private val test by option("-t", "--test")
        .choice("unit", "integration", ignoreCase = true)
        .default("unit")
        .copy(help="""
            This is a first help line
            And a second line
            And another one
        """)
```

I'm generally not in favor of there being multiple ways to specify the same thing, since that often makes the code harder to understand.

**Comment by serpro69** [comment]
Right, I didn't know that was possible. Thanks!
