### ISSUE TITLE
Abstract UsageError texts (with the current as default)

### ISSUE THREAD

**Issue by LouizFC** [ajalt/clikt#227]
Greetings.

I think that adding the possibility to customize the texts from the `UsageError` derived exceptions would benefit the library.

In my case I have a project that involves non-english-speaking people who would use a CLI, so I need to translate the current error messages to their native language.

Currently I am just wrapping the exception handling in a `when` block and applying the translations with almost the same logic found in the `formatMessage` method.

I could be wrong, but I saw that most exception creation is done in the `Parser` object. Maybe allow it to be instantiated indirectly and give it a parameter like `ErrorMessageFactory` with a `handle(e: UsageError): String` method or something similar, I dont know.

Thanks in advance

**Comment by ajalt** [comment]
I'd definitely like to support localization. Could you provide examples of what and how you're translating now, so I can get a better idea of what's required?

**Comment by LouizFC** [comment]
I am using nothing fancy. The types of errors that users get are mostly MissingParameter and BadParameterValue, so I literally duck taped a solution some ugly string building logic. This is literally what I am using right now (quite ugly)
```kotlin
fun CliktCommand.echo(
    message: Any?,
    trailingNewline: Boolean = true,
    err: Boolean = false,
    lineSeparator: String = currentContext.console.lineSeparator
) {
    TermUi.echo(message, trailingNewline, err, currentContext.console, lineSeparator)
}

fun UsageError.inferParamName(): String = when {
    paramName != null -> paramName!!
    option != null -> option?.let { it.names.maxByOrNull { it.length } } ?: ""
    argument != null -> argument!!.name
    else -> ""
}

fun CliktCommand.localizedMain(argv: List<String>) {
    try {
        parse(argv)
    } catch (e: ProgramResult) {
        exitProcess(e.statusCode)
    } catch (e: PrintHelpMessage) {
        echo(e.command.getFormattedHelp())
        exitProcess(if (e.error) 1 else 0)
    } catch (e: PrintCompletionMessage) {
        val s = if (e.forceUnixLineEndings) "\n" else currentContext.console.lineSeparator
        echo(e.message, lineSeparator = s)
        exitProcess(0)
    } catch (e: PrintMessage) {
        echo(e.message)
        exitProcess(if (e.error) 1 else 0)
    } catch (e: UsageError) {
        val errorMessage = buildString {
            append("Erro: ")
            localizeExceptionMessage(e)
        }
        echo(errorMessage, err = true)
        exitProcess(e.statusCode)
    } catch (e: CliktError) {
        echo(e.message, err = true)
        exitProcess(1)
    } catch (e: Abort) {
        echo("Operação abortada!", err = true)
        exitProcess(if (e.error) 1 else 0)
    }
}

private fun StringBuilder.localizeExceptionMessage(e: UsageError) {
    when (e) {
        is MissingParameter -> {
            append("Pârametro não informado: ${e.inferParamName()}")
        }
        is BadParameterValue -> {
            append("Valor ínválido")
            if (e.inferParamName().isEmpty()) {
                append(" : ").append(e.text)
            } else {
                append(" para \"")
                append(e.inferParamName())
                append("\": ")
                append(e.text)
            }
        }
    }
}
```

I got my hands on Clikt quite recently, so I am not quite familiar with the codebase
