### ISSUE TITLE
Ignore unknown parameters

### ISSUE THREAD

**Issue by sksamuel** [ajalt/clikt#230]
Would it be possible to add an option to ignore unknown params?
Error: no such option: "--reporter".

**Comment by ajalt** [comment]
Sure, that's possible. Can you describe your use-case so I can get an idea of what the design should look like?

**Comment by sksamuel** [comment]
Yeah this is the use case:

I updated the kotest CLI main to accept a new param --foo.

Then I updated the kotest intellij plugin to send this param.

If someone is using the latest plugin and an older version of the CLI it will now throw an error saying unknown param, but the old cli should continue to work as the new params are extra functionality that the old one can work without.

**Comment by ajalt** [comment]
So Clikt already supports unknown options: https://ajalt.github.io/clikt/options/#unknown-options

Does that cover your use case?

**Comment by sksamuel** [comment]
Perf.

**Comment by ajalt** [comment]
Great!
