### ISSUE TITLE
Kotlin 1.3 compatibility

### ISSUE THREAD

**Issue by sksamuel** [ajalt/clikt#238]
I see you have moved to Kotlin 1.4. Did you consider using API level 1.3 so that clikt 3.0 can still be used in 1.3 projects like while allowing you to use the language features of 1.4.

I have cloned the project and set Api to 1.3:

```kotlin
tasks.withType<KotlinCompile>().all {
    kotlinOptions.jvmTarget = "1.8"
    kotlinOptions.apiVersion = "1.3"
}
```

The only function you are using which are not in 1.3 is maxByOrNull.

**Comment by ajalt** [comment]
Do many other libraries do that? It seems like projects still on Kotlin 1.3 could continue to use Clikt 2.8 until they update. I'd rather not be stuck on an old API version.

**Comment by sksamuel** [comment]
I can understand that. I can keep Kotest on 2.8.

**Comment by razvn** [comment]
Don't know if releated but if you had made the updated maybe you would have met issue #239 before me :)
