### ISSUE TITLE
How to make switch required?

### ISSUE THREAD

**Issue by asarkar** [ajalt/clikt#240]
`option().switch(...).required()` does not compile, neither does `option().required().switch(...)`.

**Comment by ajalt** [comment]
There isn't a `required()` extension for flag/switch options. You can write your own like this:

```kotlin
fun <T : Any> FlagOption<T?>.required(): FlagOption<T> {
    return copy(
            transformEnvvar = { transformEnvvar(it) ?: throw MissingOption(option) },
            transformAll = { transformAll(it) ?: throw MissingOption(option) },
            validator = validator,
    )
}
```

Since we already have a `default()` extension, I think it would make sense to add this as a built in extension.

**Comment by asarkar** [comment]
@ajalt Would the code you showed display the required indicator, like `*`?

**Comment by ajalt** [comment]
You can add `helpTags = mapOf(HelpFormatter.Tags.REQUIRED to "")` to the `copy` call to get the indicator in the help message.

**Comment by asarkar** [comment]
Thank you. I'm assuming this is going to be a standard feature in the library in the next version?

**Comment by ajalt** [comment]
That's the plan.
