### ISSUE TITLE
Validate default value for File type

### ISSUE THREAD

**Issue by rcaught** [ajalt/clikt#242]
Firstly, just want to say that I love this project @ajalt.

Say I have the following code:

```
private val myDir by option().file(
        mustExist = true,
        canBeFile = false,
        canBeDir = true,
        mustBeWritable = true,
        mustBeReadable = true
    ).default(File("/path/that/may/exist/but/does/not/for/this/example"))
```

If a user enters the command option `my-dir=/path/that/does/not/exist` you get the error:
```
Error: Invalid value for "--my-dir": Directory "/path/that/does/not/exist" does not exist.
```

If the default gets used and the path doesn't exist (omitting `--my-dir`), no validation is applied.  You would need to apply a `validate` or `check` call to the end of the property (re-implementing a lot of the `file` logic to do so).

It would be ideal if the argument to `default` could somehow have validations applied.  I understand why this is not currently possible due to the types and ordering (Option Transformation Order), but keen to hear if there is a solution I'm not thinking of or a change to Clickt that might make sense.

**Comment by rcaught** [comment]
> If the default gets used and the path doesn't exist (omitting --my-dir), no validation is applied. You would need to apply a validate or check call to the end of the property (re-implementing a lot of the file logic to do so).

I now see that the `validate` or `check` lambda doesn't run if the value is not set, so what I'm suggesting above doesn't even work.

**Comment by ajalt** [comment]
I think that validating defaults would result in a poor user experience. Reporting an error on an option that the user didn't enter, for a value that the user didn't enter, would be confusing. In your case, I would probably omit `default(...)` and check your default value manually in `run`. That way you could provide a more useful error message like "No value given for --my-dir, and no default available. Please specify --my-dir manually.".

**Comment by rcaught** [comment]
Thanks for the feedback!  Just a few points for posterity that I've worked out along the way:
- not using `default(...)` of course results in:
  - a nullable property and problems around that (having to make the property mutable to be able to assign a default on null, mutable nature conflicting with the `file` read-only receivers, etc)
  - losing the automatic help defaults

So I've decided to stay with using the `default(...)` setting and validate manually in `run` like you suggested, which seems to work well.
