### ISSUE TITLE
Help page isn’t generated when using gradle build

### ISSUE THREAD

**Issue by sangeetds** [ajalt/clikt#245]
I'm having trouble showing the help page when using gradle build and running a script to show the result. 

What I am doing to get this error: I've made a script similar to `runsample` script provided in the repository. 
Detailed error: I've made a script named `project` for a file `main.kt` which has two options, `repo` `count` . It runs fine with `./project repo xyz count 2` and also shows error with `./project abc` but shows nothing when I run `./project --help` or `./project help` and actually runs without any arguments. I've provided help options for all the variables. 

Is there anything that I'm missing or anything else that needs to be done to show the help screen?

**Comment by ajalt** [comment]
I'd need some more information to help you out. Can you share the code for your command?

**Comment by sangeetds** [comment]
[Here's ](https://github.com/sangeetds/GithubApiProject) the link to Github repository if you want to take a closer look. 

But let me just post the code in `main.kt`

```
class Hello : CliktCommand() {
    private val rateLimit = 60
    private val organisationName: String by option(help = "Name of the organisation").prompt("Enter the name of Organisation")
    private val repositoriesCount: Int by option(help = "Number of repositories to be selected").int()
        .prompt("Enter number of repositories to be selected")
    private val committees: Int by option(help = "Number of top committees to be displayed").int()
        .prompt("Enter the number of committees to be displayed")
    private val login by option(help = "User login id").default("")
    private val token by option(help = "Authorization token").default("")

    override fun run() {
        val newUserArguments = UserArguments(
            organisation = organisationName.trim(),
            repoCount = repositoriesCount,
            topCommittees = committees,
            token = if (token.isBlank()) "" else token.trim(),
            login = if (login.isBlank()) "" else login.trim()
        )
        val githubAPI = Github(newUserArguments)
        val repoList = githubAPI.getRepos()
        val committeesList = HashMap<String, List<User>>()
        repoList?.forEach { repo ->
            echo("Name: ${repo.name} \t Fork Count: ${repo.forks_count}")
        }
        repoList?.forEach { repo ->
            committeesList[repo.name] = githubAPI.getTopUsers(repo)!!
        }

        repoList?.forEach { repo ->
            echo("${repo.name}:")
            committeesList[repo.name]?.forEach { user ->
                echo("Name: ${user.author.login} \t Commits: ${user.total}")
            }
        }
    }
}

fun main(args: Array<String>) = Hello().main(args)
```

And here's the script which I am running `project`

```
#!/usr/bin/env bash

task=$1
shift 1

if ./gradlew --quiet installDist; then
  ./build/install/GithubAPI/bin/GithubAPI "$@"
else
  echo "Gradle task failed. Please check your files for any errors and run 'gradle build' followed by './gradlew installDist' and try again" >&2
fi
```

Thanks a lot for the help!

**Comment by ajalt** [comment]
This is not a problem with Clikt. The `shift 1` in your script is removing the first command line argument before passing it to your program. Get rid of that line and it will work.
