### ISSUE TITLE
How to run using ./

### ISSUE THREAD

**Issue by nik-suri** [ajalt/clikt#246]
I am new to both Kotlin/Java and I have quite a simple question. In your README and documentation you provide an example of a simple program and then show how you can run it using `./hello`. 

How did you go from the writing program to being able to run it using `./hello`?

There are lots of build processes for kotlin and it seems that there is a step missing here.

**Comment by ajalt** [comment]
I touch on this in the [docs](https://ajalt.github.io/clikt/quickstart/#developing-command-line-applications-with-gradle). You can either use Kotlin/Native and compile to a single binary, or on JVM you can use the [gradle application plugin](https://docs.gradle.org/current/userguide/application_plugin.html), which will generate a script that you can run as a binary. This repo has a number of samples that you can look at to see how to set that up.

**Comment by nik-suri** [comment]
Great, thank you! The samples are helpful.

I use maven for builds, and the [appassembler-maven-plugin](https://www.mojohaus.org/appassembler/appassembler-maven-plugin/) seems to work as the equivalent of the gradle application plugin.
