### ISSUE TITLE
How to configure a prompt with a default that comes from another option?

### ISSUE THREAD

**Issue by joffrey-bion** [ajalt/clikt#250]
I'm trying to setup a command that takes multiple sets of credentials (for different things) as options.
All of them can be prompted for, but I would like the first username to be shown and used as default value for other username prompts.

```kotlin
class MyCommand : CliktCommand() {

    val githubUser by option("--github-user").prompt("Your GitHub username")

    val bintrayUser by option("--bintray-user").prompt("Your Bintray username", default = githubUser)
}
```

This obviously doesn't work because `githubUser` doesn't have a value at this time.
Is there a way to provide a default with a lambda?

**Comment by JakeWharton** [comment]
https://ajalt.github.io/clikt/api/clikt/com.github.ajalt.clikt.parameters.options/default-lazy/

**Comment by joffrey-bion** [comment]
But that's not quite the same, right? How can I use it for a prompt default?

The behaviour I'm looking for is that if the option is missing on the command line, the user is prompted with an indication of a default value, so that they know what will be used if they just press enter without typing anything

**Comment by JakeWharton** [comment]
Ah sorry I totally missed the prompt part and focused on the lazy part. Never used prompt.

**Comment by ajalt** [comment]
Jake is right, you can use `defaultLazy` here. `option().prompt()` just calls `TermUi.prompt` under the hood, so [you can do the same](https://ajalt.github.io/clikt/utilities/#input-prompts):

```kotlin
class MyCommand : CliktCommand() {
    val githubUser by option("--github-user").prompt("Your GitHub username")
    val bintrayUser by option("--bintray-user").defaultLazy {
        TermUi.prompt("Your Bintray username", default = githubUser) ?: githubUser   
    }
}
```

There's a caveat that default values (including `prompt()`) are evaluated in the order they're defined, so make sure you're only referencing properties defined earlier in the command. If you don't want to rely on the definition order, you can call `TermUi.prompt` manually from `run`.

**Comment by joffrey-bion** [comment]
That makes sense. I was somehow too focused on the `prompt()` shorthand. Thanks!
