### ISSUE TITLE
How to do conditional validation?

### ISSUE THREAD

**Issue by asarkar** [ajalt/clikt#253]
Given
```
private class Execute : CliktCommand(name = "exec") {
    private val address by argument()
    private val method by argument()
    private val cmdArgs: List<String> by argument().multiple()
    private val fileArgs by option("-f").file(mustExist = true, canBeDir = false, mustBeReadable = true)
        .convert { it.readLines() }

    override fun run() {
        require(cmdArgs.isNotEmpty() || fileArgs?.isNotEmpty() == true) {
            "One of arguments or file must be provided"
        }
        // do stuff
    }
}
```

One of `cmdArgs` or `fileArgs` must be present. Is there some sort of post method that can throw a nice `MissingOption` error instead of `IllegalArgumentException` thrown by `require`?

**Comment by ajalt** [comment]
There's no way to group an argument and an option together, but you're free to throw one of the [built-in errors](https://ajalt.github.io/clikt/exceptions/#which-exceptions-exist) like `UsageError` yourself.

**Comment by asarkar** [comment]
Hi @ajalt 
`UsageError` expects a `paramName:String?` or `Argument` or `Option`, and seems more suitable for a single field validation. Here I've two fields, and the 2nd and 3rd `UsageError` overloads definitely don't work. Do you recommend using a `null` `paramName` with the text as shown above?

**Comment by ajalt** [comment]
Yes. Just supply `text` and let the rest of the arguemtns be `null`.
