### ISSUE TITLE
Provide a post construct method

### ISSUE THREAD

**Issue by asarkar** [ajalt/clikt#255]
It will be useful to have a post construct method where validations involving more than one option/argument can be done, or their values can be modified. This can be done in `run`, of course, but it feels like the wrong method for this purpose. Most dependency injection frameworks have such a hook, and so does JUnit (`before*` methods)

**Comment by ajalt** [comment]
You can already reference other parameters in `check` and `validate`, as shown in the [documentation](https://github.com/valich/intellij-markdown/pull/59) and [examples](https://github.com/ajalt/clikt/tree/master/samples/validation)

**Comment by asarkar** [comment]
What does https://github.com/valich/intellij-markdown/pull/59 have to do with validation? Is it wrongly provided?

**Comment by asarkar** [comment]
Also, not all validations can be done in `check` or `validate`.
```
private val protoPath by option("--proto-path", "-pp", help = "Directory in which to search for imports")
    .file(mustExist = true, canBeDir = true)
    .multiple()
private val protoFile by option("--proto-file", "-pf", help = "File path relative to the proto directory")
```

Validation:
```
if (protoPath.isNotEmpty()) {
    if (protoFile == null) {
        throw UsageError("Proto file must be specified if proto path is")
    } else if (protoPath.none { it.resolve(protoFile!!).exists() }) {
        throw UsageError("Proto path must be a proper prefix of the proto file absolute path")
    }
}
```

Is `check` or validate` called when the option is null? If not, then the above validations can't be done.

**Comment by ajalt** [comment]
Sorry on the documentation link, that was a copy-paste error. Here's the correct link: https://ajalt.github.io/clikt/parameters/#parameter-validation

`check` and `validate` aren't called if the option is null. If you need more complicated validation, you should do it in `run`.

**Comment by asarkar** [comment]
> If you need more complicated validation, you should do it in run.

That’s exactly the problem this ticket stated, that `run` is a kitchen sink, but you closed it suggesting to use `check` and `validate`.

**Comment by ajalt** [comment]
If you need a version of validate that runs when the option is null, you can easily make one:

```kotlin
fun <AllT, EachT, ValueT> OptionWithValues<AllT, EachT, ValueT>.validateWhenNull(
    validator: OptionValidator<AllT>
): OptionDelegate<AllT?> {
    return copy(transformValue, transformEach, transformAll, validator)
}
```

`run` is like `main`. If you find it getting too long, you can decompose it into other functions. I don't want to start adding a android-style lifecycle methods. They're unnecessary and make the library more complicated. You can always make your own command base class that implements whatever callbacks you want.

**Comment by asarkar** [comment]
> You can always make your own command base class

I can. I can also parse command-line arguments myself without the use of this library at all. The whole point is to abstract boilerplate and repetitive tasks away, and if we look at the usage, we will surely find validation is a very common boilerplate.

Anyway, I’ve made my point, whether to do anything about it or not is up to you. Thanks.
