### ISSUE TITLE
[question] "Multiple Values from Environment Variables" documentation outdated / how to use associate with environment variables

### ISSUE THREAD

**Issue by tristanlins** [ajalt/clikt#257]
The documentation said:

> On Windows, it will split on semicolons (;). On other systems, it will split on colons (:). You can also specify a split pattern by passing it to the envvarSplit parameter of option.

After reading #177 and #185 I asume `envvarSplit` was removed completely?
I tried to create a "logger-level" multi-value option, that supports `envvar`.

*Version 1: works but not with `envvar`*

```kotlin
private val loggers by option(
    "--logger",
    envvar = "LOGGER"
).associate()
```

*Version 2: runs into "List has more than one element." IllegalArgumentException*

```kotlin
private val loggers by option(
    "--logger",
    envvar = "LOGGER"
).copy(valueSplit = Regex(Regex.escape(File.pathSeparator))).associate()
```

*Version 3: works fine, but looks clumsy*

```kotlin
private val loggers by option(
    "--logger",
    envvar = "LOGGER"
).convert {
    it.split(File.pathSeparator).map {
        it.substringBefore("=") to it.substringAfter("=")
    }
}.transformAll {
    it.flatten().toMap()
}
```

Whats the correct way, to use `associate()` with `envvar`?
Or is this not supported out of the box?

I would also do a PR, but first I would have to know what the correct solution could look like ;-)

**Comment by ajalt** [comment]
The docs are definitely out of date, I'll get those fixed.

Like most of Clikt's extensions, `associate` is [a one-liner composed of a few other transforms](https://github.com/ajalt/clikt/blob/6c97021fa22d6447827fda5d9d3d77239adb59c9/clikt/src/commonMain/kotlin/com/github/ajalt/clikt/parameters/options/TransformAll.kt#L170):

```kotlin
fun Option.associate(delimiter: String = "=")
    = splitPair(delimiter).multiple().toMap()
```

It looks like you want to add an extra `split` step, which you can do like this:

```kotlin
option(/*...*/)
    .splitPair().split(File.pathSeparator).transformAll { it.flatten().toMap() }
```

**Comment by tristanlins** [comment]
Okay, youre right, I missed the "This must be called after converting the value type, and before other transforms." in the `split(..)` doc. Thanks :wave:
