### ISSUE TITLE
OptionGroup has no method getValue() and thus it cannot serve as a delegate

### ISSUE THREAD

**Issue by Virtlink** [ajalt/clikt#259]
I'm trying to group some options, but the code example [in the documentation](https://ajalt.github.io/clikt/documenting/#grouping-options-in-help) does not work:

```
import com.github.ajalt.clikt.core.NoOpCliktCommand
import com.github.ajalt.clikt.parameters.groups.OptionGroup
import com.github.ajalt.clikt.parameters.options.option
import com.github.ajalt.clikt.parameters.types.int

class UserOptions : OptionGroup(
    name = "User Options",
    help = "Options controlling the user"
) {
    val name by option(help = "user name")
    val age by option(help = "user age").int()
}

class Tool : NoOpCliktCommand() {
    val userOptions by UserOptions()
}
```

This produces the error (Clikt 3.1.0, Kotlin 1.4.21, Java 11.0.9.1, Intellij 2020.3 Ultimate):

> Type 'UserOptions' has no method 'getValue(Tool, KProperty<*>)' and thus it cannot serve as a delegate

The type `OptionGroup` implements the interfaces `ParameterGroup` and `ParameterHolder`, but neither has a `getValue` method.

**Comment by ajalt** [comment]
The property function for plain groups is provided as an extension. You need to add `import com.github.ajalt.clikt.parameters.groups.provideDelegate`. IntelliJ should offer to import that function automatically. 

I would be good to add that info to the docs.
