### ISSUE TITLE
Using NullableOption.prompt prevents converting option to arbitrary type

### ISSUE THREAD

**Issue by carltonwhitehead** [ajalt/clikt#260]
`NullableOption.convert()` is not available on an option chain after `NullableOption.prompt()` because it returns an `OptionWithValues`, which doesn't seem to have any methods allowing type conversion. Please correct me if I'm wrong!

`TermUi.prompt()`, by comparison, has a `(String) -> T` allowing conversion to an arbitrary type.

It would be useful to allow validating the input format beforehand and converting it to an arbitrary type afterwards.

Example:
```kotlin
private val date: LocalDate by option()
        .prompt(validate = { input -> 
            try { 
                LocalDate.parse(input) 
            } catch (dtpe: DateTimeParseException) {
                throw UsageError("Invalid date format: $input")
            }
        })
        .convert { toLocalDate(it) }
```

**Comment by ajalt** [comment]
`prompt` is just like `multiple` and `default`: you have to [apply it after the conversion](https://ajalt.github.io/clikt/options/#option-transformation-order).

```kotlin
private val date by option()
    .convert { LocalDate.parse(it) }
    .prompt()
```

**Comment by carltonwhitehead** [comment]
Aha, thanks for the tip. I'll give that a try.
