### ISSUE TITLE
Idea: Allow root options to be passed to subcommands

### ISSUE THREAD

**Issue by sschuberth** [ajalt/clikt#268]
For user convenience, it might make sense to allow passing global options as if they were sub-command options. For example, instead of requiring the user to write

    command --root-option subcommand --sub-option

*clikt* could allow to write

    command subcommand --root-option --sub-option

This would work unless there is an option name clash between the global command and the sub-command, in which case the sub-command-specific option should take precedence.

AFAIK there's currently no elegant way to achieve this in *clikt*, so maybe it makes sense to implement this as a core feature toggle on the context, like `subcommandsInheritGlobalOptions` or `allowGlobalOptionsForSubcommands`.

**Comment by ajalt** [comment]
I agree that there are definitely use-cases for sharing options between parents and subcommands. There are some design decisions we'd have to make, such as:

- Should this be opt-in or opt-out per-subcommand? Is there a situation where you wouldn't want the global options available to all subcommands?
- Do subcommands need access to the global option values? If so, should it be implicit (e.g. a map in the `context`), or explicit (with a property delegate)
- How should an option be marked as global?
- What happens if a subcommand declares a global option?

I'd like to collect use-cases and some examples of real-world CLI apps that have global options + subcommands to help answer these questions, so if anyone has any, I'd love it if you could share them here.

**Comment by sschuberth** [comment]
> Should this be opt-in or opt-out per-subcommand? Is there a situation where you wouldn't want the global options available to all subcommands?

I believe it should be a global opt-in. Per-subcommand sounds like a really confusing end-user experience.

> Do subcommands need access to the global option values? If so, should it be implicit (e.g. a map in the `context`), or explicit (with a property delegate)

I'd say yes, but about the *how* (implicit or explicit) I don't have a strong preference. What we [currently do](https://github.com/oss-review-toolkit/ort/blob/4be3ab1fbac441ae07fbc8f3f8399582975c0020/cli/src/main/kotlin/OrtMain.kt#L149-L152) is to pass global options as an object in the context, which is similar to your map suggestion.

> How should an option be marked as global?

Does it need to be? Why would a subcommand care whether an option came in via the "global" or "local" scope? Anyway, your map suggestion from above would implicitly answer that question, as global options would come via the context instead of property delegates.

> What happens if a subcommand declares a global option?

Is that even possible right now? I mean, what makes a command a subcommand is the way you link the commands, and each command just has its options. So, from that perspective any command (subcommand or not) can just have options, but a subcommand cannot have global options, because if the options in the commad were global, it would not be a subcommand :wink:

**Comment by sschuberth** [comment]
> I agree that there are definitely use-cases for sharing options between parents and subcommands.

BTW, strictly speaking this feature request is at its core not about being able to share options between parents and subcommands; that's already possible via the context-based approach I outlined above. This request rather is about syntactic sugar to make the global option somewhat non-positional by allowing it to be specified at the subcommand level.

**Comment by ajalt** [comment]
I think we might be using terminology differently. For this PR, I'm going to use the term "global option" to refer to an option that can be called on a different command from where it's declared. I'll use the term "root option" to refer to an option declared on the root command.

> > How should an option be marked as global?
> 
> Does it need to be?

There has to be some way to tell Clikt that an option should be treated as global. Either through a whle-command flag like you mentioned in the initial issue, or per-option, or some other way. Should it be possible to have only some options on a command be global?

> > What happens if a subcommand declares a global option?
> 
> Is that even possible right now?

Well, there are no global options right now. What should happen if a command with the global option flag set (or whatever mechanism we decide on) is registered as a subcommand? We could throw an error, or treat that command's global options as regular options, or only make that command's options "global" to that its own subcommands etc.

**Comment by sschuberth** [comment]
> I think we might be using terminology differently.

Yes, indeed. Thanks for the clarification. I've edited my top post accordingly and renamed `--global-option` to `--root-option`.

> Should it be possible to have only some options on a command be global?

From my side, I'd be fine with all or nothing. Assuming that root options would be passed to subcommands via the context, a subcommand could simply not read any global options it's not interested in.

> What should happen if a command with the global option flag set (or whatever mechanism we decide on) is registered as a subcommand?

I'd say in that case the flag should simply be ignored.

But your question raised another question on my side: That flag to introduce could be one on the root command, telling the root command that it should "push" its options to all its subcommands. Or the flag could be on the / each subcommand, telling the subcommand to "pull" all root command options. With the latter solution you could decide on a subcommand level whether you want to have access to root command options, making them global options. However, I currently prefer the first approach, as it seems more natural for the root command to give the / all subcommands access to the root options.

However, I'd again like to emphasize that giving a subcommand access to root command options, and thus effectively creating global options, is a different topic compared to making `command subcommand --root-option --sub-option` valid syntax.

**Comment by AvlWx2014** [comment]
If I'm understanding the discussion correctly, this is something that I asked about in the issues for [kotlinx.cli](https://github.com/Kotlin/kotlinx-cli/issues/54) and that they support [through inheritance](https://github.com/Kotlin/kotlinx-cli/blob/0215281dcb269a10267500399d3bb41cbf547d63/core/commonTest/src/SubcommandsTests.kt#L64). 

Based on the example I gave in the issue I linked above:
a. Am I in the right neighborhood about the use case here?
b. Does Clikt do this right now?

**Comment by sschuberth** [comment]
*clikt* does right now support options on the "root command". Your subcommands can manually interpret these as "shared options" by accessing the root command's options via the context. So technically, this is possible. However, this issue in mostly about the syntax that has to be used for root command options, or better, their ordering. At you linked example, you'd have to write

    app -o outdir single --file infile

because `-o` needs to be an option on the *app*  root command, while you probably would like to write

    app single --file infile -o outdir

which is not possible yet with *clikt*.

**Comment by AvlWx2014** [comment]
Thanks for your thorough response! You are correct, I am trying to avoid duplication by defining shred options across subcommands. It would be ideal in the example I linked to write

`./AppName single infile -o outdir`

However, I recognize that with Clikt, as you mentioned, it will look more like

`./AppName -o outdir single infile`

which works just as well.

After exploring a bit with subcommands through inheritance it looks like the root command, which also has a name, would have to be included on the command-line as well. Instead it looks like this:

`./AppName root-command -o outdir single infile`

Which is a bit awkward. However, I noticed the Clikt Quickstart docs suggest that I could do the following:
```kotlin
class Cli : CliktCommand() {
    protected val o by option("-o", "--output", help="Specify the output directory.").file()
    override fun run() = Unit
}

class Single : CliktCommand(help="Process a single file") {
    override fun run() {
        // process single file
    }
}

class Multiple : CliktCommand(help="Process many files") {
    override fun run() {
        // process multiple files
    }
}

fun main(args: Array<String>) {
    Cli().subcommands(Single(), Multiple()).main(args)
}
```

And run it with:
```
./cli -o outdir single infile
```

Which would be great. I just have to get it to work. I'm using the `application` plugin for Gradle, and keep having to use `./AppName` to run it, since that's the name the output scripts end up with.

**Comment by sschuberth** [comment]
Feel free to look at our project for an example:

https://github.com/oss-review-toolkit/ort/blob/72db6534a875d82b425e4211bde1eeaedb775e8f/cli/build.gradle.kts#L32-L40

https://github.com/oss-review-toolkit/ort/blob/72db6534a875d82b425e4211bde1eeaedb775e8f/cli/src/main/kotlin/OrtMain.kt#L196-L203

**Comment by AvlWx2014** [comment]
Will do, thank you. Sorry for getting a bit off topic there!

**Comment by ajalt** [comment]
So revisiting this, I wonder if it wouldn't be better to implement this functionality with functionality with an OptionGroup that's included in each subcommand.

```kotlin
class CommonOptions : OptionGroup("Common Options:") {
    val o by option("-o", "--output", help = "Specify the output directory.")
}

class Cli : NoOpCliktCommand()

class Single : CliktCommand(help = "Process a single file") {
    private val commonOptions by CommonOptions()
}

class Multiple : CliktCommand(help = "Process many files") {
    private val commonOptions by CommonOptions()
}
```

- No need to build a separate config object
- All the common options are available strongly typed; subcommands don't need to know about their parent
- Common options are listed separately in the help output for each subcommand, so you don't have to call `--help` twice to see all the available options
- It's explicit which commands use the common options, so there's no confusing behavior around where the options are legal on the command line.

If you do need an explicit config object, you could define it (possibly as an extension) on the option group. I converted one of my CLI tools that previously used root options to this pattern, and it works well.

Inheritance is also available as discussed above, although I think the option group is simpler.

```kotlin
data class Config(val outputDir: String?)
abstract class MyCommand(help: String) : CliktCommand(help = help) {
    // You can still use an option group here to separate them in help output if desired
    private val o by option("-o", "--output", help = "Specify the output directory.")
    protected fun config() = Config(o)
}

class Single : MyCommand(help = "Process a single file") {
    override fun run() {
        val config = config()
    }
}
```

@sschuberth would either of these approaches solve your problem?

**Comment by sschuberth** [comment]
> I converted one of my CLI tools that previously used root options to this pattern, and it works well.

Can you share the diff of that change / the PR for reference? Or is that project not public on GitHub?

> @sschuberth would either of these approaches solve your problem?

I might be missing something, but I currently don't see how this approach supports *both*

    command --root-option subcommand --sub-option

and

    command subcommand --root-option --sub-option

syntaxes at the same time.

**Comment by ajalt** [comment]
> Can you share the diff

Unfortunately, it is closed source

>  I currently don't see how this approach supports both

It doesn't, but that seems like it might be a good thing. I image users would get confused when some options can be given before or after the subcommand, while others cannot. With the option group approach, a subcommand's options are all specified in the same place: after the subcommand.

**Comment by ajalt** [comment]
Ok, I think I'll hold off on implementing this for now. Thanks for taking the time to discuss!
