### ISSUE TITLE
Dependencies between commands

### ISSUE THREAD

**Issue by fabriziofortino** [ajalt/clikt#269]
Is there a way to create dependencies for commands?

For example, I could have the commands `compile` and `test`. To latter depends on the former.

**Comment by ajalt** [comment]
You can [chain subcommands][1] together, and pass information between them with the [command context][2]. If that doesn't solve your problem, I can give you better advice if you share more details on what your trying to achieve.

[1]: https://ajalt.github.io/clikt/commands/#chaining-and-repeating-subcommands
[2]: https://ajalt.github.io/clikt/commands/#nested-handling-and-contexts

**Comment by fabriziofortino** [comment]
AFAIU chaining would require explicit declarations of the subcommands. What I am looking for is something that would automatically invoke a subcommand the invoked command depends on. Going back to my example, when I run:

```
./myCli test
```

I want to force the execution of `compile` before `test`.

I tried to achieve the same in code, passing the instance of the `CompileCommand` to the `TestCommand` and invoking `compile.run()` as the first thing in `test.run()` but the problem is that all the options in the CompileCommand are not initialized.

I think it would be good to have a way to declare dependencies. `ant` has something very similar to this that allows declaring dependencies between tasks https://ant.apache.org/manual/targets.html

**Comment by ajalt** [comment]
Hm, that seems out of scope for this library. Clikt is a UI layer. Your business logic for constructing and running execution graphs should probably be defined separately from your Clikt commands. 

You could use your context object to store information on what commands were called, then run your graph with whatever dependencies you define. e.g.:

```kotlin
class MyCli: CliktCommand() {
    val graph by findOrSetObject { MyGraph() }
    private val option by option()

    override fun run() {
        graph.option = option
    }
}

class Test: CliktCommand() {
    private val graph by requireObject<MyGraph>()
    override fun run() {
        graph.tasks += "test"
    }
}

fun main(args: Array<String>) {
    val cli = MyCli()
    cli.main(args)
    executeTasks(cli.graph)
}
```

**Comment by fabriziofortino** [comment]
I see your point. I can construct my graph but at the same time, I would like to define the steps as Clikt commands. This is pretty much what I am trying to do. The problem is that the options of the subcommand that are not explicitly invoked are `null`. I would expect them to have the default value. Is there any way to achieve that?

**Comment by ajalt** [comment]
We can't finalize parameters of commands that weren't invoked, since that would cause errors to be reported for `required` options and the like. I would suggest having default values on your graph object and setting them in the `run` method of commands that are called.

The fact that the option properties of uninvoked commands return null is a bug: they should throw an error when you try to read from them. Thanks for reporting that, I'll get it fixed.
