### ISSUE TITLE
`print` and `println` instead of `echo` on CliktCommand

### ISSUE THREAD

**Issue by bradynpoulsen** [ajalt/clikt#27]
After having built some CLI's lately using the library, I'm wondering if it would be beneficial to just expose `print` and `println` methods to mimic printing to the screen directly with `System.out` or `System.err` but in scope with the console's Context instead

Example proposed methods:
```kotlin
protected fun println() = echo("")
protected fun println(message: String) = echo(message)
protected fun println(message: Any?) = echo(message?.toString())

protected fun print(message: String) = echo(message, trailingNewLine = false)
protected fun print(message: Any?) = echo(message?.toString(), trailingNewLine = false)
```

We could also consider just exposing a `out` and `err` PrintStream on the CliktCommand type 

```kotlin
class CliktCommand(...) {
    protected val out: PrintStream by lazyPrintStream { echo(it, trailingNewLine = false) }
    protected val err: PrintStream by lazyPrintStream { echo(it, trailingNewLine = false, err = true) }

    ...

    private inline fun lazyPrintStream(output: (String) -> Unit): Lazy<PrintStream> = lazy(LazyThreadSafetyMode.NONE) {
        PrintStream(object : OutputStream() {
            override fun write(b: Int) {
                output(b.toByte().toChar().toString())
            }
        })
    }
}
```

at which point we could just alias the recommended methods above to go to `out` by default

```kotlin
protected fun println() = out.println()
protected fun println(message: String) = out.println(message)
protected fun println(message: Any?) = out.println(message?.toString())

protected fun print(message: String) = out.print(message)
protected fun print(message: Any?) = out.print(message?.toString())
```

**Comment by ajalt** [comment]
The reason is chose the name `echo` over `print` is to make it obvious when reading the code which method you're using. There's the additional problem that, if you define member `println` methods, you can no longer use the system `println` without an explicit package name (`kotlin.io.println("")`). 

Maybe that's a good thing, since it would help prevent people from accidentally using system `println` instead of `echo`, but I'm not sure. Is typing `echo` instead of `println` cumbersome?

**Comment by bradynpoulsen** [comment]
I'm thinking of it similar to how the `require` helper works inside of validation blocks. `echo` isn't very discoverable unless you a) go through most of the `CliktCommand` source code (this is how I discovered it) or b) you pick up on it while reading the user guide. The usability is more awkward because you either have to utilize named parameters to toggle behavior flags on the method or use obscure stand-alone booleans.

The part thats sometimes cumbersome is comparing what you have to do to sanely (for you and other developers reading your code) utilize certain aspects of `echo`.
```kotlin
println("foo") // or out.println("foo")
echo("foo")

print("foo") // or out.print("foo")
echo("foo", trailingNewline = false)

err.println("foo")
echo("foo", err = true)

err.print("foo")
echo("foo", trailingNewline = false, err = true)
```

An advantage of just using `print` and `println` is using APIs that you already know and love, no discoverability is need. While it does intercept natural `kotlin.io.println("")` method calls, the majority of users _probably_ just want it do end up on standard out, which is the default behavior of `echo`. But if they decide their command's output should end up somewhere else, if they weren't strictly using `echo`, they now have to go refactor their code to do so as compared to their usage of `print` and `println` passing through the context too

**Comment by ajalt** [comment]
I would normally avoid overriding built in functions, since that leads to unexpected behavior. But in this case, given that `echo`'s behavior is identical to `println`'s, but it fixes line ending bugs, I think that I agree with you that this is worth implementing. 

I can work on it this weekend.

**Comment by bradynpoulsen** [comment]
Sounds good. I was going to implement it as well when I had some time, but wanted to have the discussion first. I'll post here if I start working on it

**Comment by jcornaz** [comment]
I think it is not a so good idea. Here is why:

First "echo" is easy to discover. Either by auto completion or in the doc. For any library or tool, the best way to discover feature will always be to read the documentation. And in this case, we are talking about a feature which appear in the very first paragraph of the "get started" section. So it is hard to find only if we don't read the "Hello world" of the technology we are about to use.

Then `echo` definitely doesn't do the same as `println`. It does more.

And, println is the most known function in Kotlin. It is the first one you learn (again reading the "Hello world"), and the one you see the most often when reading articles, examples, and documentation. Every developer knows it and have a strong assumption about how it will behave. No one will think about reading the documentation about println. So it will have astonishing, unexpected behavior.
