### ISSUE TITLE
Idea: Built-in --help-all for root command

### ISSUE THREAD

**Issue by sschuberth** [ajalt/clikt#271]
If a (root) command has subcommands, passing `--help` to the root command gives help on the overview of subcommands, and passing `--help` to a subcommand gives detailed help on that command only. But there are cases (e.g. when search for options common across all subcommands) where it would be good to get the detailed help on all subcommands at once. Would it make sense to offer a built-in `--help-all` option on the root command for this?

**Comment by ajalt** [comment]
I can see the usefulness, although I'm concerned it would result in too much output for programs with many subcommands. Would it display help recursively in the case of nested subcommands? I'm not sure how to display that in a way that's helpful. Do you know of any existing CLI apps that do something similar?

**Comment by sschuberth** [comment]
> Would it display help recursively in the case of nested subcommands?

Yes.

> I'm not sure how to display that in a way that's helpful.

Not to a human to read all of it. I agree such an output would mostly be useful to get piped through `grep` to search for something.

> Do you know of any existing CLI apps that do something similar?

Nope.

Thinking about it again, it's probably too much of a nice use-case, so I'll probably just implement that manually on the client side. Feel free to close.

**Comment by sschuberth** [comment]
I indeed decided to implement this on the client side, see https://github.com/oss-review-toolkit/ort/pull/3702.
