### ISSUE TITLE
Interpreting options - force whitespace after option name?

### ISSUE THREAD

**Issue by kgruhler** [ajalt/clikt#274]
Hi, 

I'm using the following mutuallyExclusiveOptions and another option called "--unstable"

```kotlin
private val fileConfig: FileOption? by mutuallyExclusiveOptions(
    option("-f", "--file").convert { FileOption(it, FILE) },
    option("-u", "--uri").convert { FileOption(it, URI) }
  ).single().required()
```

When a user enters a wrong/unsupported command line option "-unstable" (instead of --unstable with two dashes) the CLI replied with a missleading error message for the user, because it interprets "-unstable" as option "-u":

```bash
> command -f /path/to/file -unstable
An error occured:
 MutuallyExclusiveGroupException: option --file cannot be used with --uri

```

I have two questions now: 

1. Is it possible to avoid that clikt interprets "-unstable"  as an option? Maybe by checking for a whitespace 
after each option like "-u ".
2. Can I somehow transform or validate the given option keys by myself to create a custom "whitepace" check, before CLIKT is throws the MutuallyExclusiveGroupException ?

**Comment by ajalt** [comment]
Although I can understand the confusion caused by that very specific typo, I'm -1 on this request. 

Clikt follows standard POSIX conventions for parsing short options. Users who have used other CLI tools will expect them to behave the same way. I think that changing the parsing behavior here will cause more confusion than it solves.

**Comment by ajalt** [comment]
I've added better error messages around missing a dash in some cases in #286. I'll continue to try to improve error messages in the future.
