### ISSUE TITLE
Talk about CliKt (Kotlin + GraalVM)

### ISSUE THREAD

**Issue by trietsch** [ajalt/clikt#283]
Hey @ajalt! Thanks for this awesome library. Yesterday, I gave a presentation about using Kotlin, CliKt and GraalVM to create a platform native binary. If you'd like, you could add the presentation, which was live streamed to YouTube, to the documentation / readme.

The link to the presentation = https://www.youtube.com/watch?v=MWrAt1L6xpM
And the link to the repository with example code = https://github.com/trietsch/spotify-cli

Feel free to use them :)

Regards,
Robin

**Comment by buremba** [comment]
I just want to say thank you to @ajalt, the library is great!
