### ISSUE TITLE
Provide Automatic-Module-Name for jvm target

### ISSUE THREAD

**Issue by Lafreakshow** [ajalt/clikt#289]
First of all, I had a quick look to see if this was mentioned anywhere. My apologies in case I missed something.

Cikt works perfectly well as an automatic module. Gradle, however, insists on putting it on the classpath because it doesn't have a module descriptor or automatic module name. This makes it inconvenient to use in modular JVM projects and while inconvenience is all it causes me, it could easily lead to other hard to identify issues in more complex projects.

I reckon a full `module-info.java` is overkill here but an `Automatic-Module-Name = clikt.jvm` in the jars manifest would make the experience a lot nicer. This way, the modules name stays consistent even if the jar changes names some time in the future and it'll also (likely) shut up Gradle. It's also good practice anyway.

My workaround right now is essentially that, transforming the artifact to add an automatic module name. (For reference: [I simply went by this](https://docs.gradle.org/release-nightly/samples/sample_java_modules_with_transform.html))

**Comment by ajalt** [comment]
I can look into that.

Out of curiosity, are you using Clikt from Java? What is the advantage you get from using java modules for a kotlin project?

**Comment by Lafreakshow** [comment]
> Out of curiosity, are you using Clikt from Java? What is the advantage you get from using java modules for a kotlin project?

I'm currently building a smallish data analysis app in pure kotlin for the JVM. almost all choices I made pretty much came down to "well, I'm already familiar with it so..."

I work with JavaFX/TornadoFX a lot, I also work for jvm 14+ for a while now and JavaFX 14 is a real pain to use in non modular/mixed applications so that's why I started building pure Kotlin apps using JPMS and got used to it by now. Stronger encapsulation for libraries and JLink packaging are notable advantages. In this most recent project of mine I'm using the ServiceLoader and while that isn't exclusive to JPMS, it's more convenient and explicit to define services in `module-info.java`. I believe there are certain performance benefits to using modules as well, but I doubt I or most applications, really, are ever going to the point of significant performance gains here. There are supposedly also further security benefits, but I don't deal much in that area so I can't confirm this.

It's a bit wacky at times getting Kotlin and JPMS to cooperate. Trouble like I had with Clikt is one common issue. Naturally, authors of Kotlin multi-platform libraries don't pay much attention to JPMS, which I can't fault them for since even many Java devs don't pay much attention to it yet. Anything involving reflection is bound to cause some trouble with JPMS, most likely requiring some jvm arguments but it's an easy enough fix and happens simply because these libraries aren't built with this strong encapsulation in mind. 

In recent months support has gotten a lot better so now most issues I deal with come down to Gradle acting weird. Neither the Kotlin nor the Java plugin really support this use case so I've resorted to rerouting the Kotlin compile output to the java compile output directory. That's the simplest way I've found so far to get the JavaCompile tasks to find the class files the Kotlin compiler spits out. This obviously doesn't work so well in mixed projects but I've been told that there's a proper way to add input files to compile tasks, which I'd probably use if I was doing mixed stuff now. I was relatively new to Gradle when I came up with my workaround and hey, if it ain't broke... Then there's also the fact that Gradle generally doesn't support JPMS that well yet, which has brought me here in the first place.

The most headache inducing part is testing, ironically. Mostly because JPMS doesn't allow the same package in multiple modules and to get around the strong encapsulation one has to put code-under-test and tests in the same module. Also most testing frameworks use *a lot* of reflection. These are somewhat time consuming issues but usually fixable with a few JVM args (note that this is also true for java projects). 

One notable benefit of JPMS here is the possibility of black box testing. As in tests in a completely separate java module which will see the code-under-test from the perspective of a regular consumer. Gives one the chance to properly test with encapsulation intact. Not a new concept by any means but since JPMS strongly enforces encapsulation, it's a lot harder to accidentally circumvent it. (Naturally, being it's own module, this also means all the issues mentioned previously now also affect test code)

Personally, I've grown to like the stronger encapsulation and once the initial few days of working around slight incompatibility and Gradle weirdness, it's no more effort than going non-modular. I don't think the advantages are significant enough to go ahead and convert existing kotlin projects to JPMS and people with deadlines may want to stick to non modular with java 8 or 11 target. (still the most stable for pure kotlin/jvm projects as far as my experience goes). For libraries, an automatic module name is enough to shut the jvm up for the most part. 

One thing I can say though, I recommend not mixing modular/non-modular stuff too much. JavaFX is a good example. It *technically* kind of works in non-modular applications but the effort of fixing the myriad of issues that it causes down the line is much greater than the effort of going modular. Since more and more Java Libraries are now coming fully modular, I've taken to defaulting to that as well, simply to keep things simple and consistent. Generally, it's much simpler to use non-modular libraries in a modular application than the other way around.

Keep in mind here that I haven't worked with Kotlin MMP/Native at all yet. If I'm not mistaken, the build process is a bit different there. I can't say whether that introduces additional problems. I'm thinking specifically of how the Java Compiler has to work with the Kotlin Compilers output to compile `module-info.java`. If MMP/Native builds produce class files in a non-standard manner, that could lead to some problems. The issue of packages in different modules may also arise, depending on how the separation between common and platform specific code translates to jar files.  These are probably easy to figure out. I just have absolutely no idea about Kotlin multi-platform builds.

**Comment by ajalt** [comment]
Thanks for taking the time for the write up! I'm a little concerned about the testing issues you mentioned. Do you know of any examples of how to test with JPMS? I assume just running on JDK 14 isn't enough.

**Comment by ajalt** [comment]
Implemented in #295

**Comment by Lafreakshow** [comment]
I'm sorry for this late of a response. Unfortunately I fell quite ill for a while but now I'm back! I hope you don't mind too much.

Thanks for getting this done!

Let me know if you still want to know more about JPMS and testing. I mostly just write unit tests and run them on the classpath, circumventing JPMS entirely. So unfortunately I can't say too much from experience here. When I have to with deal modules during testing I usually end up [here](https://docs.gradle.org/current/userguide/java_testing.html#sec:java_testing_modular) in the Gradle docs. For a general overview, I've found [this](https://sormuras.github.io/blog/2018-09-11-testing-in-the-modular-world.html) very helpful as a starting point. While it's a bit older, everything there still applies and the article pretty much covers the major problems with testing in JPMS and how to deal with them.

If the goal is to test how the library behaves under JPMS then black box testing is the one you need as classpath and white box testing both more or less circumvent JPMS. Things like reflection can be very tricky because it's hard to predict what the code will require access to but when the magic is mostly internal it should be enough to call every endpoint from a black box test. That way, your tests will fail should something not be accessible from outside the module. Someone who actually writes modular tests for a living could probably give a lot better advice on this though...

I believe you use reflection to inject parameters into command classes so you may want to mention in the documentation somewhere that consuming modules need to make sure that classes which clikt will reflect on are `open` to clikt. Though the JVM's error messages regarding access violation are pretty concise and clear so anyone somewhat acquainted with JPMS should manage without a hint in the documentation.

**Comment by ajalt** [comment]
Thanks for the info. The only reflection that Clikt does is [`::class.simpleName`](https://github.com/ajalt/clikt/blob/a220c2c9173df9dace0c2a87f9bff86b211b6428/clikt/src/commonMain/kotlin/com/github/ajalt/clikt/core/CliktCommand.kt#L517), which I don't think would cause any access violations.

**Comment by Lafreakshow** [comment]
Only reflective access to non public classes or members will cause issues. So `::class.simpleName` should be non problematic. I'm not entirely sure how things work if you try this on a non public class but I think that case would be pretty rare. And it's not like you could do anything about it anyway. Glad I could help.
