### ISSUE TITLE
Cannot build Kotlin native binaries

### ISSUE THREAD

**Issue by JoeRourke123** [ajalt/clikt#296]
The binaries build for a simple hello world application but as soon as I add in the simple Clikt example and dependencies in my Gradle build file - I get a `java.lang.IllegalStateException` with a message saying that `Deserializer for declaration public kotlin.text/titlecase|7326534260091731227[0] is not found`. I'm trying to build for macOS (Intel) using Gradle 6.8. The build fails at the ":linkDebugExecutableNative" step of execution.

Below is my Gradle file:
```
plugins {
    kotlin("multiplatform") version "1.4.32"
}

group = "space.flotion.tools"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

kotlin {
    val hostOs = System.getProperty("os.name")
    val isMingwX64 = hostOs.startsWith("Windows")
    val nativeTarget = when {
        hostOs == "Mac OS X" -> macosX64("native")
        hostOs == "Linux" -> linuxX64("native")
        isMingwX64 -> mingwX64("native")
        else -> throw GradleException("Host OS is not supported in Kotlin/Native.")
    }

    nativeTarget.apply {
        binaries {
            executable {
                entryPoint = "main"
            }
        }
    }
    sourceSets {
        all {
        	dependencies {
        		implementation("com.github.ajalt.clikt:clikt:3.2.0")
			}
		}
    }
} 
```

Are there any ideas of what could be the cause here?

**Comment by JoeRourke123** [comment]
Would like to mention that I haven't used Kotlin in multiplatform/native mode before so it's possible I'm just doing something wrong there...

**Comment by JoeRourke123** [comment]
Switching down to 3.1.0 seemed to fix the issue - unsure as to what changes caused it to break...

**Comment by ajalt** [comment]
Clikt 3.2.0 is built with kotlin 1.5.10, but you're using kotlin 1.4.32. For native binaries, you usually need to build with the same compiler version as your libraries.
