### ISSUE TITLE
Is it possible to use groupSwitch inside OptionsGroup

### ISSUE THREAD

**Issue by eiva** [ajalt/clikt#297]
Trying to define options group where few of options are exclusive.

```
private class MyOptions : OptionGroup(
) {
     val someParam by option("--some").required()
     val switchParam by option().groupSwitch("--a" to "A", "--b" to "B").reqired()
}
```

And this shows some stange compile-time errors:
```
Property delegate must have a 'getValue(MyOptions, KProperty<*>)' method. None of the following functions is suitable: 
...
```

Also questions: 
- is it possible to define some validations right in the OptionsGroup?
Like override something? That could help to define complex mutual exclusive parameters.
- is it possible to define conversion for entire group right in OptionsGroup? So when this group will be used in multiple place client code dont need to take care of converting to something.

Thanks a lot!

**Comment by ajalt** [comment]
1. No, Clikt doesn't support nested option groups, and I don't plan on adding support in the future: they would make help output difficult to understand. [Subcommands](https://ajalt.github.io/clikt/quickstart/#nesting-commands) may be a better way to structure your tool.
2. Yes, you can add `validate` blocks to any options in a group, and those blocks can reference other options in the group. But keep in mind that complex requirements can make your tool harder to use. Most tools will instead ignore options that aren't applicable to a chosen configuration.

**Comment by eiva** [comment]
Thanks for reply.
