### ISSUE TITLE
Idea : Documentation generator

### ISSUE THREAD

**Issue by Lysoun** [ajalt/clikt#298]
A generator to create documentation for the CLI, based on the commands and their options. It would be very helpful to maintain CLI documentation.

**Comment by Lysoun** [comment]
Oh is there a way to export that? I would like to maintain a documentation for my CLI in the README of my project, to ensure all documentation can be found at the same place, even if doing ```--help``` should be enough.

**Comment by ajalt** [comment]
Sure. You can do the usual `./mycommand --help > output.txt` to save the help output to a file. `--help` just prints the string returned by [`command.getFormattedHelp()`](https://ajalt.github.io/clikt/api/clikt/com.github.ajalt.clikt.core/-clikt-command/get-formatted-help.html), so you can also call that function yourself and do whatever you'd like with the string.
