### ISSUE TITLE
Externalise call to System.getenv

### ISSUE THREAD

**Issue by Mahoney** [ajalt/clikt#299]
Testing anything that relies on `System.getenv()` is a pain - it would be much easier if, say, `CliktCommand.parse()` looked like this:
`fun parse(argv: List<String>, parentContext: Context? = null, env: Map<String, String> = System.getenv())`

Then clients of clikt have optional complete control over when `System.getenv()` is called, so can test as they see fit.

**Comment by Mahoney** [comment]
Or it could be part of the `init { context {} }` block, which would fit with the configuration file parsing.

**Comment by Mahoney** [comment]
OK, just worked out that what I want is this:

```kotlin
import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.context
import com.github.ajalt.clikt.sources.MapValueSource
import com.github.ajalt.clikt.sources.ValueSource.Companion.envvarKey

private class CliParser(
  private val env: Map<String, String> = System.getenv()
) : CliktCommand {

  init {
    context {
      valueSource = MapValueSource(env, envvarKey())
      autoEnvvarPrefix = "MY_APP"
    }
  }
}
```

I wonder if that's worth documenting? Or perhaps I missed it.

**Comment by ajalt** [comment]
The ValueSource is a clever workaround, but I think adding explicit support for setting the environment in the `context` block would be the best solution. I'm thinking something like this:

```kotlin
class CliParser(
  env: Map<String, String> = System.getenv()
) : CliktCommand {

  init {
    context {
      readEnv = env::get
      autoEnvvarPrefix = "MY_APP"
    }
  }
}
```

Where `readEnv` is `(String) -> String?` and defaults to the equivalent of `System::getenv`

**Comment by sschuberth** [comment]
BTW, if this is only about testing, *kotest* has a nice [withEnvironment()](https://kotest.io/docs/extensions/system_extensions.html#system-environment) call.
