### ISSUE TITLE
Possible values for options are missing in a help message if a type is specified

### ISSUE THREAD

**Issue by gstromov** [ajalt/clikt#300]
Found in **version: 3.2.0**

**Issue description:**

`--help` for an `option` doesn't provide possible values in case if a type specified. To say it more accurately, a type specification erases information about choices in a help message.

For instance, for this `option` declaration:
```
    private val jUnitVersion by option("-j", "--junit-version", help = "Test framework to be used")
        .choice("4" to 4 , "5" to 5)
        .default(4)
``` 
it prints:
```
  -j, --junit-version [4|5]        Test framework to be used
```
However, if code is slightly modified like this:
```
    private val jUnitVersion by option("-j", "--junit-version", help = "Test framework to be used")
        .choice("4", "5")
        .int()
        .default(4)
```
it prints:
```
  -j, --junit-version INT          Test framework to be used
```

**Expected behavior:**
Help messages are identical for both declarations

**Comment by ajalt** [comment]
Hm, the current behavior seems correct to me. The `[4|5]` and `INT` text are the option's [metavar](https://ajalt.github.io/clikt/parameters/#metavars). Any time you call `convert` (which `int` and `choice` both do), you can set the metavar that will be used. And ince `int` is called last, it sets the metavar to `INT`, which matches the type of the final option.

I guess an argument can be made that the first conversion's metavar should be used, like in your case. I don't know if most people will expect it to work like you suggest, or how it currently does.

**Comment by gstromov** [comment]
Thank you, agreed
