### ISSUE TITLE
Build for Apple Silicon

### ISSUE THREAD

**Issue by lgorence** [ajalt/clikt#302]
As of Kotlin 1.5.30-M1, there is [native support for Apple Silicon](https://blog.jetbrains.com/kotlin/2021/07/kotlin-1-5-30-m1-released/#apple-silicon-support). Once 1.5.30 is fully released, can we please get builds for ARM Macs?

**Comment by ajalt** [comment]
GitHub Actions doesn't have any M1 runners right now. It's not clear whether you'll be able to cross compile the Arm binaries from an Intel Mac. If you can, I'm willing to add that target with a notice that tests aren't run for it, so it's not fully supported. If you can't cross compile, then there's nothing we can do.

**Comment by twyatt** [comment]
Compiling arm64 on GitHub Actions does work, as can be seen with [Kable](https://github.com/JuulLabs/kable).

**Comment by twyatt** [comment]
Upstream issue for GitHub Actions getting Apple Silicon support: https://github.com/actions/virtual-environments/issues/2187
