### ISSUE TITLE
undefined arguments "eaten up" silently on allowMultipleSubcommands = true

### ISSUE THREAD

**Issue by HoffiMuc** [ajalt/clikt#303]
I have a `CliktCommand(allowMultipleSubcommands = true)`

neither the parent CliktCommand nor any of its sub-commands define any `by argument()` things at all.

```kotlin
val subCommands = listOf(
    BootstrapInfra(),
    BootstrapK3s(),
    Scratch()
)

fun main(args: Array<String>) {
    if(args.isNotEmpty()) {

        App().subcommands(subCommands).main(args)

    } else {
        // multiple default commands on no args
        App().subcommands(subCommands).main(arrayOf(
            "bootstrap-infra",
            "bootstrap-k3s"
        ))
    }
}

class App: CliktCommand(allowMultipleSubcommands = true) {
    private val log by LoggerDelegate()

    override fun aliases(): Map<String, List<String>> = mapOf(
        "infra" to listOf("bootstrap-infra"),
        "k3s" to listOf("bootstrap-k3s"),
        "s" to listOf("scratch"),
    )

    override fun run() {
        log.info("App.run() ran!")
    }
}

```

if I now call my App with args e.g.:

`bootstrap-infra first bootstrap-k3s 'second' 'third fourth' 'fifth'`

I'd expect the App to complain that there is no command first or second or ...

but these args are silently eaten up by Clikt without complaining anywhere.

(so if a user just forgot to prefix an optional opt with '--' it will now just silently be ignored)

even if I have all sub-commands with `CliktCommand(printHelpOnEmptyArgs = true)`

`bootstrap-infra bootstrap-k3s eins "zwei drei" vier'`

does not issue any error or the help.

Is that intentional or am I missing something?

**Comment by ajalt** [comment]
Thanks for the report! I'll make a new release one Kotlin 1.5.30 is out. In the mean time, you can use a snapshot build to see if the fix works for you.
