### ISSUE TITLE
Multiple arguments, and a default value

### ISSUE THREAD

**Issue by janderssonse** [ajalt/clikt#305]
Maybe I'm missing something, but is there way to have a default (list,set etc) value when using argument(.. and the mulitple() function together?. I just can't' seem to find it in the api. 

I.e
Works, but without default:
  val inputDirs: List<Path> by argument(
        help = "a list of directory paths containing video files to package. (default: $defaultInputDir)"
    ).path(
        mustExist = true,
        canBeFile = false,
        mustBeReadable = true
    )
        .multiple()

What I would like, something like

  val inputDirs: List<Path> by argument(
        help = "a list of directory paths containing video files to package. (default: $defaultInputDir)"
    ).path(
        mustExist = true,
        canBeFile = false,
        mustBeReadable = true
    )
        .multiple(). default(listOf(defaultInputDir))

or 

  val inputDirs: List<Path> by argument(
        help = "a list of directory paths containing (default: $defaultInputDir)"
    ).path(
        mustExist = true,
        canBeFile = false,
        mustBeReadable = true
    )
        .multiple(default=listOf(defaultInputDir))

**Comment by ajalt** [comment]
Good catch, the `default` parameter for `multiple` only exists for options. I'll add it. 

In the meantime, you can implement it yourself easily: 

```kotlin
val arg by argument().transformAll(nvalues = -1) { it.ifEmpty { yourDefault } }
```

**Comment by janderssonse** [comment]
Thanks for the quick response, and the suggested temporary solution.
