### ISSUE TITLE
Add a tri state flag option

### ISSUE THREAD

**Issue by BomBardyGamer** [ajalt/clikt#309]
I've been using this library for a while, and I think it's a great library. It's very nice and clean to create options, and you don't even have to manually construct an option parser or anything, but I have one problem that I have a suggestion for.

I propose a flag option with 3 possible values: true, false, and not set. Now, I know you can create your own options to parse with, but I think this would be a nice thing to have built-in. I think this could either be done by making a flag option with a nullable boolean (probably more suitable with the design of this library, with the nullable integer and string options), or by creating an enum or something that has the 3 possible values.

Or, what would be even better than this is a way to check if an option was actually provided or not.

**Comment by ajalt** [comment]
You can implement this yourself easily:

```kotlin
val opt: Boolean? by option().convert { it.toBoolean() }
// use like --opt=true
```

Or in flag style:

```kotlin
val opt: Boolean? by option().switch("--on" to true, "--off" to false)
// use like --on
```

I might consider adding the first form to Clikt, but the flag version seems too niche.
