### ISSUE TITLE
Unsigned integers for parameter types

### ISSUE THREAD

**Issue by Blacklands** [ajalt/clikt#316]
Unsigned integer types are stable in Kotlin [since some time](https://blog.jetbrains.com/kotlin/2021/04/kotlin-1-5-0-rc-released/#stable-unsigned-integer-types). Would it be possible to add built-in parameter types (so, converters) for `UInt` and `Ulong`?
For now, we can do `convert { it.toULong() }` and the like, but this isn't as nice as having native support with better error messages and so on.

**Comment by ajalt** [comment]
Good idea, I added these in d3fdddf

**Comment by snpefk** [comment]
Commits leads to something outside of the project, any plans to release it?

**Comment by ajalt** [comment]
@snpefk Sure, you can try it with the [latest snapshot build](https://github.com/ajalt/clikt#snapshots).  Let me know what you think.

**Comment by snpefk** [comment]
Whoops, didn't notice snapshot section in README. Thank you, will try!
