### ISSUE TITLE
HelpTagDefault not localized

### ISSUE THREAD

**Issue by StefRe** [ajalt/clikt#322]
Minimum **example** to reproduce:

```
import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.context
import com.github.ajalt.clikt.output.CliktHelpFormatter
import com.github.ajalt.clikt.output.Localization
import com.github.ajalt.clikt.parameters.options.default
import com.github.ajalt.clikt.parameters.options.option

class DefaultTagLocalization : CliktCommand() {
    val opt1 by option().default("default value")

    init {
        context {
            helpFormatter = CliktHelpFormatter(showDefaultValues = true)
            localization = MyLocalization()
        }
    }

    override fun run() {}
}

fun main(args: Array<String>) = DefaultTagLocalization().main(args)

class MyLocalization : Localization {
    override fun helpOptionMessage() = "Localized help option message."
    override fun helpTagDefault() = "Localized default tag"
}

```

**Actual output** when invoked with option `-h`:

> Usage: default-tag-localization [OPTIONS]
> 
> Options:
>   --opt1 TEXT  (default: default value)
>   -h, --help   Localized help option message.

**Expected output** when invoked with option `-h`:

> Usage: default-tag-localization [OPTIONS]
> 
> Options:
>   --opt1 TEXT  (Localized default tag: default value)
>   -h, --help   Localized help option message.

If you set a breakpoint at `override fun helpTagDefault() = "Localized default tag"` you see that it's never called as `CliktHelpFormatter` uses the `defaultLocalization` when formatting the default value.

**Comment by ajalt** [comment]
So the problem here is that `CliktHelpFormatter` takes the localization in its constructor, and doesn't read from the context if you create is explicitly. A fix will require a breaking API change, but for now you can do this instead:

```kotlin
context {
    helpFormatter = CliktHelpFormatter(showDefaultValues = true, localization = MyLocalization())
}
```

**Comment by StefRe** [comment]
Thanks for the hint. In the end I had to use

```
context {
    helpFormatter = CliktHelpFormatter(showDefaultValues = true, localization = MyLocalization())
    localization = MyLocalization()
}
```
to get both `HelpTagDefault` and `helpOptionMessage` localized.   

Maybe it should be clearer stated in the documentation ([Localization ](https://ajalt.github.io/clikt/documenting/#localization) and [Default Values in Help](https://ajalt.github.io/clikt/documenting/#default-values-in-help)) that you need to pass the localization separately for the help formatter in addition to general localizcation.
