### ISSUE TITLE
option: Custom converter?

### ISSUE THREAD

**Issue by FrankC01** [ajalt/clikt#323]
Is there a way to have a custom converter?

My program takes a path which may prefix "~/" that I want to expand but the remaining path (i.e. `"~/.stuff"`) may not exist... yet.

Is my only option in the `run` overload?

**Comment by ajalt** [comment]
Yes. [Here's the docs on custom types](https://ajalt.github.io/clikt/parameters/#custom-types). The example in that section shows how to reuse the `file` or `path` type.

**Comment by FrankC01** [comment]
Works like a charm!

I stumbled for a bit over the precedence as I had `.required()` preceding `.convert{}`

Thanks
