### ISSUE TITLE
Trying to use Clikt in a small REPL

### ISSUE THREAD

**Issue by thunderbiscuit** [ajalt/clikt#347]
Hi there! I've been a fan of Clikt for a while now, and I have used it in a few small projects. Thanks for writing such an awesome tool.

I'm opening this issue because I'm writing an app that is longer lived and to which I'd like to send instructions through a command line prompt. A REPL would be perfect for that, and I'd love to use Clikt's type safety and help messages and everything it provides. I have something that works fairly well at the moment (see code below) but my only issue is that if there is any error at all in the parsing of the input Clikt will exit my entire application instead of simply throwing an error I can handle while keeping the loop/application alive. 

I'm wondering if you have any ideas on how to leverage Clikt better to solve my issue. I know you mentioned in #61 that you don't intend to support REPLs natively in Clikt, and I see the dev in #122 who says they were using it in a REPL; that's what gave me the idea to try and use Clikt for my problem too instead of just a while loop with custom sort-of parsing of input strings. 

Here is an example that showcases the functionality I'm looking for (except for the error/exit):

```kotlin
fun main() {
    while (true) {
        print("K-REPL ❯❯❯ ")
        val input: String = readln()
        if (input == "exit") {
            break
        }
        val inputArray: Array<String> = input.split(' ').toTypedArray<String>()

        try {
            KReadEvalPrintLoop().subcommands(listOf(CallHome(), Cookies())).main(inputArray)
            println()
        } catch (e: Throwable) {
            println("ERROR: $e")
        }
    }
}

class KReadEvalPrintLoop : CliktCommand() {
    override fun run() = Unit
}

class CallHome : CliktCommand(help = "Call home", name = "callhome") {
    private val name by option().default("me")
    override fun run() { echo("Hi mom... it's $name") }
}

class Cookies : CliktCommand(help = "Bake cookies") {
    private val number by option().int().default(12)
    override fun run() { echo("Baking $number cookies...") }
}
```
<br/>

This little tool when used gives you something like this:
<img width="600" alt="repl" src="https://user-images.githubusercontent.com/39974688/167292899-cc1277f6-797a-45aa-8390-b239fcbccfda.png">

**Comment by ajalt** [comment]
>  if there is any error at all in the parsing of the input Clikt will exit my entire application instead of simply throwing an error

That's because you're calling `CliktCommand.main` instead of `parse`. See the docs on [exception handling][1] for more details. The API for [`main`][2] also mentions `parse`.

If you have any suggestions for how I can improve the documentation to make that easier to understand, let me know. For example, when searching for a solution to this problem, did you try searching the docs for a keyword that didn't turn up anything useful?

[1]: https://ajalt.github.io/clikt/exceptions
[2]: https://ajalt.github.io/clikt/api/clikt/com.github.ajalt.clikt.core/-clikt-command/main.html

**Comment by thunderbiscuit** [comment]
Oh man this solved my problem instantly. REPL now behaving :100: as expected. I feel bad that the answer was fairly obvious in retrospect, and I do think your docs are absolutely fine as is. I just wasn't looking at the right things. 

---

Let me try to answer your question more directly, as I know what it's like from a maintainer's perspective to get questions that were totally laid out in the docs I wrote. First off, I absolutely _love_ Material for MkDocs. Whenever I see docs written using it I smile in joy at the great time I'm about to have parsing and learning the tool/library I'm researching. So your docs are darn 🔥 and that's all there is to it.

And as they say, "Good docs, good lib". And so it went; back in September I needed to build a small command line tool and I really wanted to try and use Kotlin for it, and I was curious whether I'd get good performance using Kotlin Native. That's the time at which I went through your docs fairly completely, and got a good sense for what the tool was and how to use it. At the time I only grabbed a few of your simple examples, fiddled with them a bit, added my stuff, bam everything worked flawlessly (except I couldn't get the coloured output working using Native for some reason), but otherwise I didn't run into anything that caused me problems at all. All error handling was perfectly handled in the background and I never really had to re-read those error handling pages or have to pay much attention to them.

Fast-forward a few months I had an idea for a tool that required a REPL and immediately came to check out the docs on that for Clikt. Because there were no pages on it I looked into your issues and found 61 where you mentioned this was outside the scope of your project. Fair enough, my team otherwise uses [`clap`](https://crates.io/crates/clap), a Rust parser that does support REPL (but I can't help it I just keep coming back to the Kotlin solutions when I get the chance—I'm just a Kotlin fanboy that's all). At the time I sort of left it there, didn't dig too hard into how to maybe make the REPL work for me with Clikt and just went with the Rust solution.

Now this third time around, when I _again_ wanted to build a REPL and found myself taking another look at Clikt, I was a bit more determined. But here is the catch and my error; I didn't really go back into the docs as much as I could have, and instead much more finely parsed your issues on the repo. That's where the bulk of the search words and all of that went for me. And I was focusing on the repl part, later on not enough with errors. When I command+clicked into the `CliktCommand` class source code, I looked at the `main()` function because this is what I was calling, and this is where I was seeing the `exitProcessMpp(0)` and whatnot for most exceptions, and for some reason the Kdocs* didn't really click for me that indeed I could use parse directly and shortcut the `main` function.

I think in my particular case what would have worked out well for me would have been to either stumble upon a GitHub issue that would have had a small example (I'm trying to turn this issue into just that, and I'll post my final sample in a different comment so it's easy to find for others), or simply have a page addressing this REPL need in the docs (a sort of "Hey we know you want this and it's not natively supported, but here's a small example of how you can make it work if you really want to). Whether there is enough demand for REPLs to dedicate a page for it in your docs I don't know (just having the GitHub issue with an example is probably fine). But my personal experience is that there is a lot of small utility tools we write for ourselves or our teams that are not one-liners and benefit from being live and accepting commands without requiring a whole RPC interface and whatnot, and those often end up being simple `while(true)` loops, but they can really benefit from the power of a parser like Clikt (errors, help messages, long/short option names, etc.).

Anyway thanks for the help! Didn't mean to write a whole novel when I started this response but hey I really like your tool, and I wanted to answer your question fully. Cheers!

<br/>
*Kdocs for `main` are: `This function calls parse and catches and CliktErrors that are thrown. Other errors are allowed to pass through.` Are they bad? I don't think so (maybe other than the second "and" typo). I think maybe I was just going too fast, and didn't see the answer in front of me.

**Comment by thunderbiscuit** [comment]
My final sample behaves as expected, and is the following:

```kotlin
fun main() {
    while (true) {
        print("K-REPL ❯❯❯ ")
        val input: String = readln()
        val inputList: List<String> = input.split(' ')

        try {
            KReadEvalPrintLoop()
                .subcommands(CallHome(), Cookies(), Exit())
                .parse(inputList)
            println()
        } catch (e: PrintHelpMessage) {
            echo(e.command.getFormattedHelp())
            println()
        } catch (e: UsageError) {
            echo(e.helpMessage())
            println()
        } catch (e: Throwable) {
            println("ERROR: ${e.cause}")
            println()
        }
    }
}

class KReadEvalPrintLoop : CliktCommand() {
    override val commandHelp = """
        This application is a Read-Eval-Print-Loop.

        Call any of the commands to do fun stuff.
    """
    override fun run() = Unit
}

class CallHome : CliktCommand(help = "Call home", name = "callhome") {
    private val name by option().default("me")
    override fun run() { echo("Hi mom... it's $name") }
}

class Cookies : CliktCommand(help = "Bake cookies") {
    private val number by option().int().default(12)
    override fun run() { echo("Baking $number cookies...") }
}

class Exit : CliktCommand(help = "Exit REPL") {
    override fun run() {
        echo("Exiting REPL...")
        exitProcess(0)
    }
}
```
