### ISSUE TITLE
Android studio: Cannot access 'com.github.ajalt.clikt.core.ParameterHolder'

### ISSUE THREAD

**Issue by dongfengweixiao** [ajalt/clikt#348]
Run well, but have follow tips.

![1](https://user-images.githubusercontent.com/1300822/167379381-e8c76c25-d8b3-4dc1-aced-4753a21e784a.png)

Cannot access 'com.github.ajalt.clikt.core.ParameterHolder' which is a supertype of 'com.github.ajalt.clikt.core.CliktCommand'. Check your module classpath for missing or conflicting dependencies.

![image](https://user-images.githubusercontent.com/1300822/167379550-20cb7932-8bee-4cfa-93da-aad38b97355b.png)
Cannot access 'com.github.ajalt.clikt.core.CliktCommand' which is a supertype of 'com.yuxing.iperf3.IperfArgs'. Check your module classpath for missing or conflicting dependencies.

**Comment by ajalt** [comment]
It seems like you might have your gradle dependencies setup incorrectly. I don't think that's an issue with this library.
