### ISSUE TITLE
Request for new release

### ISSUE THREAD

**Issue by warrenstapleton** [ajalt/clikt#35]
I am pulling 1.5.0 from jcenter, however the fix I see in the source code to rename subcommands to _subcommands to avoid the namng conflict for internal variables is not available in the current release, making the subcommands mechanism unusable as far as i can tell.  Would you be able to make a new release?  Thanks.

**Comment by ajalt** [comment]
Done! For future reference, if you need to depend on unreleased commits, you have the option to use [JitPack](https://jitpack.io/#ajalt/clikt) to depend on a specific commit or a snapshot.
