### ISSUE TITLE
Required multiple arguments doesn't work

### ISSUE THREAD

**Issue by tersers** [ajalt/clikt#36]
Say I have an argument as follows:

`private val urls: List<String> by argument("urls", help="Some list of URLs.").multiple(true)`

No exception is thrown when the argument is not provided in the CLI. I believe an exception should definitely be thrown in this case. Is there something I'm missing or is this a bug?

Thanks :)

**Comment by ajalt** [comment]
Yep, that's a bug. Thanks for the report!
