### ISSUE TITLE
Idea: Extract core of Argument class into a Kotlin "Pydantic" style Library 

### ISSUE THREAD

**Issue by ghost** [ajalt/clikt#363]
Hello @ajalt,

I love your library, it is one of the best in the Kotlin space and very much useful, appreciate your hard work!

Coming from Python I was trying to find something which could save lots of time would be useful and will be a much better version of the data class which is in the style of the amazing https://github.com/samuelcolvin/pydantic

Looking at your code, you are actually implementing lots of the concept already in your code in the arguments package.
Would it make sense to spin a core library from that code that would be a decent Kotlin style Pydantic?

Here to give a hand or anything else needed if this sound right.

Many Thanks again! 🚀
Dudi

**Comment by dudil-tsg** [comment]
Hello @ajalt,

I love your library, it is one of the best in the Kotlin space and very much useful, appreciate your hard work!

Coming from Python I was trying to find something which could save lots of time would be useful and will be a much better version of the data class which is in the style of the amazing https://github.com/samuelcolvin/pydantic

Looking at your code, you are actually implementing lots of the concept already in your code in the arguments package.
Would it make sense to spin a core library from that code that would be a decent Kotlin style Pydantic?

Here to give a hand or anything else needed if this sound right.

Many Thanks again! 🚀
Dudi

**Comment by ajalt** [comment]
I'm glad you like Clikt!

**Comment by ajalt** [comment]
I'm glad you like Clikt!

Can you provide some more information on your use case? What functionality are you looking for?

**Comment by tjerkw** [comment]
I think this is related https://github.com/ajalt/clikt/issues/371
Right ? @ghost

**Comment by ajalt** [comment]
I'll close this for now due to lack of response. We can open it again if necessary.
