### ISSUE TITLE
Why is TermUi.echo(..) deprecated

### ISSUE THREAD

**Issue by alzamon** [ajalt/clikt#366]
TermUi.echo(..) is @Deprecated, but all the suggested alternative do is call the very same deprecated method. What is the reasoning here?

I am very tempted to use the @Deprecated TermUi.echo(..) method because i want to extract logic to helper functions to hide details from my implemented CliktCommands. 

An alternative could be to create helper-methods that are extension functions of CliktCommand, but since CliktCommand.echo(..) is protected that is not possible.

**Comment by alzamon** [comment]
Thanks. I had a feeling there was something subtle I was missing. 

I'm making a CLI tool for managing versions for other cli-tools. Sample usage `application-manager install kubectl --version 1.23.0` or `application-manager list-versions trivy`.

I would have helper file for instance GithubHelper for downloading binaries from release pages on github.

**Comment by ajalt** [comment]
How about passing in the console or command as a parameter (or extension) to your helper methods? Then the helpers would still use the right console instance rather than the global one.

**Comment by alzamon** [comment]
Yes. It is a possibility. I solved by a callback parameter. But felt it introduced unneccecary complexity.

Anyway.  I feel I understand better now and can close the issue if you want.

**Comment by ajalt** [comment]
Alright. Thanks for the feedback!
