### ISSUE TITLE
access the help message printed by -h?

### ISSUE THREAD

**Issue by curtisullerich** [ajalt/clikt#369]
Is there a way to manually get the help message that's printed by `-h`?

`MyCommand().getFormattedHelp()` seems to be that message, but it does not include the subcommands.

I would like to do this so I can have a `help` subcommand and not require running `--help` or `-h` which is unnatural in my context (I'm using Clikt in a loop for a REPL).

Alternatively, any way of accessing just the commands portion of the help text would do the trick.

Thanks for writing a great library.

**Comment by ajalt** [comment]
`getFormattedHelp()` is what `main` prints when `-h` is encountered. Is it possible that you're calling it before you register the subcommands?

Either way, you don't need to call that to make a help subcommand. You just need to throw [PrintHelpMessage][1]:

```kotlin
class HelpCommand() : CliktCommand() {
    override fun run() {
        throw PrintHelpMessage()
    }
}
```

I think it would make sense to add a command like that to clikt.

[1]: https://ajalt.github.io/clikt/api/clikt/com.github.ajalt.clikt.core/-print-help-message/index.html
