### ISSUE TITLE
Argument values with '=' char in them

### ISSUE THREAD

**Issue by wulf0r** [ajalt/clikt#37]
I am using this excellent library to pass JDBC connection info to my application. Unfortunately this leads to 
the error "Error: no such option:" in the case when the JDBC URL contains an equals sign. How can I handle this case properly?
Here is an example of what happens:

```
λ java -jar database-consistency-checker-1.0.jar jdbc:test:host:port:schema/option1=value1
Usage: database-consistency-checker [OPTIONS] jdbcUrl dbUser dbSchema COMMAND
                                    [ARGS]...

Error: no such option: "jdbc:test:host:port:schema/option1".
```

**Comment by ajalt** [comment]
You can use `--` to tell the parser that all remaining parameters are arguments.

https://ajalt.github.io/clikt/arguments/#option-like-arguments

**Comment by ajalt** [comment]
Let me know if you still have problems, and we can re-open this issue.
