### ISSUE TITLE
GraalVM and Subcommands

### ISSUE THREAD

**Issue by hrothwell** [ajalt/clikt#372]
Will start out by saying so far I love the library, my bigger qualms are with the combination of GraalVM and Windows.... 

I have a current working build of my application using Clikt found [here](https://github.com/hrothwell/anime-cli/tree/bfa684bc50eba232836b3fe15c3099a34fd23d63). This works just fine and GraalVM is able to handle everything just fine to build a Windows native exe.

Exact GraalVM steps found in bat file [here](https://github.com/hrothwell/anime-cli/blob/bfa684bc50eba232836b3fe15c3099a34fd23d63/build-native-image-windows.bat). 

However, when trying to create subcommands off of `Anime` (example from old broken commit [here](https://github.com/hrothwell/anime-cli/commit/7424b16f52f1aaf72d8fefb5278ec23660e5c6ec#diff-3e4c046d9e967e09184d686459936bc02c44bbddb31da08b7dde4c3983ca6494R11)), my `reflect-config.json` created by `agentlib` is no longer created and thus a native build no longer works. Everything works great in jvm (`./gradlew run`)

I have tried several work arounds such as manually parsing main args myself and trying to call different command classes based on args, but eventually that failed to build the `reflect-config.json` as well, which leads me to believe it is not just the subcommand function but perhaps a combination of a few factors which I have yet to look into. 

Opening this issue up as a hopeful discussion topic around `.subcommands()` function and a place for others who may end up in my shoes to conjure to. Is `.subcommands()` known to have/have others had issues with this and GraalVM? I did see some not promising commits from [trietsch/spotify-cli](https://github.com/trietsch/spotify-cli/commit/5011eb71e6e878e5d9ff2b7da6f52a793454743a)... 

If I make any improvements I will make sure to update this thread

**Comment by hrothwell** [comment]
Additional finding:
Calling `.subcommands()` with no commands inside does not break the `reflect-config.json` build by agentlib

**Comment by hrothwell** [comment]
Was indeed a user error on my part with GraalVM. I had read the agentlib [doc](https://www.graalvm.org/22.0/reference-manual/native-image/Agent/) a few times and for some reason this excerpt never really rang a lot of bells:

> It can be necessary to run the target application more than once with different inputs to trigger separate execution paths for a better coverage of dynamic accesses. The agent supports this with the config-merge-dir option which adds the intercepted accesses to an existing set of configuration files

PR where I fixed this found [here](https://github.com/hrothwell/anime-cli/pull/15). Essentially when building the image try to hit all paths we can take (ie subcommands). Hope this might help someone in the future!

**Comment by ajalt** [comment]
Thanks for the info! There's a tech talk about running Clikt on Graal mentioned in #283. I'll add a section to the docs with some info on graal, and I'll make sure to include this gotcha.

FYI Clikt supports kotlin native, so if Graal keeps giving you trouble, you might consider building the native binaries directly. [ktor][1] has an http client that you could use with K/N if you want.

[1]: https://ktor.io/docs/getting-started-ktor-client.html#create-client
