### ISSUE TITLE
`convertToPath()` logic is too strict with `mustExist = false`

### ISSUE THREAD

**Issue by sschuberth** [ajalt/clikt#374]
I'm defining an argument like

    val statementGlobs by argument()
        .file(mustExist = false, canBeFile = true, canBeDir = false, mustBeWritable = false, mustBeReadable = false)

When passing `*.pdf` as the argument, this results in `Error: Invalid value for "STATEMENTGLOBS": Illegal char <*> at index 0: *.pdf`. While it's correct that `*` is not a valid file name character, I'd assume that to play no role with `mustExist = false`.

A work-around of course is to treat the argument as a `String` instead of a `File`, but that defeats a bit the purpose of `file()` when no glob pattern is used.

**Comment by ajalt** [comment]
That [check][1] is just calling java's `Files.exists(argument)`. I guess we could catch that exception and treat it as a non-existent file, but the current behavior feels correct. You're requiring the argument to be a file, and `*.pdf` isn't a valid filename.

[1]: https://github.com/ajalt/clikt/blob/a2af626c91e30c2071b3d6edf33b3b62b938e6a6/clikt/src/jvmMain/kotlin/com/github/ajalt/clikt/parameters/types/path.kt#L37

**Comment by sschuberth** [comment]
> You're requiring the argument to be a file, and `*.pdf` isn't a valid filename.

I get your point, however my thinking was that a non-existing file (which is allowed with `mustExist = false`) also it not a file.

That said, it seem like `Files.exists(argument)` is *not* called as I'm using `mustExist = false`, or? So the check must fail somewhere else.

**Comment by ajalt** [comment]
Good point, it's `Path.of(argument)` that's causing the exception. So even if we skip the check in that case, we can't return a `Path` with that value.

**Comment by sschuberth** [comment]
> So even if we skip the check in that case, we can't return a `Path` with that value.

Ok, thanks for checking; then I'll stick to the work-around to use a `String` argument and do the file checks myself if it's no glob pattern.
