### ISSUE TITLE
Cannot pass VM options using -D and spring boot with Clikt

### ISSUE THREAD

**Issue by thejettanderson** [ajalt/clikt#377]
I'm trying to pass in an argument to override an application.properties variable in spring boot with -Dmy.prop=prop_value, so the command to the program looks like this `mycommand -Dmy.prop=prop_value` or `-Dmy.prop=prop_value mycommand`, but I keep getting the `no such option: -Dmy.prop` error message.

Is there a way to override application.properties values using clikt?

**Comment by ajalt** [comment]
Setting Java system properties is unrelated to Clikt, and depends on how you're running your jar.

I'd suggest using [environment variables][1] instead. Then you could override them with `MY_PROP=prop_value mycommand`

[1]: https://ajalt.github.io/clikt/options/#values-from-environment-variables
