### ISSUE TITLE
Could `CliktCommand` become an interface?

### ISSUE THREAD

**Issue by sschuberth** [ajalt/clikt#378]
I'm currently playing with pluggable subcommands via Java's `ServiceLoader` approach. That is, I want my main command to be extendable by user-defined subcommands for which they add JARs to the classpath at runtime.

It's basically [doable](https://github.com/oss-review-toolkit/ort/pull/6144/files), but my implementation turns out to be not-so-nice (i.e. not really type-safe), mostly because `CliktCommand` is an abstract class instead of an interface, which is the root cause of me having to do [this cast](https://github.com/oss-review-toolkit/ort/pull/6144/files#diff-2dd1bb3aa259877c614672068200c3f404054c7baae9ba83951e5f0e3c2e3124R154).

It would be so much nicer if my `OrtCommand` interface could extend a `CliktCommand` interface, and use that with `ServiceLoader` to discover implementations.

**Comment by ajalt** [comment]
My understanding is that ServiceLoaders can load abstract classes. Could you do something like `abstract class OrtCommand : CliktCommand`?

**Comment by sschuberth** [comment]
> You'd have to repeat the CliktCommand constructor, but that's only a few lines of boilerplate.

Yes, that's possible and was also discussed [here](https://github.com/oss-review-toolkit/ort/pull/6144#discussion_r1036912514), but repeating all constructor arguments is exactly what I'd like to avoid. Independently of whether it's only a few lines of code, it just feels wrong to me.

**Comment by sschuberth** [comment]
> Yes, that's possible and was also discussed [here](https://github.com/oss-review-toolkit/ort/pull/6144#discussion_r1036912514), but repeating all constructor arguments is exactly what I'd like to avoid.

I nevertheless decided to go that route as in our case I only needed to repeat two of the many constructor arguments.
