### ISSUE TITLE
Evaluate default values lazily (to allow them to be based on other option values)

### ISSUE THREAD

**Issue by sschuberth** [ajalt/clikt#380]
I'm trying to base a default value for an option on the value of another option, like

```
    private val repositoryConfigurationFile by option(
        "--repository-configuration-file",
        help = "A file containing the repository configuration. If set, the '$ORT_REPO_CONFIG_FILENAME' file from " +
                "the repository is ignored."
    ).convert { it.expandTilde() }
        .file(mustExist = true, canBeFile = true, canBeDir = false, mustBeWritable = false, mustBeReadable = true)
        .convert { it.absoluteFile.normalize() }
        .default(inputDir.resolve(ORT_REPO_CONFIG_FILENAME))
        .configurationGroup()
```

where `inputDir` is another option, which results in `java.lang.IllegalStateException: Cannot read from option delegate before parsing command line`.

I'm wondering whether this could be circumvented by evaluating default values lazily?

**Comment by JakeWharton** [comment]
You can use https://ajalt.github.io/clikt/api/clikt/com.github.ajalt.clikt.parameters.options/default-lazy.html

**Comment by sschuberth** [comment]
Oh, wow, thank you. I wasn't expecting the function name to change, but to simply take a lambda. But well, the feature is there, so I'm closing this!
