### ISSUE TITLE
groupChoice does not allow options with the same name among the OptionGroup choices

### ISSUE THREAD

**Issue by maximilian-galanis** [ajalt/clikt#383]
It would be great if clikt would allow the option groups choices in a `options().groupChoice()` to share options (contain options with the same name).
I understand that option groups registered to a `CliktCommand` cannot share options due to parsing ambiguities. However, in a `groupChoice` only the options of one of the given groups are relevant, while the options for all other groups are ignored. So technically there should not be any ambiguities in this case.

Here is an example of what I'm trying to do:
```
Backend1Options : OptionGroup("The options of backend 1") { // backend1 reads .txt files
    val txtSource: Path by option("--source")
        .path(mustExist=true, mustBeReadable=true).default("./source.txt").check(...)
    val backend1SpecificOption: Boolean by option().flag()
}
Backend2Options : OptionGroup("The options of backend 2") { // backend2 reads .json files
    val jsonSource: Path by option("--source")
        .path(mustExist=true, mustBeReadable=true).default("./source.json").check(...)
    val backend2SpecificOption: Boolean by option().flag()
}

class Tool : CliktCommand {
    val toolOption1: Boolean by option().flag()
    val backendOptions by option("--backend").groupChoice(
        "txtBackend" to Backend1Options()
        "jsonBackend" to Backend2Options()
}
```

One obvious way to deal with this issue would be to collect all options shared between different backends and put them directly into the Tool command. The problem with this solution is that now both 'backends' would have to agree on the type of source files, their validation, the default and all the other option details.

I'm also open to other solutions for this issue, if you know any.

**Comment by ajalt** [comment]
This actually would still lead to some situations where parsing is ambiguous

consider 

```kotlin
class G1 : OptionGroup() {
    val o by option().pair()
}

class G2 : OptionGroup() {
    val o by option()
}

class C : CliktCommand() {
    val g by option().groupChoice("a" to G1(), "b" to G2())
    val a by argument()
}
```

if the user enters `--o 1 2`, does the `2` token belong to `G1.o`, or to the `a` argument? There's no way to know, so we can't tell which error message to show. `--o 1 2 --g a` isn't parsable without backtracking.

I would say that you're probably best off moving the common options to the root command and doing validation manually in `run`. It's a little more typing, but this feature would add a lot of complication to clikt's internals, so I don't think it's worth implementing.

**Comment by maximilian-galanis** [comment]
Now I see the issue.. Thank you for the explanation.
I have now resorted to using separate sub commands for all the backends of my application.
