### ISSUE TITLE
Missing desktop targets

### ISSUE THREAD

**Issue by mpetuska** [ajalt/clikt#389]
Clikt seems to be missing `mingwX86` and all linux targets except `linuxX64`. Is there a particular reason that's blocking their support?

**Comment by ajalt** [comment]
I don't publish Arm, Mips or x86 targets because GitHub CI doesn't have runners for them. So even if I can cross compile, I can't verify that they work. 

You can always use the JVM build for those targets.

**Comment by mpetuska** [comment]
I see, fair enough
