### ISSUE TITLE
Question: what's a good way to handle required environment variable options?

### ISSUE THREAD

**Issue by dtanner** [ajalt/clikt#392]
### Use case
A script that will be used by an automated process (no humans) requires a password as input.
I'm planning on requiring an environment variable to exist for this. In this scenario, I don't ever want users inputting the password via a command option because then the password could be logged to history. They should only use an environment variable.

### How I'm implementing it so far
`private val somePassword by option(envvar = "SOME_PASSWORD", hidden = true).required()`

and I'm indicating that `SOME_PASSWORD` is required in the `epilog` field to help users know it's required, while hiding the option in the normal help output.

This works, but it's not ideal. The issue is that the error message is this:
```
Usage: my-command [OPTIONS]

Error: Missing option "--some-password"
```

...which hints to them something they shouldn't do in this case.  Is there a better out of the box approach for this scenario I should be using, or is the best option for now some custom validation in `run`?  Thanks!

**Comment by dtanner** [comment]
Closing my own issue...if you think there's a better way, but this seems easy enough for this scenario.

```
    override fun run() {
        if (somePassword.isNullOrBlank()) {
            throw UsageError("SOME_PASSWORD is a required environment variable.")
        }
```

**Comment by ajalt** [comment]
You don't want an option, so I would suggest not using one. Just read the value from `System.getenv` yourself.
