### ISSUE TITLE
mutuallyExclusiveOptions does not work in OptionGroup

### ISSUE THREAD

**Issue by ulrikrasmussen** [ajalt/clikt#393]
When I try to factor out common options in an `OptionGroup` then `mutuallyExclusiveOptions` fails to type check because its implementations of `getValue()` and `provideDelegate()` assumes that the parent object is of type `CliktCommand`.

For example, consider this code from [the documentation](https://ajalt.github.io/clikt/options/#mutually-exclusive-option-groups):

```kotlin
sealed class Fruit {
    data class Oranges(val size: String): Fruit()
    data class Apples(val count: Int): Fruit()
}
class Order : CliktCommand() {
    val fruit: Fruit? by mutuallyExclusiveOptions<Fruit>(
        option("--oranges").convert { Fruit.Oranges(it) },
        option("--apples").int().convert { Fruit.Apples(it) }
    )

    override fun run() = echo(fruit)
}
```

I would expect to be able to factor out the `fruit` option and put it in an option group, but the following code fails to type check:
```kotlin
class OrderOptions : OptionGroup("") {
    val fruit: Fruit? by mutuallyExclusiveOptions<Fruit>(
        option("--oranges").convert { Fruit.Oranges(it) },
        option("--apples").int().convert { Fruit.Apples(it) }
    )
}
```
with the error
```
Property delegate must have a 'getValue(OrderOptions, KProperty*>)' method. None of the following functions are suitable.
getValue(CliktCommand, KProperty<*>) defined in com.github.ajalt.clikt.parameters.groups.MutuallyExclusiveOptions
Property delegate must have a 'provideDelegate(OrderOptions, KProperty*>)' method. None of the following functions are suitable.
provideDelegate(CliktCommand, KProperty<*>) defined in com.github.ajalt.clikt.parameters.groups.MutuallyExclusiveOptions
```

**Comment by ajalt** [comment]
Clikt doesn't support nested option groups, since I'm not sure there's a way to generate help output for them that isn't confusing. Maybe we could allow it in the type system but throw an exception at runtime if any inner groups had a name? That doesn't feel great to me.

**Comment by ajalt** [comment]
So I investigated supporting this, and I don't think it's feasible. Even if you ignore the help formatting, you would still have to recursively finalize groups, which causes too many edge cases.
