### ISSUE TITLE
Allow flag prompts

### ISSUE THREAD

**Issue by rocketraman** [ajalt/clikt#400]
Would be nice if we could prompt for flags. The flag would basically turn into a yes/no prompt with enter choosing the default.

**Comment by ajalt** [comment]
You can't do this in the current version because flags always have a default, but I just added a `nullableFlag` transform on the 4.0 branch so you can do `option().nullableFlag().prompt()`. You can try it out with the latest [snapshot][1]

[1]: https://github.com/ajalt/clikt#snapshots
