### ISSUE TITLE
Subcommand --help shows root command help

### ISSUE THREAD

**Issue by russellbanks** [ajalt/clikt#406]
I'm using Clikt 4.0 snapshot (`4.0.0.214-SNAPSHOT`).

### Root command --help:
![WindowsTerminal_cTPFMTPMPB](https://github.com/ajalt/clikt/assets/74878137/31857d3d-bea9-4f15-8610-68a6969e785f)

### Sub command --help:
![WindowsTerminal_HGbhO1I9Lz](https://github.com/ajalt/clikt/assets/74878137/33f91afb-9425-4404-97ed-106513518290)

They both have the same output despite the remove command having its own help

```kotlin
class RemoveVersion : CliktCommand(
    help = """
        Removes a pre-existing package version in winget-pkgs
        
        To remove an entire package, all versions of that package must be removed
    """.trimIndent(),
    name = "remove"
)
```

```kotlin
fun main(args: Array<String>) {
    Komac()
        .subcommands(NewManifest(), QuickUpdate(), RemoveVersion(), Token().subcommands(Update(), Remove()), Cleanup())
        .versionOption(version = BuildConfig.appVersion, names = setOf("-v", "--version"))
        .main(args)
}
```

**Comment by ajalt** [comment]
Thanks for the clear report! Should be fixed in 98105aae
