### ISSUE TITLE
Expose echo for extension functions

### ISSUE THREAD

**Issue by unredundant** [ajalt/clikt#407]
Hello :wave: enjoying using Clikt a lot. 

A small issue I'm having is that `echo` is a protected function.  The reason I would like to expose it more broadly is so that it can be used in a extension functions.  For example, I am building a native CLI for [neon](https://neon.tech), which involves making many http requests to the neon api under the hood.  

I would like to have something like the following extension function
 
```kotlin
  suspend inline fun <reified T, C: CliktCommand> C.unwrapSafely(
    response: HttpResponse, 
    errorMessage: String
  ): T? = when (response.status.value) {
    in 200..299 -> response.body()
    else -> {
      echo (
        json.encodeToString(
          ErrorMessage.serializer(),
          ErrorMessage(
            message = errorMessage,
            code = response.status.value,
            details = response.bodyAsText()
          )
        )
      )
      null
    }
  }
```

however, I cannot access `echo` in the currently implementation.  This leads to me having to write all of this code in every command, instead of utilizing a single line helper method.  

Would like to hear your thoughts, either to exposing `echo`, or potential alternatives :)

**Comment by ajalt** [comment]
Thanks for the feedback. I implemented this in b79b0bc7 on the 4.0 branch, which you can try out with the latest snapshot build.
