### ISSUE TITLE
Adding parameters programatically

### ISSUE THREAD

**Issue by v-p-b** [ajalt/clikt#408]
I enables/disable different class instances in my application for different builds (compile time). 

I would like these "plugin" classes to be able to register their command line parameters with Clikt, so it will for example generate the help menu according to the current plugin configuration of the build. 

Is there a way to do this with the current Clikt API?

Thank you!

**Comment by ajalt** [comment]
Sure, there's a [sample][1] that uses plugins to add commands

[1]: https://github.com/ajalt/clikt/tree/master/samples/plugins

**Comment by v-p-b** [comment]
Thank you, both options look workable - I was on the second path, but couldn't figure out how to instantiate Options easily.
