### ISSUE TITLE
Allow colored text in option parameter prompts

### ISSUE THREAD

**Issue by russellbanks** [ajalt/clikt#410]
Using Clikt 4.0-SNAPSHOT:

```kotlin
private val packageIdentifierParam: String? by option(
    "-i", "--id", "--package-identifier",
    help = "Package identifier. Example: Publisher.Package"
).prompt(
    text = buildString {
        appendLine(colors.brightGreen("[Required] Enter the package identifier"))
        appendLine(colors.info("Example: Microsoft.Excel"))
        append("Package Identifier")
    }
).check {
    it.length in 4..128 && Regex("^[^.\\s\\\\/:*?\"<>|\\x01-\\x1f]{1,32}(\\.[^.\\s\\\\/:*?\"<>|\\x01-\\x1f]{1,32}){1,7}$") matches it
}
```

This results in `java.lang.IllegalStateException: Context accessed before parse has been called.`

The only workaround I've found is by doing this, but I know using `Terminal()` in this way is bad, especially as it needs opt-in:
```kotlin
text = buildString {
    val terminal = Terminal()
    appendLine(terminal.colors.brightGreen("[Required] Enter the package identifier"))
    appendLine(terminal.colors.info("Example: Microsoft.Excel"))
    append("Package Identifier")
}
```

Please let me know if there's a proper way to do this! Otherwise, I'd love for this to be a properly integrated.

**Comment by ajalt** [comment]
If you don't need theme styles, you can use `TextColors.*` directly, no need for a terminal.

```kotlin
import com.github.ajalt.mordant.rendering.TextColors.*
text = buildString {
    appendLine(brightGreen("[Required] Enter the package identifier"))
}
```

If you need to use the terminal while in the command init, set it on the context:

```kotlin
class C(val t: Terminal): CliktCommand() {
    init { context { terminal = t } }
    val o by option(help=t.colors.info("help"))
}
```

**Comment by ajalt** [comment]
Closing for now since there's a solution. If you have for feedback, we can reopen this.

**Comment by ajalt** [comment]
Although it doesn't affect prompts, in 282d184 I added lazy help setters, so you can do 

```kotlin
class C: CliktCommand() {
    val o by option().help{ theme.info("help") }
}
```

without needing to pass a terminal around yourself
