### ISSUE TITLE
SSL Error when trying to open website

### ISSUE THREAD

**Issue by vewert** [ajalt/clikt#417]
I tried clicking on the link to: [https://ajalt.github.io/clikt/](https://ajalt.github.io/clikt/) to see more information and documentation, but got the following error:

> ## This site can’t provide a secure connection
> **ajalt.github.io** sent an invalid response.
> [Try running Windows Network Diagnostics](javascript:diagnoseErrors()).
> ERR_SSL_PROTOCOL_ERROR

I tried with various browsers and got similar results.

**Comment by ajalt** [comment]
Thanks for the heads up, but the website is hosted on GitHub pages, I don't manage its SSL connections at all. Maybe GitHub was having an issue, or you have some firewall or proxy configuration causing it? Everything works for me.

**Comment by vewert** [comment]
Thanks for your quick reply. You were absolutely correct, for some reason, my router was blocking the GitHub page. I unblocked it and now I can access the documentation.
