### ISSUE TITLE
Help needed: App always returns exit code 1

### ISSUE THREAD

**Issue by Sironheart** [ajalt/clikt#424]
Sorry about opening an issue for this, I just don't really know a better place for asking for help.

I started experimenting with Kotlin Multiplatform and wanted to implement a dotfile manager for testing purposes. Unluckily, my application always exits with an exit code 1.

```
11:03:04: Executing 'runDebugExecutableMacosArm64'...

> Task :dfm:compileKotlinMacosArm64
> Task :dfm:linkDebugExecutableMacosArm64

> Task :dfm:runDebugExecutableMacosArm64 FAILED
Usage: dfm [<options>] <command> [<args>]...

Options:
  -h, --help  Show this message and exit

Commands:
  completion  Generate a tab-complete script for the given shell
3 actionable tasks: 3 executed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dfm:runDebugExecutableMacosArm64'.
> Process 'command '/Users/steffenbeisenherz/projects/dfm/dfm/build/bin/macosArm64/debugExecutable/dfm.kexe'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
11:03:11: Execution finished 'runDebugExecutableMacosArm64'.
```

Source project: https://github.com/Sironheart/dfm

Could you take a look at my setup and tell me what I might be doing wrong? Thank you very much in advance :)

**Comment by sschuberth** [comment]
In your app, `<command>` is a mandatory argument, hence the `runDebugExecutableMacosArm64` task fails if you don't pass it.

As in contrast to JVM apps using the [Gradle application plugin](https://docs.gradle.org/current/userguide/application_plugin.html#sec:application_usage), the Kotlin native plugin [does not support `--args`](https://youtrack.jetbrains.com/issue/KT-55617) for its tasks yet, you need to first build the binaries (without running them via Gradle) and then run the binaries directly / manually from your shell to be able to pass any mandatory arguments.

**Comment by Sironheart** [comment]
I believe this can be /closed, even though running the release/ native binary still returns a status code of 1. 
In case you want to reproduce the behaviour afterwards:
- Macbook
- Fish Shell
- [the project at point of behaviour](https://github.com/Sironheart/dfm/commit/560cf94e43aac11be75c4d84614bf5f6ec0c86ce)

**Comment by sschuberth** [comment]
For `--help` exiting with 1, this has been [fixed](https://github.com/ajalt/clikt/pull/425) meanwhile.
