### ISSUE TITLE
Documentation refers to non-existing option

### ISSUE THREAD

**Issue by zeldigas** [ajalt/clikt#426]
Looks like in version 4 `requireConfirmation` flag in `prompt` was removed, but documentation still refers to it: https://ajalt.github.io/clikt/options/#password-prompts

As a side note: I can't find alternative in current codebase

**Comment by ajalt** [comment]
Thanks for the heads up! I added [ConfirmationPrompt][1] to mordant, and once i make the release, I'll use it to add `requireConfirmation`  back to clikt's `prompt`.

[1]: https://github.com/ajalt/mordant/commit/8ccdc4739251e36935651eb6efd8d24b6c74085b
