### ISSUE TITLE
Feature request: add a WASM target

### ISSUE THREAD

**Issue by ZacSweers** [ajalt/clikt#438]
Even if it's just experimental, would be helpful for applications that are testing support and use clikt

**Comment by ajalt** [comment]
So I looked into this and it seems that the wasm source set is somehow a dependency of the js source set, so [`jsTest` fails to configure][1]. If you know of some workaround, let me know. 

Once kotest adds a wasm target, I'll try again. That probably won't happen until coroutines has a stable release with wasm support, though.



[1]: https://github.com/ajalt/colormath/actions/runs/5812418349/job/15757769530
