### ISSUE TITLE
Feature Request: Allow OptionGroups to be nested

### ISSUE THREAD

**Issue by paulduffin** [ajalt/clikt#440]
This is not an urgent request (as I am stuck on 3.5.3 for the foreseeable future) but just something that I would have found useful if I could use it.

`OptionGroup`s are great for sharing and reusing sets of related options. However, because of the restrictions against nesting you have to choose between having one convenient group, or using group based mechanisms like cooccurring options.

So, if I have a group containing, 4 options `A1`, `A2`, `B` and `C`. That group is used on lots of sub-commands. I then want to add a restriction such that `A1` and `A2` are cooccurring then I have to break them out into their own group and add them to all the sub-commands separately, changing the references to them.

I had a little try at doing that myself without modifying Clikt but hit a number of road blocks because I did not have access to the information that I needed.

**Comment by ajalt** [comment]
Hi, thanks for the feedback. This was also requested in #393. This could definitely be useful, but implementing it would require recursive finalization of option groups, which would introduce a lot of problematic edge cases.
