### ISSUE TITLE
Type mismatch: inferred type is MordantHelpFormatter but ((Context) -> HelpFormatter)? was expected

### ISSUE THREAD

**Issue by pykereaper** [ajalt/clikt#443]
Hi,

first: Thanks so much for this awesome library and keep up the good work!

Recently, I updated from 3.5.4 to 4.2.0 and had to migrate some stuff. Everything works fine, except the [display of the default values](https://ajalt.github.io/clikt/documenting/#default-values-in-help).  
When I use the code from your documentation:

```kotlin
class Tool : NoOpCliktCommand() {
    init {
        context { helpFormatter = MordantHelpFormatter(showDefaultValues = true) }
    }

    val a by option(help = "this is optional").default("value")
    val b by option(help = "this is also optional").default("value", defaultForHelp="chosen for you")
}
```

Upon compilation, following error occurs. IntelliJ is also showing that the code is wrong.

```text
Type mismatch: inferred type is MordantHelpFormatter but ((Context) -> HelpFormatter)? was expected
```

Can you help me out, if there's something I can do to fix this issue?
I'm using Kotlin 1.9.0 & Gradle 8.3.

**Comment by ajalt** [comment]
Thanks for the heads up! That should read `helpFormatter = { MordantHelpFormatter(it, showDefaultValues = true) }`. I've corrected that typo in the docs.

**Comment by pykereaper** [comment]
Wow! Thanks so much for this ultra-fast response. Works like a charm! ❤️
