### ISSUE TITLE
`CliktCommandTestResult.stdout` seems to miss some lines

### ISSUE THREAD

**Issue by sschuberth** [ajalt/clikt#450]
I ran into a weird case when [porting some custom test code to use `CliktCommand.test`](https://github.com/oss-review-toolkit/ort/pull/7465): Tests start to fail because not all expected output is present in `stdout` (several intermediate lines are missing). I still need to investigate this further, and also test on Linux (so far I only tested on Windows), but maybe @ajalt already has an idea what the cause may be... probably some flushing related stuff as I'm mixing regular `println` output with Mordant terminal-based output?

**Comment by sschuberth** [comment]
> so far I only tested on Windows

The test also [fails on CI under Linux](https://github.com/oss-review-toolkit/ort/actions/runs/6097257260/job/16544524932#step:6:1561).

**Comment by sschuberth** [comment]
Here's the diff of `stdout` output I'm seeing:

```
$ diff -u ~/Downloads/ort-runMain.txt ~/Downloads/ort-test.txt
--- /c/Users/Sebastian/Downloads/ort-runMain.txt        2023-09-06 15:40:51.367788000 +0200
+++ /c/Users/Sebastian/Downloads/ort-test.txt   2023-09-06 15:43:06.494989800 +0200
@@ -13,21 +13,7 @@
 ANDROID_HOME = C:\Users\Sebastian\AppData\Local\Android\Sdk

 Looking for ORT configuration in the following file:
-        C:\Users\SEBAST~1\AppData\Local\Temp\org.ossreviewtoolkit.cli.OrtMainFunTest8167368713510116351.yml
+        C:\Users\SEBAST~1\AppData\Local\Temp\org.ossreviewtoolkit.cli.OrtMainFunTest3403289522922918673.yml

-Looking for analyzer-specific configuration in the following files and directories:
-    C:\Users\SEBAST~1\AppData\Local\Temp\org.ossreviewtoolkit.cli.OrtMainFunTest11438308662023712643\.ort.yml (does not exist)
-    C:\Users\Sebastian\.ort\config\resolutions.yml (does not exist)
-The following 1 package manager(s) are enabled:
-    Gradle
-The following 1 package curation provider(s) are enabled:
-    File
-Analyzing project path:
-    C:\Users\SEBAST~1\AppData\Local\Temp\org.ossreviewtoolkit.cli.OrtMainFunTest11438308662023712643
-No definition files found.
-Writing analyzer result to 'C:\Users\SEBAST~1\AppData\Local\Temp\org.ossreviewtoolkit.cli.OrtMainFunTest10656446805885795442\analyzer-result.yml'.
-The analysis took 8.746237s.
-Found 0 project(s) and 0 package(s) in total (not counting excluded ones).
-Applied 0 curation(s) from 0 of 1 provider(s).
 Resolved issues: 0 errors, 0 warnings, 0 hints.
 Unresolved issues: 0 errors, 0 warnings, 0 hints.
```

It indeed seems as if all lines printed via regular `println` are missing, see e.g. https://github.com/oss-review-toolkit/ort/blob/02516d79aff0dedc4147358da6c86dcca58dbfc9/plugins/commands/analyzer/src/main/kotlin/AnalyzerCommand.kt#L139-L151.

**Comment by ajalt** [comment]
Yes, you have to use `echo` for it to be captured. That's explicitly called out in the docs for both [CliktCommand.test][1] and [echo][2]. Let me know if you were looking for this information somewhere else so I can update those docs to be more clear.

[1]: https://ajalt.github.io/clikt/testing/#testing-clikt-commands
[2]: https://ajalt.github.io/clikt/quickstart/#printing-to-stdout-and-stderr

**Comment by sschuberth** [comment]
> Let me know if you were looking for this information somewhere else so I can update those docs to be more clear.

Oh. To be frank, I was just reading this paragraph

> Calling `test` will run the command with the given arguments and return a [result](https://ajalt.github.io/clikt/api/clikt/com.github.ajalt.clikt.testing/-clikt-command-test-result/) object that contains the captured outputs and result status code. You can check the captured output with the `stdout` property of the result, errors output with `stderr`, or both combined in with `output`.

and stopped there without noticing the "Caution" box below. I would have expected such an important detail to be part of this text already, not moved out to a separate box.

Anyway, thanks for pointing this out to me. But I still wonder whether there's technically no way to capture `println`, too. Third-party code used by a clikt-based CLI app might be using `println`, and then using `CliktCommand.test().stdout` for testing would be impossible for such scenarios.

**Comment by ajalt** [comment]
I don't believe there's any cross-platform way to capture `println`, so there's nothing more that can be done here.
