### ISSUE TITLE
Use composition over inheritance

### ISSUE THREAD

**Issue by rohdef** [ajalt/clikt#453]
Please change the design to use composition over inheritance

The usage of inheritance causes a tight coupling, which is never (or almost never) desired. The recent making `kotlinx.cli` obsolete is a nice little example of that

Also inheritance is inherently less flexible than composition, despite Kotlin solving a lot of the issues from Java, doesn't mean that all is perfect

**Comment by ajalt** [comment]
Can you please provide an example of a problem you were trying to solve that you could not due to the current design and the code you would like to see instead. Just saying things like "please change the design" is not actionable or useful.

**Comment by rohdef** [comment]
Could not might be saying a bit much, but one that is problematic is dependencies in a multi project structure

Sub-projects should not know about clikt or any other framework used to gather parameters/configurations for a given run. What my sub-project is concerned about is not whether it is run through a CLI, web server etc., it cares about its domain, so it should only know of dependencies relevant to that part of the domain it deals with. Even though one should probably do mapping in most cases that is not a given, a constructed example could be:

```kotlin
// Assumes usage of generics for parsing
val config: ConfigClass = parser.arguments(args)
    ?: configFileReader.read("myFile")
    ?: defaultConfig
doSomething(config)
```

Here the config is only a clikt config in the first case, and with a proper serializing behavior it could actually rely on a framework-independent `ConfigClass`

Also avoiding inheritance makes things much easier with DI frameworks etc. For instance the `run` method is not relevant if I want to pass my arguments around using the DI rather than having the `CliktCommand` as executing part. Then I'd be passing around a method implementation that is either a dummy (kind of has to be in the case of clikt, I found no way to avoid the execution of `run`) or have potentially unrelated behavior to  the passing around

In my specific case I could fortunately go with the flow and let clikt do a quick mapping to independent objects, but that might not be viable in all cases (I'm happy I don't have a mix of global arguments and command arguments that both needs to be in the DI). I have not yet checked how well this works when testing, I recall having major problems when doing KTor/Kodein exactly due to all the frameworks wanting to be the executing party and weird inheritance (and a lack of interfaces rather than subclassing)

**Comment by rohdef** [comment]
https://stackoverflow.com/a/49016/1441857 this actually explains it quite well. So basically if I write an application for fetching images, is that application a `CliktCommand` or is my application an `ImageFetcher`? In my book, my application has a `CliktCommand` (perhaps `CliktAction` would be a better name from that point of view), which is used to know which images to fetch. So basically I want the relationship loosely coupled, not tightly. And just as I want to be able to easily transition from kotlinx.cli right now, I want it to be easy to move to/from clikt as well
