### ISSUE TITLE
JsonValueSource returns with double quotes

### ISSUE THREAD

**Issue by vcifello** [ajalt/clikt#455]
Thank you for this excellent library! The JsonValueSource example is much appreciated, as well.

I wanted to have an option for email in the command line with an option to put them in the config.json triggered by --email without arguments.

--email a@g.com b@g.com results in [ a@g.com, b@g.com]

when read from the config file {
  "email": [ "a@g.com", "b@g.com"]
}

the result is [ "a@g.com", "b@g.com"]

I realize the JsonValueSource is a sample, but I was hoping that there would be an obvious/east solution

Where would be the best place to parse out the double quotes? Shouldn't that be the default functionality? 

Thanks in advance!

**Comment by ajalt** [comment]
Thanks for the report! It turns out `JsonElement.toString()` includes the quotes, and switching to `jsonPrimitive.content` fixes this issue.
