### ISSUE TITLE
option() should infer valueSourceKey

### ISSUE THREAD

**Issue by browngavin** [ajalt/clikt#458]
When I follow the example from https://ajalt.github.io/clikt/options/#values-from-configuration-files the value is not read from the configuration file.

myconfig.properties
```
name = Foo
```

```
class Hello : CliktCommand() {
    init {
        context {
            valueSource = PropertiesValueSource.from("myconfig.properties")
        }
    }
    val name by option()
    override fun run() {
        echo("Hello $name")
    }
}
```
Outputs: "Hello null"

If I modify the option by specifying the valueSourceKey, then it is able to read from the configuration file.

```
class Hello : CliktCommand() {
    init {
        context {
            valueSource = PropertiesValueSource.from("myconfig.properties")
        }
    }
    val name by option(valueSourceKey = "name")
    override fun run() {
        echo("Hello $name")
    }
}
```
Outputs: "Hello Foo"

Similar to how the option name is inferred from the property name when not provided, the valueSourceKey should have the same inferred value.

**Comment by ajalt** [comment]
Hm, I can't reproduce this. You first example works for me with file contents like `name=foo`.

Clikt does infer the value source name, and there are [tests for that functionality][1].

Are you sure that you had a file with the correct name and format?

[1]: https://github.com/ajalt/clikt/blob/master/clikt/src/jvmTest/kotlin/com/github/ajalt/clikt/sources/PropertiesValueSourceTest.kt

**Comment by browngavin** [comment]
Hmm, the only thing that changed between invocations was this line: `val name by option(valueSourceKey = "name")`. No changes to the properties file, so if there were name/format issues it wouldn't have worked with the `valueSourceKey` specified.

Any tips on debugging this or additional information I can add?

**Comment by ajalt** [comment]
The name inference is customizable by passing in a lambda to the `getKey` parameter. The default is exposed in [`ValueSource.getKey`][1]. You could try printing that to see what it infers:

```kotlin
valueSource = PropertiesValueSource.from("myconfig.properties", requireValid=true) { ctx, option ->
    ValueSource.getKey(joinSubcommands = ".")(ctx, option).also { println(it) }
}
```

And make sure the file exists: `println(Files.isRegularFile(Path("myconfig.properties")))`

[1]: https://ajalt.github.io/clikt/api/clikt/com.github.ajalt.clikt.sources/-value-source/-companion/get-key.html

**Comment by browngavin** [comment]
Thanks! Printing out the computed key showed me where there was a hyphenation error.
