### ISSUE TITLE
Documentation is incorrect?

### ISSUE THREAD

**Issue by tcasstevens** [ajalt/clikt#459]
Dear clikt,

In your documentation, I think this command
./gradlew run --args="hello --count=3 --name=Clikt"

Should be
// hello shouldn't be included
// name is an argument
./gradlew run --args="--count=3 Clikt"

**Comment by ajalt** [comment]
Thanks for the feedback! That example wasn't meant to necessarily reflect the command in the previous section, but I can see the confusion there so I updated it with your suggestion.

**Comment by tcasstevens** [comment]
Still looks the same on this page
https://ajalt.github.io/clikt/quickstart/
