### ISSUE TITLE
Flag options from Env var defaulting false via context

### ISSUE THREAD

**Issue by ppslim** [ajalt/clikt#463]
I have a use case in which I want to use Environment variables to provide values for all launching a command. However, I don't want Flag values to have such strict requirements around the value supplied, especially when "not supplied" isn't as strict.

I note form `TransformContext.valueToBool` (and as documented), any other value - thus the else condition - is a failure.

Would it be possible for a context option that makes them none strict, allowing `else` to simply indicate `false`?

Whilst not my primary case, a `--dry-run` flag is an example of a scenario in which a non-strict outcome applies for me. I would prefer the application continue because a user fat-fingered the latter `g` rather than `f` for the value.

FYI, traditionally I completely get that defaulting dry-run to false may be a bad idea or even dangerous. In my specific case, it is non-dangerous and completely reversible to trigger a non-dry-run when the intent was a dry-run.

**Comment by ajalt** [comment]
I'm not going to build this in, but it's easy to implement yourself. A flag is just a boolean option with `transformValues(0..0)`. [Here's the implementation][1]. Any boolean is just a `convert` call with a list of strings it's looking for. You can use your own `convert` instead.



[1]: https://github.com/ajalt/clikt/blob/93d88e9beb90b49fd38cbd94f5bb881b0c69f255/clikt/src/commonMain/kotlin/com/github/ajalt/clikt/parameters/options/FlagOption.kt#L44
