### ISSUE TITLE
multiple cooccurring option groups e.g. val userOptions by UserOptions().cooccurring().multiple()

### ISSUE THREAD

**Issue by HoffiMuc** [ajalt/clikt#468]
[docs for co-occurring-option-groups](https://ajalt.github.io/clikt/options/#co-occurring-option-groups)

Hi, would it be possible to have multiple cooccurring option groups?

val userOptions: ***<big>List&lt;UserOptions&gt;</big>*** by UserOptions().cooccurring()***<big>.multiple()</big>***

```kotlin
class UserOptions : CliktCommand() {
    class UserOptions : OptionGroup() {
        val name by option().required()
        val age by option().int()
        val opt by option().int()
    }
    val userOptions: List<UserOptions> by UserOptions().cooccurring().multiple()

    override fun run() {
        if (userOptions == null || userOptions.isEmpty()) echo("No user options")
        userOptions.forEach {
            userOptions.let {
                echo("name: '${it.name}'")
                echo(" age: '${it.age}'")
                echo(" opt: '${it.opt}'")
            }
        }
    }
}
```

on calling:
- the `required()` option or anything that IS "part of" that `OptionGroup` would "start" a List entry
- another `required()` option starts a new List entry and options of that `OptionGroup` following it belong to that new one
- an option not from that `OptionGroup` "seals" that List entry
- anything that is not "part of" that `OptionGroup` also "seals" it

and then be able to:

```bash
$ ./tool --name hoffi --age=30   --unrelatedOption --name both --age=77 --opt=78   --name jesus --opt=42 --whatewaoption
```

with result:

```txt
name: 'hoffi'
 age:  '30'
 opt:  'null'
name: 'both'
 age: '77'
 opt: '78'
name 'jesus'
 age: 'null'
 opt: '42'
```

Would be cool (I hope it would be possible without any problems, but I'm not sure)

**Comment by ajalt** [comment]
Groups can't be repeated, but [subcommands can][1]. Use a subcommand instead of a group and you can have something like this:

```
$ ./tool --unrelatedOption person --name hoffi --age=30  person --name both --age=77 --opt=78  person --name jesus --opt=42
```

[1]: https://ajalt.github.io/clikt/commands/#chaining-and-repeating-subcommands

**Comment by HoffiMuc** [comment]
My goal is NOT to `run()` a command consecutively, as I am transforming very big files,
I want to have _some_ opts that are "globally" and configure how (e.g. case insensitive) to transform all the files,
_*PLUS*_  multiple *groups* of options that tell, what I want to do with different regions of each file.

As the files are very big, I don't want to run the subcommand x times for achieving all the x transformations,
but give a set of transformations (plus the global options once) so I can do a "transform once"-run on each file,
doing ALL the transformations to it which in turn are defined by the combined information in each *group* of options.

any way on how to achieve something like that?

**Comment by ajalt** [comment]
You don't have to do any processing in your `run`; you can collect the info into your [context object][1] and process everything at the end.

But if you're fixed on not using subcommands, you'll have to [collect the repeated options as arguments][2] and group them yourself. Global options can be declared as usual.

You can't have arguments after a subcommand with `multiple`  arguments. There would be no way to know whether a token should belong to the parent or subcommand.

[1]: https://ajalt.github.io/clikt/commands/#nested-handling-and-contexts
[2]: https://ajalt.github.io/clikt/options/#unknown-options

**Comment by HoffiMuc** [comment]
just to confirm if I correctly understood: (and if so, for others who come acoss this as reference)

for re-cooccuring `OptionGroup`s you'd need
- a `CliktCommand` that has a single `OptionGroup` in it
  and puts them in parents currentContext (its own context to be fetched by subcommand name)
- the parent CliktCommand has to `CliktCommand(allowMultipleSubcommands = true)`
- the `CliktCommand` that ***actually uses*** the **multiple** gatherd `OptionGroup`s
  (which each of aboves `CliktCommand` puts in the context)
  by fetching them from the Clikt context (List or Map)

so e.g.:

the gathering one `OptionGroup` CliktCommand:
```kotlin
class UserOptGroup() : CliktCommand(name = "user") {
    class UserOptions : OptionGroup() {
        override fun toString(): String = "user($login, ${name.singleQuote()}, $age, $opt)"
        val login by option().required()
        val name by option()
        val age by option().int()
        val opt by option().int()
    }
    data class User(val login: String, val name: String?, val age: Int?, val opt: Int?) {
        override fun toString(): String = "User('$login', ${name.singleQuote()}, $age, $opt)"
    }
    val userOptions by UserOptions().cooccurring()
    val unrelatedOption by option("--unrelatedOption").flag()

    override fun run() {
        val parentCtxUsers: MutableMap<String, User> = currentContext.parent!!.findOrSetObject { mutableMapOf() }
        userOptions?.let { parentCtxUsers[it.login] = User(it.login, it.name, it.age, it.opt) }
        // debug output
        echo("UserOptGroup run():")
        echo("  unrelatedOption: '${unrelatedOption}'")
        userOptions?.let { echo("  $it") } ?: echo(" no userOptions")
    }
}
```

the actual CliktCommand using all of above's `OptionGroup`s

```kotlin
class DoWithUsers() : CliktCommand(name = "doWithUsers") {
    val users: MutableMap<String, UserOptGroup.User> = mutableMapOf() // set/filled in run() from parent CliktCommand context
    val args: Set<String> by argument().multiple().unique().help("files to do replacement(s) in")

    override fun run() {
        val parentUsers = currentContext.parent!!.findObject<MutableMap<String, UserOptGroup.User>>()
        parentUsers?.let { users.putAll(it) }
        // debug output
        if (users.isEmpty()) echo("no users!")
        echo("DoWithUsers: ${users.size} users: ${users.entries.joinToStringSingleQuoted()}")
        echo("DoWithUsers: args: ${args.joinToStringSingleQuoted()}")
    }
}
```

**Comment by ajalt** [comment]
That's one way to do it, although you don't necessarily need the group. You can test each command individually if you use `findOrSetObject` instead.

```kotlin
data class User(val login: String, val name: String?)

class UserCommand : CliktCommand() {
    val login by option().required()
    val name by option()

    val users by findOrSetObject { mutableMapOf<String, User>() }

    override fun run() {
        users[login] = User(login, name)
    }
}

class ReplaceCommand : CliktCommand() {
    val users by findOrSetObject { mutableMapOf<String, User>() }
    val args: Set<String> by argument().multiple().unique().help("files to do replacement(s) in")

    override fun run() {
        echo("users: $users")
        echo("args: $args")
    }
}

class Tool : CliktCommand(allowMultipleSubcommands = true) {
    override fun run() {
        // set the context object for subcommands
        currentContext.obj = mutableMapOf<String, User>()
    }
}
```

`test` works with subcommands, you just have to register them like you normally would:

```kotlin
val command = Tool().subcommands(UserCommand(), ReplaceCommand())
val result = command.test(
    "user --login a --name b user --login c replace file1 file2"
)
assertEquals(
    result.output,
    """
    users: {a=User(login=a, name=b), c=User(login=c, name=null)}
    args: [file1, file2]
    """.trimIndent()
)
```
