### ISSUE TITLE
clikt and kscript standalone main have the same JVM signature (main([Ljava/lang/String;)V):

### ISSUE THREAD

**Issue by HoffiMuc** [ajalt/clikt#469]
I want to use [kscript](https://github.com/kscripting/kscript) with clikt.

I want to have the scripts as regular .kt files (and not .kts script files)

So I need a global fun `main(argv: Array<out String>)`
or I need
`companion object { @JvmStatic fun main(args: Array<out String>) = MyCliktCmd().subcommands(MyCliktSubcmd)).main(args) }`

 !!! As my git repo has multiple scripts as .kt files, and I might want to run each individually,
 !!! (and as kscript, file imports and packages are not best friends, unfortunately)
 !!!  I *cannot have* multiple global `fun main()` 

but having a `companion object { @JvmStatic fun main(...` in my ClicktCommand 
***clashes with the non-static main*** of extended `class ClicktCommand` (see code examples below)

thinking about it, there probably isn't much you can do about it.
(but maybe `fun main(argv: Array<out String>)` ***was not "the wisest" choice*** for the central clikt execution entry-point.)

Any thoughts on this??

(footnote: I very very much like clikt ... it is an excelent piece of multiplatform software library!!!)

---

Plain Kotlin code that shows the problem:
I cannot execute BSubClass as its companion main clashes with the non-companion main of ASuperClass
(In case of clikt `ASuperClass` would be `ClicktCommand`

```kotlin
open class ASuperClass {
    //companion object { @JvmStatic fun main(args: Array<out String>) = ASuperClass().superFun(args) }
    fun main(args: Array<out String>) = ASuperClass().superFun(args)
    fun superFun(args: Array<out String>) {
        println("ASuperClass: ${args.joinToString()}")
    }
}
class BSubClass : ASuperClass() {
    companion object { @JvmStatic fun main(args: Array<out String>) = BSubClass().superFun(args) }
    fun subFun(args: Array<out String>) {
        println("BSubClass: ${args.joinToString()}")
    }
}
```

output:
```
Accidental override: The following declarations have the same JVM signature (main([Ljava/lang/String;)V):
    fun main(args: Array<out String>): Unit defined in BSubClass
    fun main(args: Array<out String>): Unit defined in BSubClass
```

Same problem with clikt:
I cannot execute the SuperCmd main()

```kotlin
class SuperCmd : CliktCommand() {
    companion object { @JvmStatic fun main(args: Array<out String>) = SuperCmd().subcommands(SubCmd()).main(args) }
    override fun run() {
        println("cmd: super-cmd")
    }
}
class SubCmd : CliktCommand() {
    override fun run() {
        echo("cmd: sub-cmd")
        echo()
    }
}
```

same compile error:

```
Accidental override: The following declarations have the same JVM signature (main([Ljava/lang/String;)V):
    fun main(argv: Array<out String>): Unit defined in SuperCmd
    fun main(args: Array<out String>): Unit defined in SuperCmd
```

Any thoughts on this??

**Comment by ajalt** [comment]
Put the companion in a different class?

```kotlin
class EntryPoint {
    companion object { @JvmStatic fun main(args: Array<out String>) = SuperCmd().subcommands(SubCmd()).main(args) }
}
```

**Comment by HoffiMuc** [comment]
You're a genius !!! :)))
