### ISSUE TITLE
Add support for TextStyle in the Text Widget.

### ISSUE THREAD

**Issue by Irineu333** [ajalt/clikt#477]
First of all, congratulations on the library, I am amazed by it, creating [my first command line program](https://github.com/Irineu333/EnvManager).

Now for the suggestion:
---

I wanted to print a simple stylized text, but the `Text` widget does not provide support. I looked in the documentation and found nothing. Studying how widgets work under the hood, I managed to create the behavior with:

``` kotlin
terminal.println(
    Lines(
        listOf(
            Line(
                spans = listOf(
                    Span.word("Hello"),
                    Span.space(),
                    Span.word("Word!"),
                )
            )
        )
    ).withStyle(
        TextColors.red
    )
)
```

![image](https://github.com/ajalt/clikt/assets/45833588/de57aceb-89a3-4df5-a22b-5f0da57d00eb)

But I believe it would be much simpler if the `Text` also had a `withStyle` function, making it look like this:

``` kotlin
terminal.println(
    Text("Hello, World!").withStyle(
        TextColors.red
    )
)
```

Or a widget specifically for this, like `StyledText`.

Well, I hope I'm not talking nonsense 😂

**Comment by Irineu333** [comment]
![image](https://github.com/ajalt/clikt/assets/45833588/1d928524-3d28-4f17-8d57-6ace7154297d)
I thought about using this extension, but it is internal.

**Comment by Irineu333** [comment]
I improvised a Widget to use in my project, but it turned out quite bad, first because of my lack of knowledge, and second because some APIs that I would need are internal, like parseText for example:

``` kotlin
class StyledText(
    private val lines: Lines
) : Widget {

    constructor(
        text: String,
        textStyle: TextStyle
    ) : this(
        Lines(
            text.split(BreakLineRegex).map { line ->
                Line(
                    spans = WordOrWhitSpaceRegex.findAll(line).map {
                        if (WhiteSpaceRegex.matches(it.value)) {
                            Span.space(it.value.length)
                        } else {
                            Span.word(it.value)
                        }
                    }.toList()
                )
            }
        ).withStyle(textStyle)
    )

    override fun measure(t: Terminal, width: Int): WidthRange {
        return WidthRange(lines.height, width)
    }

    override fun render(
        t: Terminal,
        width: Int
    ): Lines {
        return lines
    }

    companion object {
        val BreakLineRegex = Regex("\\n")
        val WhiteSpaceRegex = Regex("\\s+")
        val WordOrWhitSpaceRegex = Regex("\\s+|\\S+")
    }
}
```

**Comment by ajalt** [comment]
Take a look at mordant's docs on [Text Colors and Styles][1]. All styles are callable, so you can do this:

```kotlin
import com.github.ajalt.mordant.rendering.TextColors.*
import com.github.ajalt.mordant.rendering.TextStyles.*

val t = Terminal()
t.println(red("This text is red"))
```

Or, if you want to use the `Text` widget for wrapping or alignment, you can do the same thing:

```kotlin
t.println(Text(red("This text is red"), whitespace=Whitespace.NORMAL))
```

This is a question about mordant rather than clikt, so I'll close this issue, but I'll update mordant's docs to talk about the Text widget.

[1]: https://ajalt.github.io/mordant/guide/#text-colors-and-styles
