### ISSUE TITLE
[Question] Callback to execute some code when the help is shown

### ISSUE THREAD

**Issue by leinardi** [ajalt/clikt#479]
I'm using Clikt to set the log level with the following code:

```kotlin
    private val logLevel: Level by option("-l", "--loglevel", help = "TBD")
        .choice(
            "INFO" to Level.INFO,
            "WARN" to Level.WARN,
            "ERROR" to Level.ERROR,
        )
        .default(Level.INFO)

    override fun run() {
        configureLog4j(logLevel)
    }
```
And everything works fine until I use the `-h` or `--help` parameter: in this case `run()` is not executed and the default value for the log level is not set.

Is there a way to execute `run()` also when the help parameter is used or, alternatively, to have a callback when the the help parameter is shown?

**Comment by ajalt** [comment]
Sure! I added docs on customizing the help option in #480. Take a look and let me know if that answers your question.

**Comment by leinardi** [comment]
Hey thanks a lot for the quick r!

**Comment by leinardi** [comment]
Hey thanks a lot for the quick reply! 

> ### Changing the help option behavior
> 
> If you want to run some code when the help option is invoked, or change its behavior, you can define
> the option yourself. The default help option is an [eager option][eager-options] that throws a
> [PrintHelpMessage], so if you wanted to log some information when the help option is invoked, you
> could do something like this:
> 
> === "Example"
```kotlin
    class CustomHelpCommand : TestCommand() {
        init {
            eagerOption("-h", "--help") {
                echo("about to print help")
                throw PrintHelpMessage(context)
            }
        }
    }
```

This suggestion is really nice and it allows me to execute some code when the eager option is executed but I was wondering if there is a way to access the default localized help text that would be shown with the default implementation. It's not big deal, I can just hardcode `"Show this message and exit"`, but I was wondering if there is a cleaner solution.

**Comment by ajalt** [comment]
Good question. You can, but it's a little more involved. [`eagerOption` is just a convenience][1] for `registerOption(option(eager=true))`, so you can use the lazy `help{}` method if you do that yourself. I updated the PR with an example. Let me know if that's clear now.

[1]: https://github.com/ajalt/clikt/blob/510384fdc947ce0300afbe518f857d907de4ad2d/clikt/src/commonMain/kotlin/com/github/ajalt/clikt/parameters/options/EagerOption.kt#L44-L62

**Comment by leinardi** [comment]
Perfect, thanks a lot for the help and for the library!
