### ISSUE TITLE
Add option to override the Pattern used to split environment variables

### ISSUE THREAD

**Issue by jsonbrooks** [ajalt/clikt#48]
I have a case where I need to add a "multiple" option via environment variable and some of these are going to contain spaces.

It looks like my only option at this point is to add my own hacky whitespace escape scheme. I'd prefer to just change the split character to a comma. Can you add the envvarSplit pattern parameter to the "option" function?

**Comment by jsonbrooks** [comment]
Maybe adding the following will already work?

.convert(envvarSplit = Regex.fromLiteral(",")) { it }

**Comment by ajalt** [comment]
That would work, but only for string options.

Here's an extension function that should work on any option:

```kotlin
fun <AllT, EachT, ValueT> OptionWithValues<AllT, EachT, ValueT>.withEnvvarSplit(envvarSplit: Regex) 
        = copy(transformValue, transformEach, transformAll, envvarSplit = envvarSplit)
```

The reason that `evvvarSplit` isn't currently exposed is that it is overridden by some conversion functions, such as [`file`](https://github.com/ajalt/clikt/blob/59500692b3634c6d99f8988597a487f26e6a9c0c/clikt/src/main/kotlin/com/github/ajalt/clikt/parameters/types/file.kt#L67).

**Comment by jsonbrooks** [comment]
Thanks for the workaround.

I wonder if there's a solution to this problem that would work for everyone and could be included in Clikt. I assume you don't want to add that extension for the same reason envvarSplit isn't already exposed?

Perhaps you could keep a defaultEnvvarSplit internally and expose envvarSplit that always overrides in "option"?

**Comment by ajalt** [comment]
Thanks for the suggestion! I added this in bfcd9fba, which is part of the 2.0.0 release. 

You can now pass `envvarSplit` to `option()`, and it will override any defaults from type conversions.

Docs: https://ajalt.github.io/clikt/api/clikt/com.github.ajalt.clikt.parameters.options/option/
