### ISSUE TITLE
Option to echo "raw" String

### ISSUE THREAD

**Issue by PinkieSwirl** [ajalt/clikt#486]
There should be an option to write unaltered Strings to the std-out.

E.g., for business logic one needs to print/echo Strings to the terminal, without any tempering. Imagine popular programs like "cat" or "grep" to alter the output (if not specified).

From the docs it is unclear to me, if this is already configurable.

**Comment by ajalt** [comment]
You can do this with [`terminal.rawPrint()`][1]

[1]: https://ajalt.github.io/mordant/api/mordant/com.github.ajalt.mordant.terminal/-terminal/raw-print.html

**Comment by PinkieSwirl** [comment]
Thanks for the quick reply, but this still converts tabs, for example.

**Comment by ajalt** [comment]
`rawPrint` passes the string unchanged to `kotlin.io.println`, so something else must be making the changes you're seeing?

**Comment by PinkieSwirl** [comment]
Sorry, it was indeed my fault, I failed to convert 2 statements to `rawPrint`. Sorry again.

And thanks for your support on this free and awesome project 👍

**Comment by PinkieSwirl** [comment]
Sorry, it was indeed my fault, I failed to convert 2 statements to `rawPrint`. Sorry again.

And thanks for your support on this free and awesome project 👍
