### ISSUE TITLE
How to nest with dynamic subcommands

### ISSUE THREAD

**Issue by mcred** [ajalt/clikt#49]
I'm trying to create a fairly complex CLI app and like the approach of the [Dynamic Subcommand Example](https://github.com/ajalt/clikt/tree/master/samples/plugins), but I'm not able to figure how how to properly have subcommands of my modules. 

For my main file:
```
class Sample : CliktCommand(
	help = """Sample Main App"""
	) {
	override fun run(){
	}
}

@JvmStatic
fun main(args: Array<String>) {
    val kodein = Kodein {
        bind() from setBinding<CliktCommand>()
        import(containersModule)
    }

    val commands: Set<CliktCommand> by kodein.instance()

    Sample().subcommands(commands).main(args)
}
```

In the containers:
```
class Containers : CliktCommand(
    help = """Container Operations"""
) {
    override fun run() {
    }
}

class List : CliktCommand() {
    override fun run() {
        echo("Hi")
    }
}

val containersModule = Kodein.Module("containers") {
    bind<CliktCommand>().inSet() with provider {
        Containers().subcommands(List())
    }
}
```

I'd like to have the main app, `./sample` have submodules and those submodules have commands such as:
```
./sample containers list
```

The above code samples has an `Unresolved reference: subcommands` for `Containers().subcommands(List())`. What is the proper way to have an imported module have subcommands?

**Comment by ajalt** [comment]
`subcommands` is an [extension function](https://github.com/ajalt/clikt/blob/d538bf8d4a40371c809ca16513de77f2170294db/clikt/src/main/kotlin/com/github/ajalt/clikt/core/CliktCommand.kt#L217). Did you import it (`import com.github.ajalt.clikt.core.subcommands`)?

**Comment by mcred** [comment]
Well. Yup. That as it. Thank you!
