### ISSUE TITLE
Disable prompt() globally

### ISSUE THREAD

**Issue by jacobk** [ajalt/clikt#494]
Hello!

In line with https://clig.dev/#interactivity
> If --no-input is passed, don’t prompt or do anything interactive. This allows users an explicit way to disable all prompts in commands. If the command requires input, fail and tell the user how to pass the information as a flag.

It would be great to have the ability to disable all `prompt()` and have them fall back to being normal options. Including handling of `required()` as needed.

Maybe this is already possible?

**Comment by JakeWharton** [comment]
Cool resource, btw! I sent a PR to add Clikt: https://github.com/cli-guidelines/cli-guidelines/pull/128

**Comment by jacobk** [comment]
> This isn't built in, but you could implement it yourself:
> 
> ```kotlin
> val noInput by option().flag()
> val foo by option().transformAll {
>     when {
>         noInput -> "foo default" // or `throw MissingOption(this)` if it's required
>         else -> terminal.prompt("Enter foo")
>     }
> }
> ```

Thanks! Didn't know about `transformAll`.
