### ISSUE TITLE
How to use command like './hello' ?

### ISSUE THREAD

**Issue by 09ae9c** [ajalt/clikt#51]
I create an IDEA gradle project and write sample code like the README shows, but when I run command `./hello` at root of project, it's not work and I got this error:

```
Java/WorkSpace/CliktDemo 
➜ ./src/main/kotlin/Hello.kt --count=3
./src/main/kotlin/Hello.kt: line 1: import: command not found
...
```
then I clone the project and build it, it's work only when I run command `./runsample copy --help`, not like the README says `./hello --help`,  did i miss something?

**Comment by ajalt** [comment]
You can't run a kotlin file directly. You have to build a jar like you would with any other kotlin or java program. The `runsample` script uses the [gradle application plugin](https://docs.gradle.org/current/userguide/application_plugin.html) to make that easier.

**Comment by 09ae9c** [comment]
Oh! I see!!! 
thanks
