### ISSUE TITLE
No way to timeout on missing input

### ISSUE THREAD

**Issue by pdb-stripe** [ajalt/clikt#521]
I am looking for a solution that would allow `terminal.readLineOrNull` to fail after some period of time, however this does not seem to work. This seems to occur in some other process? So even if I fail the running process, the JVM doesn't shut down. For example, the given code should fail and return null - and it _does_, except the process never completes until input is received

```kotlin
   private fun Terminal.readLineOrTimeout(): String? = runBlocking {
        val executor = Executors.newSingleThreadExecutor()
        var response: String? = null
        executor.submit {
            response = readLineOrNull(hideInput = true)
        }
        delay(1000)
        executor.shutdownNow()
        response

    }
```

**Comment by ajalt** [comment]
That's normal JVM thread behavior. If you want to shutdown without waiting for a thread, you need make it a [daemon thread][1].

On JVM, `Terminal.readLineOrNull` is a wrapper for `kotlin.io.readLineOrNull`, so I don't think there's anything to do here on my end.

[1]: https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/Thread.html

**Comment by pdb-stripe** [comment]
ack, got it. Thanks for the quick response!
