### ISSUE TITLE
Is clikt-core published?

### ISSUE THREAD

**Issue by 0101a1a** [ajalt/clikt#523]
Looking at [clikt](https://github.com/ajalt/clikt/tree/master/clikt#module-clikt-core) module, it provide the following code snippet:

```kotlin
implementation("com.github.ajalt.clikt:clikt-core:$cliktVersion")
```

Using:

```kotlin
implementation("com.github.ajalt.clikt:clikt-core:4.4.0")
```

Would give error: 

```console
Could not find com.github.ajalt.clikt:clikt-core:4.4.0.
Searched in the following locations:
  - https://repo.maven.apache.org/maven2/com/github/ajalt/clikt/clikt-core/4.4.0/clikt-core-4.4.0.pom
  Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

I already declared `mavenCentral()`.

Does this module have a different version or it's something meant to be used internally?

**Comment by ajalt** [comment]
It's not released yet, although I plan to soon. You can use it now with [the latest snapshot build][1]. If you do, I'd love to hear any feedback you have.

[1]: https://github.com/ajalt/clikt?tab=readme-ov-file#snapshots

**Comment by bitspittle** [comment]
Just checking in now that it's almost mid September. I'm experimenting with snapshots locally and they seem to be working fine, but I'm a bit concerned about releasing software on top of a snapshot build (especially since I was using 4.4.0.25-SNAPSHOT recently and just updated to 41-SNAPSHOT and got a handful of compile errors, so it's clear that things are still being experimented with).

As an aside, how come `NoOpCliktCommand` is now part of the mordant module btw and not core?

**Comment by ajalt** [comment]
I've been working on a major version of mordant, which I released this past weekend. Now that that's done, I can update clikt to use it and make a release of Clikt.

> how come NoOpCliktCommand is now part of the mordant module now and not core?

https://github.com/ajalt/clikt/pull/531

**Comment by bitspittle** [comment]
Congrats! I'm not under any urgent pressure, so please don't rush on my account. Feel free to bask in the well-deserved relief of a major release for as long as you'd like :) And thanks for your hard work.

Not sure why I wasn't seeing the `NoOpCliktCommand` in the core module; maybe it was a Gradle sync issue? I'll check again later.

**Comment by ajalt** [comment]
The one in the core module is called `NoOpCoreCliktCommand` to match all the other `CoreCliktCommand`s. The `NoOpCliktCommand` is in the mordant module because it uses the mordant help formatter.

**Comment by EchoEllet** [comment]
`NoOpCliktCommand` was part of the Mordant module, then moved to the core. It didn't use the Mordant help formatter, so renamed to `CoreNoOpCliktCommand` and then a copy of it made in Mordant module with the name `NoOpCliktCommand`.
