### ISSUE TITLE
Add imports to example Clikt program

### ISSUE THREAD

**Issue by m0xb** [ajalt/clikt#524]
The example program in the readme and quickstart doc page (https://github.com/ajalt/clikt/blob/master/README.md and https://ajalt.github.io/clikt/quickstart/) don't include imports. Trying to compile fails with "Unresolved reference: CliktCommand".

<img width="648" alt="Screenshot 2024-06-27 at 10 10 49 PM" src="https://github.com/ajalt/clikt/assets/6164153/3c6ed3d6-0fed-46a4-9e59-3e5e4fc26983">

It looks like the following imports are needed:

```
import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.parameters.options.default
import com.github.ajalt.clikt.parameters.options.help
import com.github.ajalt.clikt.parameters.options.option
import com.github.ajalt.clikt.parameters.types.int
import com.github.ajalt.clikt.parameters.options.prompt
```

I see an old issue mentioning the same thing, but it's closed now: https://github.com/ajalt/clikt/issues/335

**Comment by ellet0** [comment]
Usually, the docs for Java or Kotlin libraries do not include the required imports to be more readable, usually you could auto import the required classes or functions within the IDE.

It seems this example is not a module or sample in the `samples` module, if there is an issue that causes build failure the CI would have caught it.

**Comment by ajalt** [comment]
I agree with EchoEllet. To save space in the docs, I'll leave out the imports
