### ISSUE TITLE
option().splitMultiple(regex) for adding multiple values for one options

### ISSUE THREAD

**Issue by dbogdoll** [ajalt/clikt#54]
Great Library!!!

This would be a nice enhancement to the existing `.multiple()` method.
The regex could specify the separator to split regular expression.

E.g.  `var args by option().splitMultiple(",")`
would parse `--args foo,bar,baz`
into `listOf("foo","bar","baz")`

**Comment by ajalt** [comment]
That would require a change to the parser logic, so it can't be added with just a new extension method. Do you know of any existing programs that have a command line interface like that?

**Comment by jcornaz** [comment]
Separating multiple options-arguments by comma is in the [POSIX guidelines](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html):

> **Guideline 8:**
> When multiple option-arguments are specified to follow a single option, they should be presented as a single argument, using \<comma\> characters within that argument or \<blank\> characters within that argument to separate them.

**Comment by jcornaz** [comment]
>Do you know of any existing programs that have a command line interface like that?

Despite that I think being part of the POSIX guideline should be enough, I also want to say that [Maven](https://maven.apache.org/) has some options taking comma-separated values. Look at the first command line example here: https://maven.apache.org/guides/introduction/introduction-to-profiles.html

**Comment by ajalt** [comment]
Thanks for the suggestion! I added this in 14acb8a, which is part of the 2.0.0 release. 

Docs: https://ajalt.github.io/clikt/options/#multi-value-options
