### ISSUE TITLE
Highlight "required" options in the usage

### ISSUE THREAD

**Issue by dbogdoll** [ajalt/clikt#55]
Could we somehow highlight the mandatory / required options with same special char (like '*') 
when the command usage is displayed?

**Comment by ajalt** [comment]
That info isn't passed to the help formatter, so it can't be done automatically, but you can replace your usage of `required` with something like this:

```kotlin
fun <EachT : Any, ValueT> NullableOption<EachT, ValueT>.requiredWithMessage()
        : OptionWithValues<EachT, EachT, ValueT> {
    return copy(transformValue, transformEach, { it.lastOrNull() ?: throw MissingParameter(option) },
            help = "(required) $help")
}
```

which you would use like this:

```kotlin
val opt by option(help = "my option").requiredWithMessage()
```

to get output like this:

```
Usage: program [OPTIONS]

Options:
  --opt TEXT  (required) my option
  -h, --help  Show this message and exit
```

**Comment by krzema12** [comment]
Did you consider incorporating such feature into the library? It seems quite basic.

> That info isn't passed to the help formatter, so it can't be done automatically

As an end user of the library, it looks like some implementation detail that is the actual limitation. Or is the API of the library the limitation? Also, you have an example of `requiredWithMessage` which could be added to the library or replaced with  the current `required`, it seems generic enough :)

I have a similar issue with options with multiple possibilities - the help message also doesn't display the possible values.

**Comment by ajalt** [comment]
Yes, there are a number of changes that I want to make to the help formatter. This is definitely going to be added.

**Comment by ajalt** [comment]
Thanks for the suggestion! I added this in 5be9f34, which is part of the 2.0.0 release. 

Docs: https://ajalt.github.io/clikt/documenting/#required-options-in-help
