### ISSUE TITLE
Breaking Changes are not Documented

### ISSUE THREAD

**Issue by gmitch215** [ajalt/clikt#550]
Some breaking changes are missing in the documentation.

For example, the old `help` parameter still exists:
![image](https://github.com/user-attachments/assets/261da055-007e-452c-a058-693622f4214f)

I didn't have time to do a thorough inspection, but it seems like some changes are missing.

**Comment by ajalt** [comment]
Thanks for the heads up. I thought I updated everything, but it looks like I missed a spot.
