### ISSUE TITLE
subcommand argfile expansion stopped working after upgrading 4.4.0 -> 5.0.0

### ISSUE THREAD

**Issue by NikkyAI** [ajalt/clikt#558]
after upgrading to `5.0.0` passing `@file` to a clikt subcommand is not expanding it anymore

it seems to be fixed if i run `installMordant(force = true)` in each subcommand.. but i am not sure that is intended

**Comment by ajalt** [comment]
This is expected, Clikt uses mordant to read files. The documentation on [CoreCliktCommand][1] talks about its limitations and how to enable argfile parsing without mordant.

[1]: https://ajalt.github.io/clikt/advanced/#core-module
