### ISSUE TITLE
Add a way to deprecate argument

### ISSUE THREAD

**Issue by jcornaz** [ajalt/clikt#56]
Hello, 

First, thanks a lot for this great tool!

In one of my CLI, I decided to change slightly the API and I want to deprecated some options. 

It would be nice if this could be supported out of the box by `Clikt`.

```kotlin
class MyCommand : CliktCommand() {

  val oldFlag by option("--old-api").convert { it.toBoolean() }.deprecated("Use --new-api instead")
  val newFlag by option("--new-api").flag()

  override fun run() {
     if (oldFlag ?: newFlag) println("Hello world")
  }
}
```

Then if one run `--old-api true`, the program would not crash, but display a warning message:
```
WARNING: The option '--old-api' is deprecated: Use --new-api instead
```

Running `--help` could either not show the option at all, or explicitly state it is deprecated.

Eventually `deprecated`could take a severity argument (warning or error) where the "error" level would make the program crash with a nice and explicit error message in case the deprecated api has been used.

What do you think?

**Comment by ajalt** [comment]
This seems like too niche of a feature to build into clikt, but it's easy to do yourself:

```kotlin
val oldFlag by option("--old-api", help = "deprecated").convert { it.toBoolean() }.validate { println("Use --new-api instead") }
```

The `validate` block is only called if the option is given, so you can add your print there. 

You can of course package it into an extension method like this if you want to reuse it:

```kotlin
fun <AllT : Any, EachT, ValueT> OptionWithValues<AllT?, EachT, ValueT>.deprecated(
        message: String): OptionDelegate<AllT?> {
    return copy(transformValue, transformEach, transformAll, help=this.help + " (deprecated)")
            .validate { println(message) }
}
```

**Comment by jcornaz** [comment]
Thanks for the answer.

Okay, I thought that deprecating features was something that everyone would need sooner or later.

Anyway, as you said I can always write my own extension for it. Just would be nice not having to write (and test) it in each of my projects. I'll see what I do when I will have more need of it.

Thanks for your tips ;-)

**Comment by ajalt** [comment]
Do you have any examples of popular CLI programs with deprecated option names? I'm curious how they communicate that.

**Comment by jcornaz** [comment]
>Do you have any examples of popular CLI programs with deprecated option names

`gcloud` (CLI for using Google Cloud), regulary deprecate CLI options. Just `CTRL+F` "depreacted" here:  https://cloud.google.com/sdk/docs/release-notes. 

`awscli` (CLI for using AWS) is no exception. It is harder to find, because their changelog is not has nice as it is for `glcoud`. But here is a random deprecated option: https://docs.aws.amazon.com/cli/latest/reference/s3api/put-bucket-lifecycle.html

Jenkins also deprecated few options (like `--spdy`) for a while before removing them completely.

I'm sure we can find others. I bet some security CLI like ssh or others deprecate unsecure options from time to time.

**Comment by ajalt** [comment]
Thanks for the suggestion! I added this in 4bec1458, which is part of the 2.0.0 release. 

Docs: https://ajalt.github.io/clikt/options/#deprecating-options
