### ISSUE TITLE
Add support for Native Desktop targets

### ISSUE THREAD

**Issue by Wavesonics** [ajalt/clikt#561]
Man I would LOVE to see support for K/Native targets. Shipping the JVM for a terminal program has always felt kinda wrong to me. I still write my little terminal utils in Go for this reason.

I would love to be able to produce little self contained portable exe files for my terminal utils!

**Comment by ajalt** [comment]
Sorry, it's not clear what you're asking for here. Clikt does [support all kotlin native desktop targets][1].

**Comment by Wavesonics** [comment]
Whops, we're right, sorry, I think because `Desktop native (Linux, Windows, and macOS)` doesn't have any body text below it my eyes some how scanned right over it!
