### ISSUE TITLE
Make possible to use arbitrary input/output stream

### ISSUE THREAD

**Issue by jcornaz** [ajalt/clikt#57]
Prompts and echo use the standard inputs and outputs which makes testing harder and clunky.

It  would be nice to be able to inject custom input and output stream to `CliktCommand` and `TermUi`

**Comment by ajalt** [comment]
#19 added that [ability to customize the `CliktConsole`](https://ajalt.github.io/clikt/advanced/#replacing-stdin-and-stdout) on your commands to do IO however you want. Do you have a use case that isn't covered by that functionality?

**Comment by jcornaz** [comment]
Ah yes indeed. Sorry for the useless issue.
