### ISSUE TITLE
Make 'prompt' option non eager

### ISSUE THREAD

**Issue by dbogdoll** [ajalt/clikt#59]
Hello,

I would like to let the user of the command line decide if he enters the password via the keyboard or if he specifies it via an environment variable.

My program looks like

```
class PromptDemo : CliktCommand(name="prompt") {
    private val pwdViaKeyboard by option().prompt(
            text = "Please enter your password",
            default = null
    )

    private val pwdViaEnv by option()

    val pwd : String
        get() {
            if(pwdViaKeyBoard!=null) {
                return pwdViaKeyBoard
            }
            else if (pwdViaEnv!=null) {
                val pwd = System.getenv(pwdViaKeyBoard)
                if(pwd!=null) return pwd
            }

            throw IllegalArgumentException("You have to specify a password.")
        }

    override fun run() {
        println("pwd: '$pwd'")
    }
}

fun main(args: Array<String>) {
    PromptDemo().main(args)
}
```

My expectation would be that, when I enter
`prompt --pwd-via-env PWD`
and have set the env variable `PWD` to `foo`, that I would get
`pwd: 'foo'`

But I get
`Please enter your password:`.

My expectation would be that only when I specify the option `--pwd-via-keyboard` I would get the password prompt.

Could you add an additional parameter in the prompt() option which lets me evaluate the option, only when the user has required it (via specifying this option)?

Best regards,
Dieter

**Comment by dbogdoll** [comment]
Also the prompt option is always of type String and not String?. 
So I can't detect if a user is not entering a password or used default=null.

**Comment by ajalt** [comment]
You can already call propt options on the command line. I recommend doing something like this:

```kotlin
class PromptDemo : CliktCommand(name="prompt") {
    private val pwd by option(envvar = "DEMO_PWD").prompt("enter your password")
    override fun run() {
        println("pwd: '$pwd'")
    }
}
```

You can call this program in any of the following ways:

```
./promptdemo
./promptdemo --pwd 1234
DEMO_PWD=1234 ./promptdemo
./promptdemo --pwd $SOME_OTHER_ENVVAR
```

There's no need for the user to specify the envvar in another option. There's no need to check if the user has specified the password explicitly.

**Comment by dbogdoll** [comment]
Thanks for the quick response.
