### ISSUE TITLE
Support for REPL

### ISSUE THREAD

**Issue by varunkumar** [ajalt/clikt#61]
Is there a support for REPL? If so, is there an example for the same??

**Comment by ajalt** [comment]
I'm not sure I understand what you're asking. Can you give me more information on what you're trying to do?

**Comment by varunkumar** [comment]
I am looking for something similar to what `Spring Shell` offers. I want to have a REPL for reading commands and their params.

**Comment by ajalt** [comment]
That's beyond the scope of this project. I don't have any plans to add that kind of functionality.
