### ISSUE TITLE
Support manual paragraph breaks in help output.

### ISSUE THREAD

**Issue by sghpjuikit** [ajalt/clikt#67]
Not an issue, rather a question:

Example
```
CliktCommand(help = "Sentence1.\nSentence2.")
```
Will generate help text without the newline characters. I have tried `\n` and `\r`. Am I asking for the impossible (im not familiar with cli low lvl impl) or am I doing something wrong?

I am trying this with gitbash on Windows.

**Comment by ajalt** [comment]
No, the default formatter re-wraps your help text to the console width, and discards all whitespace in the string. You can customize this by overriding [addProlog](https://ajalt.github.io/clikt/api/clikt/com.github.ajalt.clikt.output/-clikt-help-formatter/add-prolog/), which is responsible for formatting your command's help message.

[Here's a smaple that shows how to customize the help formatter](https://github.com/ajalt/clikt/blob/master/samples/helpformat/src/main/kotlin/com/github/ajalt/clikt/samples/helpformat/main.kt)

**Comment by sghpjuikit** [comment]
Thx for the answer, much appreciated.

I was trying to show a bulleted list (tree to be precise) of individual execution cases (that depend on number of file arguments). You pointed me to the right direction and I managed to implement this, however I am not sure if duplicating entire `wrapText` and `wrapParagraph` makes it worth it for me (that's my problem though).

I'm wondering why the whitespaces are stripped down when text is broken into words. Is that due to difficulty determining the length of the text that contains whitespace?

This can be closed now.

```

**Comment by ajalt** [comment]
Yes, that's why I strip whitespace. However, we should definitely support manual paragraph breaks. I'll change the title of this issue to reflect the feature request.

**Comment by sghpjuikit** [comment]
Oh I see, If I have the time I may provide the code myself.

**Comment by ajalt** [comment]
What I want Clikt to support is this:

1. If there are multiple adjacent newlines, leave all of them intact
1. Allow adding the `\b` escape character on a line by itself directly before a paragraph to prevent rewrapping any of that paragraph.

**Comment by ajalt** [comment]
Ok, I implemented this in f61ee0a. I decided to use the marker `#{nowrap}` rather than `\b`, since multiline strings don't allow escape characters. Let me know what you think.

**Comment by sghpjuikit** [comment]
Wow, I did not expect you to implement this, and so quickly at all. I will give it a spin and report my findings.

**Comment by sghpjuikit** [comment]
I have tried the feature. Two ideas:

1
```
help = """#{nowrap}
                nSomeText
           """
```
Will produce the correct help text, but if this is help text of a subcommand, the subcommand's description in its parent command's help text becomes #{nowrap}, because that is the first line. I think this is incorrect behavior. Tried out of curiosity.

2 I think wrapping and whitespace preserving are orthogonal features and I feel really weird abandoning wrapping to obtain whitespace preserving. Particularly if you just want to use `"\n"` characters here and there and now you have to prefix every newline with the nowrap tag. I find this solution very confusing.

**Comment by ajalt** [comment]
Thank you for the feedback! I'll reopen this issue since the feature needs some more work.

**Comment by sghpjuikit** [comment]
Np. Anyway, great library. I'm impressed.

**Comment by ajalt** [comment]
Ok, I pushed afe8fcc, which should fix things. I switched from ` #{nowrap}` delimiter to using markdown-style preformat blocks surrounded by ```, which I think is more intuitive. Let me know if there's anything else that you'd like to see.

**Comment by sghpjuikit** [comment]
As much as I dislike making feature requests (because I feel for the dev), sure I will try the latest commit and report back anything notable.

**Comment by sghpjuikit** [comment]
So I gave it a try, I think it is better.
- Works for arguments now
- Works for entire blocks of text inside `````

But sometimes the ````` appears in the output text so I think this is not working fully as expected.

```
help = """Absolute path to the .fxwl file of the component.
      ```
      The file content is either serialized component or single line with the component's name
      ```
    """
```
produces
```
Arguments:
  FILE  Absolute path to the .fxwl file of the component. ``` The file content
        is either serialized component or single line with the component's
        name ```

```

**Comment by ajalt** [comment]
Thank you for taking the time to test this feature; I really appreciate it. I switched to a stateful parsing algorithm in f12bb8e, which should take care of all the edge cases you found.

**Comment by sghpjuikit** [comment]
Np. Ill take the revision for a spin.

**Comment by sghpjuikit** [comment]
I tried the revision, everything has been fixed. I find this implementation with ``` sufficiently deterministic and simple as well as very useful.

**Comment by ajalt** [comment]
Great! Thanks again for testing this. I'll make a release soon.
