### ISSUE TITLE
Not the centre of the application

### ISSUE THREAD

**Issue by dhakehurst** [ajalt/clikt#69]
my use case for this is to NOT have CliktCommand wrap my whole application. (i.e. the main)

I want it for parsing and retrieving cl argumnets, but I don't want to inherit from it.

i.e. I want to simply have a clparser property at the top level somewhere, and use it for parsing the arguments. and then use it again for retrieving the arguments.

This is mostly possible using your 'NoRunCliktCommand' (a better name would be nice)

but there is no way I can see, from the docs, to retrieve a cl argument/option value from a NoRunCliktCommand object?

They are stored in the _options property...but I can't access it.
can we have a method in the API for doing this please.

e.g. findOption(name:String) : Option

**Comment by ajalt** [comment]
I agree that `NoRunCliktCommand` is not a great name. I'm open to suggestions.

I'm not sure why you want to access the option objects. You can just retrieve the parsed values through the delegate properties.

```kotlin
class Tool: NoRunCliktCommand() {
    val opt by option()
}

fun main(args: Array<String>) {
    val tool = Tool()
    tool.parse(args)
    println("opt value=${tool.opt}")
}
```

**Comment by dhakehurst** [comment]
I am using your library underneath an interface
As one option for implementing the interface.

I need a way to retrieve the values without direct access to the property

**Comment by ajalt** [comment]
I'm still not sure I understand. Can you give me a more concrete example of what you're trying to do?

**Comment by ajalt** [comment]
I'm going to close due to inactivity. We can reopen this if there are any updates.

**Comment by dhakehurst** [comment]
I simply want a function like 
findOption(name:String) : Option
that accesses the _options property

**Comment by ajalt** [comment]
I don't want to expose implementation details without a concrete use case, but you could always keep track of that yourself:

```kotlin
val cmd = NoOpClickCommand()
val o1 = cmd.option() // not using delegate, need to register manually
cmd.registerOption(o1)
val options = mapOf("o1" to o1)
```
