### ISSUE TITLE
Any way to disable file expansion?

### ISSUE THREAD

**Issue by hollyroberts** [ajalt/clikt#76]
Is there a way to disable the @ notation for reading files? I have some input where it would be much easier to specify '@' before the argument as it controls the type of input (eg. slack channels). Ideally I could disable this for the entire parsing, or escape it somehow with the argument.

**Comment by ajalt** [comment]
There's no way to disable it currently, but there definitely should be. I'll add the following behavior:

- Arguments following a `--` will never be expanded
- Allow escaping `@` with `@@` e.g. `@@foo` will assign `"@foo"` to the delegate
- Add an option to the context to turn off @-file expansion entirely

**Comment by hollyroberts** [comment]
That sounds perfect, thanks!

**Comment by ajalt** [comment]
I implemented this in 2b1752e
