### ISSUE TITLE
Running Clikt from Kotlin app instead of script

### ISSUE THREAD

**Issue by pedromss** [ajalt/clikt#81]
Hello. I wanted to use Clikt as part of a kotlin project not just a kotlin script.

Having trouble running it through gradle with `./gradlew run`:

```
> Task :app:run FAILED
Error: Main method is not static in class com.github.ajalt.clikt.core.CliktCommand, please define the main method as:
   public static void main(String[] args)
```

Not sure if this is a gradle problem or a Clikt problem.
Intellij does run it

```kotlin
class App : CliktCommand() {

    private val number : Int by option()
        .required()

    override fun run() {
		println("Hello")
    }
}
```

Tried 2 mains:

1.
```kotlin
fun main(args: Array<String>) {
    val rls = RLS()
    rls.parse(args)
	// rls.run() // also tried explicitly invoking this
}
```

2.
```kotlin
fun main(args: Array<String>) = RLS().main(args)
```

In my `build.gradle.kts`:

```kotlin
application {
  mainClassName = "my.package.RLS"
}

val jar by tasks.getting(Jar::class) {
  manifest {
    attributes["Main-Class"] = "my.package.RLS"
  }
}
```

Is my use case doable with Clikt?

**Comment by ajalt** [comment]
Of course. Take a look at the samples, which are all traditional JVM apps built with the gradle application plugin. You probably are setting your `mainClassName` incorrectly. Your second version of the main function is correct, but since it's a static function, you would need to set the file as the `mainClassName`, not your command class. If the file with your static main function is `my/package/RLS.kt`, then you would set `mainClassName = "my.package.RLSKt"`.

**Comment by pedromss** [comment]
It was the `Kt` suffix... /facepalm

Thank you!

**Comment by erawhctim** [comment]
@ajalt Sorry for hjacking this thread... but do you have any ideas where to look if one is still encountering the "Could not find or load main class" gradle error? 

I have the application plugin set, and my main class configured as such: 
```
application {
    mainClassName = "fully.qualified.package.ClassKt"
}
```

And I've double-checked that my package name, class name, file name are all set correctly (and my source sets in Gradle). 
As far as I can tell, I've configured my project just like all the samples, so I'm unsure why Gradle can't find my main class. 
I even see the class file at the same file path in the `build` dir 🤔 Just curious if you had any thoughts - feel free to disregard if not 🙂 

Also thanks for this fantastic lib! 🎉
