### ISSUE TITLE
Subcommands are not shown in usage unless they have their help text specified

### ISSUE THREAD

**Issue by arocnies** [ajalt/clikt#85]
It seems commands are only listed in the usage if they have non-empty help text.
Steps to reproduce:
1) Copy tool example from https://ajalt.github.io/clikt/commands/
2) Run the main method and see that the usage does *not* contain the `execute` command
3) Add *non-empty* help text to `Execute` class (e.g. `CliktCommand(help = "Foo")`
4) Run the main method and see the usage now contains the `execute` command

Expected behavior (using the "tool" example from https://ajalt.github.io/clikt/commands/):
> $ ./tool
> Usage: tool [OPTIONS] COMMAND [ARGS]...
> 
> Options:
>   --verbose / --no-verbose
>   -h, --help                Show this message and exit
> 
> Commands:
>   execute

Actual:

> $ ./tool
> Usage: tool [OPTIONS] COMMAND [ARGS]...
> 
> Options:
> 
>   -h, --help                Show this message and exit
> 
> Commands:
> 
>

**Comment by ajalt** [comment]
Thanks for the report!
