### ISSUE TITLE
`file(exists = true)` does not fail if option is not specified

### ISSUE THREAD

**Issue by benjamin-bader** [ajalt/clikt#9]
I'm unclear as to the intention of the `exists` flag.  I expected that an unspecified file argument would not exist, and therefore would result in an option-reading failure; on the contrary, clikt seems happy to yield a null file in this case.  Is that intentional?  Why wouldn't an existence requirement imply a non-null requirement?

**Comment by ajalt** [comment]
All of the validation that `file` (and all other type conversions) does is performed on values provided. They are deliberately orthogonal to validation the presence of the value on the command line. For that, you can use functions like `multiple`, `required`, and `default`. You wouldn't want a type conversion to prevent you from customizing that behavior.

**Comment by benjamin-bader** [comment]
Ah, I missed that there is such a thing as `required`.  This makes sense.  Thanks!
