### ISSUE TITLE
Consider switchChoice

### ISSUE THREAD

**Issue by JakeWharton** [ajalt/clikt#94]
Basically the same as `groupChoice`, but instead of a choice I want to vary the options based on a switch.

Example:
```
cmd --foo --foo-bar=hi
```
```
cmd --bar --bar-baz=hey
```
```
cmd --foo --bar-baz=hey  <-- error
```
```
cmd --bar --foo-bar=hi   <--error
```

**Comment by ajalt** [comment]
Great idea, thanks!

**Comment by JakeWharton** [comment]
Thanks!

(And glad you figured out what I meant even thought I named it incorrectly)
