### ISSUE TITLE
Read the output of a command

### ISSUE THREAD

**Issue by saket** [ajalt/clikt#96]
Thanks for building clikt. I have a usecase where I want to perform an operation depending on the user's OS. I was wondering if it's possible to silently run a command and read its output to a variable. Does clikt support this in some way?

**Comment by ajalt** [comment]
You don't need Clikt for that; you can use standard functionality like `ProcessBuilder` or `Runtime.exec()` etc.

**Comment by saket** [comment]
Whoops sorry I missed this. 

Not sure if I understood your answer. I want to print a message depending upon the user's operating system in my command built by Clikt. I'm not trying to use Clikt solely for getting the user's OS. Can I run `Runtime.exec()` from inside a `CliktCommand`?

**Comment by ajalt** [comment]
You sure can. Although if you just need to know the current OS, you might be able to use `System.getProperty("os.name")` instead of running a separate program.

**Comment by saket** [comment]
Ah okay. I must have missed something. Will report back if I find myself stuck. Thank you!
