### ISSUE TITLE
Atom Editor support

### ISSUE THREAD

**Issue by Neristance** [ajalt/clikt#97]
Hi,

First of all, I really like CLIKT looks promising to me but however after some stuff, I implemented with it I would have some improvement.

In my past, I did write most of my cli tools in python, there I did open Atom to edit longer text for convenience. But I cant use it with the TermUi tools since atom needs to be started by using
` atom --wait file.xyz`

Would it be an option to support such editors as well?

Thanks!

**Comment by ajalt** [comment]
Probably. Can you give me an example of the code you're writing now that doesn't work for your use case?

**Comment by sebokopter** [comment]
```java
class AtomWaitCommand : CliktCommand(name = "atom") {
    override fun run() {
        echo(
            TermUi.editText(
                "# insert message and save",
                editor = "atom --wait"
            ) // this will throw an CliktError("Error staring editor")
        )
    }
}
```
It is not working since Java's ProcessBuilder does not allow whitespace separated commands, instead it must split into ["atom", "--wait", filename]. See #101
