### ISSUE TITLE
Kotlin Coroutines Support

### ISSUE THREAD

**Issue by matvey-mtn** [ajalt/clikt#98]
In my company, we have a core application that we want to wrap as CLI and reuse as WEB application’s backend in the future.

   [CLI Module] -> [Core Module] <- [WEB (Rest-API) Module]

A core module is written using Vert.x and Kotlin Coroutines, and it's asynchronous by design.

Communication between `CLI Module` and `Core Module` components should be done by sending messages via Vert.x Event Bus. By design, our CLI Module should parse the command and trigger business logic which at some stage will require to send a message via Vert.x event bus and handle the response. For instance: 

```
val message = vertx.eventBus().requestAwait<Any>(address, message)
```

We tried to utilize `Clikt` as a library of choice for our `CLI Module`. But here's the problem: `Clikt` doesn't have a suspending version of `com.github.ajalt.clikt.core.CliktCommand#run` method and `requestAwait` can be only used inside CoroutineScope or another suspend function.

At this point we have 2 possible solutions: either use `runBlocking {  }` everywhere in our CLI module or build our CLI module without coroutines (in a synchronous fashion) + use `io.vertx.core.eventbus.EventBus#request(String, String)` method.

None of these options are fully satisfying, because the first option is really weird, and the second one will require to work a lot with callbacks.

Is there a better way to work with Clikt when using Coroutines? If not, are there any plans to provide support for Coroutines and suspend functions in `Clikt`?

Thanks in advance.

**Comment by ajalt** [comment]
I recommend using `runBlocking`

```kotlin
override fun run() = runBlocking {
    mySuspendingFunction()
}
```

Here's an example of an existing app that takes that approach:

https://github.com/JakeWharton/SdkSearch/blob/abb9ee2845382fd8448fe4831d1911a01c1976b2/references/validator/src/main/kotlin/com/jakewharton/sdksearch/reference/validator/ReferenceValidator.kt#L25

**Comment by matvey-mtn** [comment]
Cool. Thanks.

**Comment by russellbanks** [comment]
> I recommend using `runBlocking`

How could I deal with this for a Kotlin native application that doesn't have access to runBlocking?

**Comment by ajalt** [comment]
@russellbanks it depends on what you're trying to accomplish, but you could do something like launch your async code [as a promise][1] at the end of your `run` function.

[1]: https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/as-promise.html

**Comment by russellbanks** [comment]
> @russellbanks it depends on what you're trying to accomplish

I'm just trying to run a suspending function in commonMain which doesn't have access to runblocking or promises. Usually you would do suspend fun but CliktCommand overrides a non-suspending function

**Comment by ajalt** [comment]
How would you accomplish that without if you weren't using clikt? Whatever approach you take, you should be able to do that either at the end of `run` or after `command.main` returns.

**Comment by russellbanks** [comment]
If I didn't use Clikt I would just use suspend fun. Currently I just don't have JS as a target so I can use runBlocking.

```kotlin
suspend fun main() {
   suspendingFunction()
}
```

For context, this is the file I'm referring to: [russellbanks/Skan/blob/main/src/commonMain/kotlin/Skan.kt](https://github.com/russellbanks/Skan/blob/main/src/commonMain/kotlin/Skan.kt)

**Comment by ajalt** [comment]
Then I would do the suspending work outside the command.

```kotlin
suspend fun main(args) {
    val command = MyCommand()
    command.main(args)
    mySuspendingFunction(command.option1, command.option2)
}
```

**Comment by simaotwx** [comment]
> Then I would do the suspending work outside the command.
> 
> ```kotlin
> suspend fun main(args) {
>     val command = MyCommand()
>     command.main(args)
>     mySuspendingFunction(command.option1, command.option2)
> }
> ```

In that case `main` should be called something else, like `parse`.

The code could look like this and it would be cleaner that way IMO:

```kotlin
val command = MyCommand().parse(args)
```

And you could go crazy and do this:

```kotlin
suspend fun main() = MyCommand().parse(args).let { command ->

}
```

Currently this is how you can do it:

```kotlin
suspend fun main(args: Array<String>) = Command().apply { main(args) }.let { command ->

}
```
